const questionData = [
    // --- 1. 基礎理論 (Basic Theory) ---
    { id: 1, cat: "基礎理論", zh: "位元", ja: "ビット", yomi: "びっと", eng: "Bit", desc_zh: "最小的資訊單位，只能表示 0 或 1。", desc_ja: "情報の最小単位。0 または 1 のいずれかを表します。" },
    { id: 2, cat: "基礎理論", zh: "位元組", ja: "バイト", yomi: "ばいと", eng: "Byte", desc_zh: "由 8 個位元組成，通常用來表示一個字元。", desc_ja: "8ビットから構成され、通常、1文字を表す単位です。" },
    { id: 3, cat: "基礎理論", zh: "二進位", ja: "2進数", yomi: "にしんすう", eng: "Binary Number", desc_zh: "僅使用 0 和 1 來表示數值的系統。", desc_ja: "0 と 1 のみを用いて数を表現する方法。" },
    { id: 4, cat: "基礎理論", zh: "二補數", ja: "2の補数", yomi: "にのほすう", eng: "Two's Complement", desc_zh: "在電腦中表示負數的方法。", desc_ja: "コンピュータで負の数を表現する方法。" },
    { id: 5, cat: "基礎理論", zh: "浮點數", ja: "浮動小数点", yomi: "ふどうしょうすうてん", eng: "Floating Point", desc_zh: "用於表示實數，由符號、指數、尾數組成。", desc_ja: "実数を表現する方式。符号、指数、仮数からなる。" },
    { id: 6, cat: "基礎理論", zh: "捨位誤差", ja: "丸め誤差", yomi: "まるめごさ", eng: "Rounding Error", desc_zh: "因位數有限，四雪五入或無條件捨去導致的計算誤差。", desc_ja: "桁数制限により、四捨五入や切り捨てで生じる計算誤差。" },
    { id: 7, cat: "基礎理論", zh: "AND 閘", ja: "AND ゲート", yomi: "あんどげーと", eng: "AND Gate", desc_zh: "邏輯乘。所有輸入為 1 時，輸出才為 1。", desc_ja: "論理積。全ての入力が 1 の時のみ、出力が 1 となる。" },
    { id: 8, cat: "基礎理論", zh: "OR 閘", ja: "OR ゲート", yomi: "おあげーと", eng: "OR Gate", desc_zh: "邏輯和。任一輸入為 1 時，輸出即為 1。", desc_ja: "論理和。いずれかの入力が 1 の時、出力が 1 となる。" },
    { id: 9, cat: "基礎理論", zh: "XOR 閘", ja: "排他的論理和", yomi: "はいたてきろんりわ", eng: "Exclusive OR (XOR)", desc_zh: "當兩個輸入不同時，輸出為 1。", desc_ja: "2つの入力が異なるときのみ、出力が 1 となる。" },
    { id: 10, cat: "基礎理論", zh: "資訊量", ja: "情報量", yomi: "じょうほうりょう", eng: "Information Amount", desc_zh: "事件發生機率越低，資訊量越大。", desc_ja: "事象の発生確率が低いほど、情報量は大きくなる。" },
    { id: 51, cat: "基礎理論", zh: "堆疊", ja: "スタック", yomi: "すたっく", eng: "Stack", desc_zh: "後進先出 (LIFO) 的資料結構。", desc_ja: "後入れ先出し (LIFO) のデータ構造。" },
    { id: 52, cat: "基礎理論", zh: "佇列", ja: "キュー", yomi: "きゅー", eng: "Queue", desc_zh: "先進先出 (FIFO) 的資料結構。", desc_ja: "先入れ先出し (FIFO) のデータ構造。" },
    { id: 53, cat: "基礎理論", zh: "陣列", ja: "配列", yomi: "はいれつ", eng: "Array", desc_zh: "相同類型的資料連續排列的結構。", desc_ja: "同じ型のデータを連続的に並べた構造。" },
    { id: 54, cat: "基礎理論", zh: "連結串列", ja: "連結リスト", yomi: "れんけつりすと", eng: "Linked List", desc_zh: "資料包含指向下一個資料位址的結構。", desc_ja: "データが次のデータの場所を指し示す構造。" },
    { id: 55, cat: "基礎理論", zh: "二元樹", ja: "二分木", yomi: "にぶんぎ", eng: "Binary Tree", desc_zh: "每個節點最多有兩個子節點的樹狀結構。", desc_ja: "各ノードが最大2つの子を持つ木構造。" },
    { id: 56, cat: "基礎理論", zh: "線性搜尋", ja: "線形探索", yomi: "せんけいたんさく", eng: "Linear Search", desc_zh: "從頭開始依序尋找資料的方法。", desc_ja: "先頭から順にデータを探す方法。" },
    { id: 57, cat: "基礎理論", zh: "二分搜尋", ja: "二分探索", yomi: "にぶんたんさく", eng: "Binary Search", desc_zh: "在已排序的資料中，反覆將範圍減半來搜尋。", desc_ja: "整列済みデータの中央を見て、範囲を半分に絞る探索法。" },
    { id: 58, cat: "基礎理論", zh: "雜湊法", ja: "ハッシュ法", yomi: "はっしゅほう", eng: "Hashing", desc_zh: "利用函數計算儲存位置，實現快速存取。", desc_ja: "関数で格納場所を計算し、高速アクセスを実現する。" },
    { id: 59, cat: "基礎理論", zh: "氣泡排序", ja: "バブルソート", yomi: "ばぶるそーと", eng: "Bubble Sort", desc_zh: "重複交換相鄰元素以進行排序。", desc_ja: "隣り合う要素を交換しながら整列する。" },
    { id: 60, cat: "基礎理論", zh: "快速排序", ja: "クイックソート", yomi: "くいっくそーと", eng: "Quick Sort", desc_zh: "選定基準值分割資料的高速排序法。", desc_ja: "基準値を決めてデータを分割する高速な整列法。" },
    // --- 新增 151-160 (演算法與邏輯) ---
    { id: 151, cat: "基礎理論", zh: "逆波蘭表示法", ja: "逆ポーランド記法", yomi: "ぎゃくぽーらんどきほう", eng: "Reverse Polish Notation", desc_zh: "將運算子寫在運算元後面的表示法 (如 AB+)。", desc_ja: "演算子を被演算子の後ろに記述する方法。" },
    { id: 152, cat: "基礎理論", zh: "遞迴", ja: "再帰", yomi: "さいき", eng: "Recursive", desc_zh: "函數在執行過程中呼叫自身的技巧。", desc_ja: "関数が自分自身を呼び出すこと。" },
    { id: 153, cat: "基礎理論", zh: "演算法複雜度", ja: "計算量", yomi: "けいさんりょう", eng: "Computational Complexity", desc_zh: "衡量演算法執行時間或空間的指標 (如 O(n))。", desc_ja: "アルゴリズムの実行時間やメモリ使用量の尺度。" },
    { id: 154, cat: "基礎理論", zh: "有限狀態機", ja: "オートマトン", yomi: "おーとまとん", eng: "Automaton", desc_zh: "根據輸入在不同狀態間轉換的模型。", desc_ja: "入力に応じて状態が遷移するモデル。" },
    { id: 155, cat: "基礎理論", zh: "真值表", ja: "真理値表", yomi: "しんりちひょう", eng: "Truth Table", desc_zh: "列出邏輯電路所有可能輸入與輸出的表格。", desc_ja: "論理回路の全入力と出力の組み合わせを表にしたもの。" },
    { id: 156, cat: "基礎理論", zh: "NAND 閘", ja: "NAND ゲート", yomi: "なんどげーと", eng: "NAND Gate", desc_zh: "NOT AND。只有當所有輸入為 1 時，輸出才為 0。", desc_ja: "入力が全て1の時だけ0を出力する。" },
    { id: 157, cat: "基礎理論", zh: "堆積", ja: "ヒープ", yomi: "ひーぷ", eng: "Heap", desc_zh: "一種特殊的樹狀結構，用於優先權佇列。", desc_ja: "優先度付きキューなどに使われる木構造。" },
    { id: 158, cat: "基礎理論", zh: "雜湊碰撞", ja: "シノニム", yomi: "しのにむ", eng: "Synonym / Collision", desc_zh: "雜湊法中，不同資料計算出相同雜湊值的現象。", desc_ja: "ハッシュ法で異なるデータから同じハッシュ値が出ること。" },
    { id: 159, cat: "基礎理論", zh: "根目錄", ja: "ルートディレクトリ", yomi: "るーとでぃれくとり", eng: "Root Directory", desc_zh: "檔案系統階層結構的最頂層。", desc_ja: "ファイル階層構造の最上位。" },
    { id: 160, cat: "基礎理論", zh: "絕對路徑", ja: "絶対パス", yomi: "ぜったいぱす", eng: "Absolute Path", desc_zh: "從根目錄開始完整描述檔案位置的路徑。", desc_ja: "ルートからファイル位置を完全に記述するパス。" },

    // --- 2. 電腦系統：硬體 (Hardware) ---
    { id: 11, cat: "電腦系統", zh: "馮·諾伊曼架構", ja: "ノイマン型", yomi: "のいまんがた", eng: "Von Neumann", desc_zh: "程式內建方式，指令和資料都存在記憶體中。", desc_ja: "命令とデータがメモリに格納される方式。" },
    { id: 12, cat: "電腦系統", zh: "CPU", ja: "中央処理装置", yomi: "ちゅうおうしょりそうち", eng: "CPU", desc_zh: "負責執行指令與運算。", desc_ja: "命令の実行と演算を行う。" },
    { id: 13, cat: "電腦系統", zh: "快取記憶體", ja: "キャッシュメモリ", yomi: "きゃっしゅめもり", eng: "Cache", desc_zh: "位於 CPU 與 RAM 之間，加速資料存取。", desc_ja: "CPUとRAMの間にあり高速化する。" },
    { id: 14, cat: "電腦系統", zh: "RAM", ja: "RAM", yomi: "らむ", eng: "RAM", desc_zh: "揮發性記憶體，電源關閉後資料消失。", desc_ja: "電源を切るとデータが消える揮発性メモリ。" },
    { id: 15, cat: "電腦系統", zh: "ROM", ja: "ROM", yomi: "ろむ", eng: "ROM", desc_zh: "非揮發性記憶體，儲存 BIOS 等。", desc_ja: "不揮発性メモリ。BIOS等を保存。" },
    { id: 16, cat: "電腦系統", zh: "虛擬記憶體", ja: "仮想記憶", yomi: "かそうきおく", eng: "Virtual Memory", desc_zh: "將硬碟當作記憶體使用。", desc_ja: "HDDをメモリの一部として扱う技術。" },
    { id: 17, cat: "電腦系統", zh: "RAID 0", ja: "ストライピング", yomi: "すとらいぴんぐ", eng: "Striping", desc_zh: "資料分散寫入，速度快但無容錯。", desc_ja: "分散書き込み。高速だが耐障害性なし。" },
    { id: 18, cat: "電腦系統", zh: "RAID 1", ja: "ミラーリング", yomi: "みらーりんぐ", eng: "Mirroring", desc_zh: "資料完整複製到兩顆硬碟。", desc_ja: "複製書き込み。信頼性が高い。" },
    { id: 19, cat: "電腦系統", zh: "RAID 5", ja: "RAID 5", yomi: "れーどふぁいぶ", eng: "RAID 5", desc_zh: "分散寫入資料與同位檢查碼。", desc_ja: "データとパリティを分散書き込み。" },
    { id: 61, cat: "電腦系統", zh: "GPU", ja: "GPU", yomi: "じーぴーゆー", eng: "GPU", desc_zh: "圖形處理器，擅長並行運算 (AI/圖像)。", desc_ja: "画像処理装置。並列処理が得意。" },
    { id: 62, cat: "電腦系統", zh: "SSD", ja: "SSD", yomi: "えすえすでぃー", eng: "SSD", desc_zh: "使用快閃記憶體的儲存裝置，速度快。", desc_ja: "フラッシュメモリを使った高速記憶装置。" },
    { id: 63, cat: "電腦系統", zh: "RFID", ja: "RFID", yomi: "あーるえふあいでぃー", eng: "RFID", desc_zh: "無線電波非接觸讀寫技術 (IC卡)。", desc_ja: "電波による非接触データ通信。" },
    { id: 64, cat: "電腦系統", zh: "NFC", ja: "NFC", yomi: "えぬえふしー", eng: "NFC", desc_zh: "近距離無線通訊 (手機支付)。", desc_ja: "近距離無線通信 (スマホ決済等)。" },
    { id: 65, cat: "電腦系統", zh: "OCR", ja: "OCR", yomi: "おーしーあーる", eng: "OCR", desc_zh: "將圖片文字轉換為文字資料。", desc_ja: "画像内の文字をテキスト化する。" },
    // --- 新增 161-175 (硬體細節) ---
    { id: 161, cat: "電腦系統", zh: "暫存器", ja: "レジスタ", yomi: "れじすた", eng: "Register", desc_zh: "CPU 內部速度最快的超小型記憶體。", desc_ja: "CPU内部にある超高速な記憶領域。" },
    { id: 162, cat: "電腦系統", zh: "時脈頻率", ja: "クロック周波数", yomi: "くろっくしゅうはすう", eng: "Clock Frequency", desc_zh: "CPU 每秒執行的週期數 (Hz)，越高越快。", desc_ja: "CPUの処理速度の指標。Hzで表す。" },
    { id: 163, cat: "電腦系統", zh: "匯流排", ja: "バス", yomi: "ばす", eng: "Bus", desc_zh: "電腦內部傳輸資料的通道。", desc_ja: "コンピュータ内部のデータ伝送路。" },
    { id: 164, cat: "電腦系統", zh: "A/D轉換器", ja: "A/D変換器", yomi: "えーでぃーへんかんき", eng: "A/D Converter", desc_zh: "將類比訊號 (如聲音) 轉為數位訊號。", desc_ja: "アナログ信号をデジタル信号に変換する。" },
    { id: 165, cat: "電腦系統", zh: "致動器", ja: "アクチュエータ", yomi: "あくちゅえーた", eng: "Actuator", desc_zh: "將電訊號轉換為物理動作的裝置 (如馬達)。", desc_ja: "電気信号を物理的な動きに変える装置。" },
    { id: 166, cat: "電腦系統", zh: "感測器", ja: "センサ", yomi: "せんさ", eng: "Sensor", desc_zh: "檢測物理量 (光、溫度) 並轉為電子訊號。", desc_ja: "物理量(光・温度)を検知し信号にする。" },
    { id: 167, cat: "電腦系統", zh: "嵌入式系統", ja: "組込みシステム", yomi: "くみこみしすてむ", eng: "Embedded System", desc_zh: "內建於家電或機器中，執行特定功能的電腦。", desc_ja: "家電等に内蔵され特定機能を実現するPC。" },
    { id: 168, cat: "電腦系統", zh: "隨插即用", ja: "プラグアンドプレイ", yomi: "ぷらぐあんどぷれい", eng: "Plug and Play", desc_zh: "連接裝置後自動設定即可使用。", desc_ja: "機器接続時に自動設定ですぐ使える機能。" },
    { id: 169, cat: "電腦系統", zh: "HDMI", ja: "HDMI", yomi: "えいちでぃーえむあい", eng: "HDMI", desc_zh: "傳輸高品質影像與聲音的數位介面。", desc_ja: "映像と音声を伝送するデジタル端子。" },
    { id: 170, cat: "電腦系統", zh: "USB", ja: "USB", yomi: "ゆーえすびー", eng: "USB", desc_zh: "通用的序列匯流排介面，支援熱插拔。", desc_ja: "汎用的なシリアルバス規格。" },
    { id: 171, cat: "電腦系統", zh: "藍牙", ja: "Bluetooth", yomi: "ぶるーとぅーす", eng: "Bluetooth", desc_zh: "短距離低功耗的無線通訊技術。", desc_ja: "近距離・低消費電力の無線通信技術。" },
    { id: 172, cat: "電腦系統", zh: "SRAM", ja: "SRAM", yomi: "えすらむ", eng: "Static RAM", desc_zh: "速度快不需要更新動作，常用於快取。", desc_ja: "高速でリフレッシュ不要。キャッシュに利用。" },
    { id: 173, cat: "電腦系統", zh: "DRAM", ja: "DRAM", yomi: "でぃーらむ", eng: "Dynamic RAM", desc_zh: "需要定期更新動作，容量大，常用於主記憶體。", desc_ja: "リフレッシュ必要。主記憶に利用。" },
    { id: 174, cat: "電腦系統", zh: "快閃記憶體", ja: "フラッシュメモリ", yomi: "ふらっしゅめもり", eng: "Flash Memory", desc_zh: "一種可電子抹除的非揮發性記憶體 (如 USB 隨身碟)。", desc_ja: "電気的に消去可能な不揮発性メモリ。" },
    { id: 175, cat: "電腦系統", zh: "多核心", ja: "マルチコア", yomi: "まるちこあ", eng: "Multi-core", desc_zh: "一個 CPU 封裝中包含多個處理核心。", desc_ja: "1つのCPUに複数の処理コアを持つこと。" },

    // --- 3. 電腦系統：OS 與軟體 ---
    { id: 66, cat: "電腦系統", zh: "OSS", ja: "OSS", yomi: "おーえすえす", eng: "Open Source", desc_zh: "原始碼公開且可自由修改的軟體。", desc_ja: "ソースが公開され修正可能なソフト。" },
    { id: 67, cat: "電腦系統", zh: "BIOS", ja: "BIOS", yomi: "ばいおす", eng: "BIOS", desc_zh: "啟動時最先執行，控制硬體。", desc_ja: "起動時にハードウェアを制御する。" },
    { id: 68, cat: "電腦系統", zh: "中介軟體", ja: "ミドルウェア", yomi: "みどるうぇあ", eng: "Middleware", desc_zh: "OS 與應用程式之間的軟體。", desc_ja: "OSとアプリの間で機能を提供する。" },
    { id: 69, cat: "電腦系統", zh: "API", ja: "API", yomi: "えーぴーあい", eng: "API", desc_zh: "軟體間交換資料的介面。", desc_ja: "ソフト同士が連携するための窓口。" },
    { id: 70, cat: "電腦系統", zh: "批次處理", ja: "バッチ処理", yomi: "ばっちしょり", eng: "Batch Processing", desc_zh: "累積資料後一次性處理。", desc_ja: "データをためて一括処理する。" },
    { id: 71, cat: "電腦系統", zh: "即時處理", ja: "リアルタイム処理", yomi: "りあるたいむしょり", eng: "Real-time", desc_zh: "資料產生時立即處理。", desc_ja: "データ発生時に即座に処理する。" },
    { id: 72, cat: "電腦系統", zh: "備份", ja: "バックアップ", yomi: "ばっくあっぷ", eng: "Backup", desc_zh: "複製資料以防遺失。", desc_ja: "データ消失に備えて複製をとる。" },
    { id: 73, cat: "電腦系統", zh: "完整備份", ja: "フルバックアップ", yomi: "ふるばっくあっぷ", eng: "Full Backup", desc_zh: "備份所有資料。", desc_ja: "全てのデータをバックアップする。" },
    { id: 74, cat: "電腦系統", zh: "差異備份", ja: "差分バックアップ", yomi: "さぶんばっくあっぷ", eng: "Differential", desc_zh: "備份自上次完整備份後的變更。", desc_ja: "前回フルバックアップからの変更分。" },
    { id: 75, cat: "電腦系統", zh: "增量備份", ja: "増分バックアップ", yomi: "ぞうぶんばっくあっぷ", eng: "Incremental", desc_zh: "備份自上次任何備份後的變更。", desc_ja: "前回バックアップからの変更分。" },
    // --- 新增 176-190 (OS 排程與管理) ---
    { id: 176, cat: "電腦系統", zh: "周轉時間", ja: "ターンアラウンドタイム", yomi: "たーんあらうんどたいむ", eng: "Turnaround Time", desc_zh: "從提交工作到輸出結果的總時間。", desc_ja: "処理依頼から結果出力までの全時間。" },
    { id: 177, cat: "電腦系統", zh: "回應時間", ja: "レスポンスタイム", yomi: "れすぽんすたいむ", eng: "Response Time", desc_zh: "從發出指令到系統開始反應的時間。", desc_ja: "指示から反応が始まるまでの時間。" },
    { id: 178, cat: "電腦系統", zh: "吞吐量", ja: "スループット", yomi: "するーぷっと", eng: "Throughput", desc_zh: "單位時間內處理的工作量。", desc_ja: "単位時間あたりの処理能力。" },
    { id: 179, cat: "電腦系統", zh: "多工處理", ja: "マルチタスク", yomi: "まるちたすく", eng: "Multitasking", desc_zh: "同時執行多個程式的技術。", desc_ja: "複数の処理を並行して行う技術。" },
    { id: 180, cat: "電腦系統", zh: "假脫機", ja: "スプーリング", yomi: "すぷーりんぐ", eng: "Spooling", desc_zh: "將資料暫存於硬碟，以緩解印表機等慢速裝置的等待。", desc_ja: "データを一時保存し、低速装置の待ちを減らす。" },
    { id: 181, cat: "電腦系統", zh: "死結", ja: "デッドロック", yomi: "でっどろっく", eng: "Deadlock", desc_zh: "兩個程序互等對方釋放資源，導致停擺。", desc_ja: "処理が互いの資源空きを待ち、停止する状態。" },
    { id: 182, cat: "電腦系統", zh: "記憶體洩漏", ja: "メモリリーク", yomi: "めもりりーく", eng: "Memory Leak", desc_zh: "程式未釋放不再使用的記憶體，導致可用空間減少。", desc_ja: "メモリが解放されず、使用可能領域が減る現象。" },
    { id: 183, cat: "電腦系統", zh: "碎片化", ja: "フラグメンテーション", yomi: "ふらぐめんてーしょん", eng: "Fragmentation", desc_zh: "記憶體或硬碟空間變得零散，降低效率。", desc_ja: "記憶領域が断片化し、効率が落ちる現象。" },
    { id: 184, cat: "電腦系統", zh: "排程", ja: "スケジューリング", yomi: "すけじゅーりんぐ", eng: "Scheduling", desc_zh: "決定 CPU 分配給哪個程序的機制。", desc_ja: "CPUをどの処理に割り当てるか決めること。" },
    { id: 185, cat: "電腦系統", zh: "輪詢", ja: "ラウンドロビン", yomi: "らうんどろびん", eng: "Round Robin", desc_zh: "依序分配固定時間給每個程序。", desc_ja: "各処理に一定時間を順に割り当てる方式。" },
    { id: 186, cat: "電腦系統", zh: "目錄", ja: "ディレクトリ", yomi: "でぃれくとり", eng: "Directory", desc_zh: "用於分類和管理檔案的資料夾。", desc_ja: "ファイルを整理・管理するフォルダ。" },
    { id: 187, cat: "電腦系統", zh: "壓縮", ja: "圧縮", yomi: "あっしゅく", eng: "Compression", desc_zh: "縮小檔案容量的技術 (可逆/不可逆)。", desc_ja: "データのサイズを小さくする技術。" },
    { id: 188, cat: "電腦系統", zh: "封存", ja: "アーカイブ", yomi: "あーかいぶ", eng: "Archive", desc_zh: "將多個檔案整合成一個檔案，常伴隨壓縮。", desc_ja: "複数ファイルを一つにまとめること。" },
    { id: 189, cat: "電腦系統", zh: "GUI", ja: "GUI", yomi: "じーゆーあい", eng: "Graphical User Interface", desc_zh: "透過圖形和滑鼠操作的介面。", desc_ja: "画像やマウスで操作する画面。" },
    { id: 190, cat: "電腦系統", zh: "CUI", ja: "CUI", yomi: "しーゆーあい", eng: "Character User Interface", desc_zh: "透過鍵盤輸入文字指令操作的介面。", desc_ja: "文字入力で操作する画面。" },

    // --- 4. 電腦系統：網路 (Network) ---
    { id: 25, cat: "電腦系統", zh: "OSI模型", ja: "OSI参照モデル", yomi: "おーえすあい", eng: "OSI Model", desc_zh: "通訊7層模型。", desc_ja: "通信の7階層モデル。" },
    { id: 26, cat: "電腦系統", zh: "TCP/IP", ja: "TCP/IP", yomi: "てぃーしーぴー", eng: "TCP/IP", desc_zh: "網際網路標準協定。", desc_ja: "ネットの標準プロトコル。" },
    { id: 27, cat: "電腦系統", zh: "IP地址", ja: "IPアドレス", yomi: "あいぴーあどれす", eng: "IP Address", desc_zh: "網路邏輯位址。", desc_ja: "ネット上の住所。" },
    { id: 28, cat: "電腦系統", zh: "MAC地址", ja: "MACアドレス", yomi: "まっくあどれす", eng: "MAC Address", desc_zh: "硬體實體位址。", desc_ja: "機器の物理アドレス。" },
    { id: 29, cat: "電腦系統", zh: "DHCP", ja: "DHCP", yomi: "でぃーえいちしーぴー", eng: "DHCP", desc_zh: "自動分配 IP。", desc_ja: "IP自動割り当て。" },
    { id: 30, cat: "電腦系統", zh: "NAT", ja: "NAT", yomi: "なっと", eng: "NAT", desc_zh: "轉換私有與公共 IP。", desc_ja: "IPアドレス変換。" },
    { id: 81, cat: "電腦系統", zh: "DNS", ja: "DNS", yomi: "でぃーえぬえす", eng: "DNS", desc_zh: "網域名稱轉 IP。", desc_ja: "ドメイン名をIPに変換。" },
    { id: 82, cat: "電腦系統", zh: "HTTP", ja: "HTTP", yomi: "えいちてぃーてぃーぴー", eng: "HTTP", desc_zh: "網頁傳輸協定。", desc_ja: "Web通信プロトコル。" },
    { id: 83, cat: "電腦系統", zh: "SMTP", ja: "SMTP", yomi: "えすえむてぃーぴー", eng: "SMTP", desc_zh: "發信協定。", desc_ja: "メール送信プロトコル。" },
    { id: 84, cat: "電腦系統", zh: "POP3", ja: "POP3", yomi: "ぽっぷすりー", eng: "POP3", desc_zh: "收信協定 (下載後刪除)。", desc_ja: "メール受信 (DL後削除)。" },
    { id: 85, cat: "電腦系統", zh: "IMAP", ja: "IMAP", yomi: "あいまっぷ", eng: "IMAP", desc_zh: "收信協定 (在伺服器管理)。", desc_ja: "メール受信 (サーバ管理)。" },
    { id: 86, cat: "電腦系統", zh: "FTP", ja: "FTP", yomi: "えふてぃーぴー", eng: "FTP", desc_zh: "檔案傳輸協定。", desc_ja: "ファイル転送。" },
    { id: 87, cat: "電腦系統", zh: "NTP", ja: "NTP", yomi: "えぬてぃーぴー", eng: "NTP", desc_zh: "時間同步協定。", desc_ja: "時刻同期。" },
    { id: 88, cat: "電腦系統", zh: "ARP", ja: "ARP", yomi: "あーぷ", eng: "ARP", desc_zh: "IP 轉 MAC。", desc_ja: "IPからMACを調査。" },
    { id: 89, cat: "電腦系統", zh: "路由器", ja: "ルータ", yomi: "るーた", eng: "Router", desc_zh: "不同網路間的路徑選擇。", desc_ja: "NW間の経路選択。" },
    { id: 90, cat: "電腦系統", zh: "交換器", ja: "スイッチ", yomi: "すいっち", eng: "Switch", desc_zh: "同網路內的資料轉發。", desc_ja: "NW内のデータ転送。" },
    // --- 新增 191-210 (網路進階) ---
    { id: 191, cat: "電腦系統", zh: "子網路遮罩", ja: "サブネットマスク", yomi: "さぶねっとますく", eng: "Subnet Mask", desc_zh: "用來區分 IP 位址中網路位址與主機位址。", desc_ja: "IPアドレスのNW部とホスト部を分ける。" },
    { id: 192, cat: "電腦系統", zh: "預設閘道", ja: "デフォルトゲートウェイ", yomi: "でふぉるとげーとうぇい", eng: "Default Gateway", desc_zh: "通往外部網路的出口 (通常是路由器)。", desc_ja: "外部NWへの出入り口 (ルータ等)。" },
    { id: 193, cat: "電腦系統", zh: "IPv6", ja: "IPv6", yomi: "あいぴーぶいろく", eng: "IPv6", desc_zh: "128位元的 IP 地址，解決 IPv4 枯竭問題。", desc_ja: "128ビットのIPアドレス。IPv4枯渇対策。" },
    { id: 194, cat: "電腦系統", zh: "連接埠號", ja: "ポート番号", yomi: "ぽーとばんごう", eng: "Port Number", desc_zh: "識別通訊應用程式的編號 (如 80=Web)。", desc_ja: "アプリを識別する番号 (80=Web等)。" },
    { id: 195, cat: "電腦系統", zh: "HTTPS", ja: "HTTPS", yomi: "えいちてぃーてぃーぴーえす", eng: "HTTPS", desc_zh: "加密的 HTTP 通訊，安全傳輸網頁。", desc_ja: "暗号化されたWeb通信。" },
    { id: 196, cat: "電腦系統", zh: "SSH", ja: "SSH", yomi: "えすえすえいち", eng: "Secure Shell", desc_zh: "遠端安全登入並操作電腦的協定。", desc_ja: "遠隔地から安全に操作するプロトコル。" },
    { id: 197, cat: "電腦系統", zh: "代理伺服器", ja: "プロキシ", yomi: "ぷろきし", eng: "Proxy", desc_zh: "代替內部電腦存取網際網路的伺服器。", desc_ja: "代理でネット接続するサーバ。" },
    { id: 198, cat: "電腦系統", zh: "LAN", ja: "LAN", yomi: "らん", eng: "Local Area Network", desc_zh: "區域網路 (如辦公室或家庭內)。", desc_ja: "構内ネットワーク。" },
    { id: 199, cat: "電腦系統", zh: "WAN", ja: "WAN", yomi: "わん", eng: "Wide Area Network", desc_zh: "廣域網路 (連接不同地點的網路)。", desc_ja: "広域ネットワーク。" },
    { id: 200, cat: "電腦系統", zh: "Ping", ja: "Ping", yomi: "ぴん", eng: "Ping", desc_zh: "確認網路連線是否通暢的指令。", desc_ja: "接続確認を行うコマンド。" },
    { id: 201, cat: "電腦系統", zh: "封包", ja: "パケット", yomi: "ぱけっと", eng: "Packet", desc_zh: "網路傳輸的資料小塊。", desc_ja: "通信データの小包。" },
    { id: 202, cat: "電腦系統", zh: "VLAN", ja: "VLAN", yomi: "ぶいらん", eng: "Virtual LAN", desc_zh: "在物理網路上邏輯分割出的虛擬網路。", desc_ja: "仮想的に分割されたLAN。" },
    { id: 203, cat: "電腦系統", zh: "ESSID", ja: "ESSID", yomi: "いーえすえすあいでぃー", eng: "ESSID", desc_zh: "無線網路基地台的識別名稱。", desc_ja: "無線LANアクセスポイントの識別名。" },
    { id: 204, cat: "電腦系統", zh: "MIME", ja: "MIME", yomi: "まいむ", eng: "MIME", desc_zh: "讓電子郵件支援文字以外格式 (圖片等) 的標準。", desc_ja: "メールで画像等を扱うための規格。" },
    { id: 205, cat: "電腦系統", zh: "VoIP", ja: "VoIP", yomi: "ぼいっぷ", eng: "Voice over IP", desc_zh: "在網路上傳輸語音的技術 (網路電話)。", desc_ja: "ネットで音声を送る技術 (IP電話)。" },
    { id: 206, cat: "電腦系統", zh: "SDN", ja: "SDN", yomi: "えすでぃーえぬ", eng: "Software Defined Networking", desc_zh: "透過軟體集中控制網路架構。", desc_ja: "ソフトでNW構成を制御する技術。" },
    { id: 207, cat: "電腦系統", zh: "迴路位址", ja: "ループバックアドレス", yomi: "るーぷばっくあどれす", eng: "Loopback Address", desc_zh: "指向本機自己的 IP (127.0.0.1)。", desc_ja: "自分自身を指すIP (127.0.0.1)。" },
    { id: 208, cat: "電腦系統", zh: "廣播", ja: "ブロードキャスト", yomi: "ぶろーどきゃすと", eng: "Broadcast", desc_zh: "向網路上所有裝置發送資料。", desc_ja: "NW内の全機器にデータを送る。" },
    { id: 209, cat: "電腦系統", zh: "串流", ja: "ストリーミング", yomi: "すとりーみんぐ", eng: "Streaming", desc_zh: "邊下載邊播放影音的技術。", desc_ja: "DLしながら再生する技術。" },
    { id: 210, cat: "電腦系統", zh: "IoT閘道器", ja: "IoTゲートウェイ", yomi: "あいおーてぃーげーとうぇい", eng: "IoT Gateway", desc_zh: "連接感測器與雲端的橋樑設備。", desc_ja: "センサとクラウドを繋ぐ中継機。" },

    // --- 5. 電腦系統：安全 (Security) ---
    { id: 31, cat: "電腦系統", zh: "公開金鑰加密", ja: "公開鍵暗号", yomi: "こうかいかぎあんごう", eng: "Public Key", desc_zh: "雙鑰匙：公鑰加密，私鑰解密。", desc_ja: "2つの鍵。公開鍵で暗号化、秘密鍵で復号。" },
    { id: 32, cat: "電腦系統", zh: "共通金鑰加密", ja: "共通鍵暗号", yomi: "きょうつうかぎあんごう", eng: "Symmetric Key", desc_zh: "單鑰匙：加密解密用同一把。", desc_ja: "1つの鍵。暗号化と復号が同じ。" },
    { id: 33, cat: "電腦系統", zh: "數位簽章", ja: "デジタル署名", yomi: "でじたるしょめい", eng: "Digital Signature", desc_zh: "防竄改與確認身分。", desc_ja: "改ざん検知と本人確認。" },
    { id: 91, cat: "電腦系統", zh: "防火牆", ja: "ファイアウォール", yomi: "ふぁいあうぉーる", eng: "Firewall", desc_zh: "阻擋未授權存取。", desc_ja: "不正アクセス遮断。" },
    { id: 92, cat: "電腦系統", zh: "WAF", ja: "WAF", yomi: "わふ", eng: "WAF", desc_zh: "Web 應用防火牆。", desc_ja: "Webアプリ用ファイアウォール。" },
    { id: 93, cat: "電腦系統", zh: "DMZ", ja: "DMZ", yomi: "でぃーえむぜっと", eng: "DMZ", desc_zh: "非軍事區，隔離內外網。", desc_ja: "外部公開用の隔離エリア。" },
    { id: 94, cat: "電腦系統", zh: "VPN", ja: "VPN", yomi: "ぶいぴーえぬ", eng: "VPN", desc_zh: "虛擬私有網路，加密通道。", desc_ja: "仮想的な専用線。" },
    { id: 95, cat: "電腦系統", zh: "惡意軟體", ja: "マルウェア", yomi: "まるうぇあ", eng: "Malware", desc_zh: "惡意程式總稱。", desc_ja: "悪意あるソフトの総称。" },
    { id: 96, cat: "電腦系統", zh: "勒索軟體", ja: "ランサムウェア", yomi: "らんさむうぇあ", eng: "Ransomware", desc_zh: "加密檔案勒索贖金。", desc_ja: "ファイルを人質に身代金要求。" },
    { id: 97, cat: "電腦系統", zh: "網路釣魚", ja: "フィッシング", yomi: "ふぃっしんぐ", eng: "Phishing", desc_zh: "偽裝網站騙個資。", desc_ja: "偽サイトで情報詐取。" },
    { id: 98, cat: "電腦系統", zh: "社交工程", ja: "ソーシャルエンジニアリング", yomi: "そーしゃる", eng: "Social Engineering", desc_zh: "利用心理弱點騙取資訊。", desc_ja: "心理的な隙をつく攻撃。" },
    { id: 99, cat: "電腦系統", zh: "DoS攻擊", ja: "DoS攻撃", yomi: "どすこうげき", eng: "DoS", desc_zh: "癱瘓伺服器。", desc_ja: "サーバ停止攻撃。" },
    { id: 100, cat: "電腦系統", zh: "SQL注入", ja: "SQLインジェクション", yomi: "えすきゅーえる", eng: "SQL Injection", desc_zh: "注入惡意 SQL 攻擊資料庫。", desc_ja: "DBを不正操作する攻撃。" },
    { id: 101, cat: "電腦系統", zh: "XSS", ja: "XSS", yomi: "くろすさいと", eng: "XSS", desc_zh: "網頁植入惡意腳本。", desc_ja: "Webに悪意あるスクリプト埋め込み。" },
    { id: 102, cat: "電腦系統", zh: "暴力破解", ja: "ブルートフォース", yomi: "ぶるーとふぉーす", eng: "Brute Force", desc_zh: "嘗試所有密碼組合。", desc_ja: "総当たり攻撃。" },
    { id: 103, cat: "電腦系統", zh: "多因素認證", ja: "多要素認証", yomi: "たようそにんしょう", eng: "MFA", desc_zh: "兩種以上驗證方式。", desc_ja: "2つ以上の要素で認証。" },
    { id: 104, cat: "電腦系統", zh: "生物辨識", ja: "バイオメトリクス", yomi: "ばいおめとりくす", eng: "Biometrics", desc_zh: "指紋、臉部等認證。", desc_ja: "生体情報での認証。" },
    { id: 105, cat: "電腦系統", zh: "CA", ja: "認証局", yomi: "にんしょうきょく", eng: "CA", desc_zh: "發行數位憑證的機構。", desc_ja: "証明書発行機関。" },
    // --- 新增 211-230 (資安進階) ---
    { id: 211, cat: "電腦系統", zh: "零信任", ja: "ゼロトラスト", yomi: "ぜろとらすと", eng: "Zero Trust", desc_zh: "不信任任何內外網，每次存取都驗證。", desc_ja: "全てを信頼せず毎回検証する概念。" },
    { id: 212, cat: "電腦系統", zh: "APT攻擊", ja: "APT攻撃", yomi: "えーぴーてぃーこうげき", eng: "APT Attack", desc_zh: "針對特定目標長期潛伏的持續性攻擊。", desc_ja: "特定の標的を執拗に攻撃する手法。" },
    { id: 213, cat: "電腦系統", zh: "字典攻擊", ja: "辞書攻撃", yomi: "じしょこうげき", eng: "Dictionary Attack", desc_zh: "使用常用單字列表嘗試破解密碼。", desc_ja: "単語リストを使ってパスワードを破る。" },
    { id: 214, cat: "電腦系統", zh: "彩虹表", ja: "レインボーテーブル", yomi: "れいんぼーてーぶる", eng: "Rainbow Table", desc_zh: "預先計算雜湊值以快速破解密碼的對照表。", desc_ja: "ハッシュ値を事前計算したクラック用表。" },
    { id: 215, cat: "電腦系統", zh: "加鹽", ja: "ソルト", yomi: "そると", eng: "Salting", desc_zh: "在密碼中加入隨機字串再雜湊，防止彩虹表攻擊。", desc_ja: "乱数を付加してハッシュ化し解読を防ぐ。" },
    { id: 216, cat: "電腦系統", zh: "鍵盤側錄", ja: "キーロガー", yomi: "きーろがー", eng: "Keylogger", desc_zh: "記錄使用者按鍵輸入的惡意軟體。", desc_ja: "キー入力操作を記録するスパイウェア。" },
    { id: 217, cat: "電腦系統", zh: "Rootkit", ja: "ルートキット", yomi: "るーときっと", eng: "Rootkit", desc_zh: "為了隱藏攻擊痕跡並維持入侵權限的工具包。", desc_ja: "侵入の痕跡を隠し権限を維持するツール。" },
    { id: 218, cat: "電腦系統", zh: "DDos攻擊", ja: "DDoS攻撃", yomi: "でぃーどすこうげき", eng: "DDoS Attack", desc_zh: "利用多台電腦分散同時發動 DoS 攻擊。", desc_ja: "多数の機器から一斉に攻撃を仕掛ける。" },
    { id: 219, cat: "電腦系統", zh: "加密雜湊函數", ja: "ハッシュ関数", yomi: "はっしゅかんすう", eng: "Hash Function", desc_zh: "將資料轉換為固定長度亂碼 (摘要) 的函數，不可逆。", desc_ja: "データを固定長の要約値に変換する関数。" },
    { id: 220, cat: "電腦系統", zh: "PKI", ja: "PKI", yomi: "ぴーけーあい", eng: "Public Key Infrastructure", desc_zh: "公開金鑰基礎建設，管理憑證的體系。", desc_ja: "公開鍵暗号基盤。証明書を管理する仕組み。" },
    { id: 221, cat: "電腦系統", zh: "CRL", ja: "CRL", yomi: "しーあーるえる", eng: "Certificate Revocation List", desc_zh: "憑證撤銷清單，列出已失效的數位憑證。", desc_ja: "有効期限前に無効になった証明書リスト。" },
    { id: 222, cat: "電腦系統", zh: "ISMS", ja: "ISMS", yomi: "あいえすえむえす", eng: "ISMS", desc_zh: "資訊安全管理系統 (如 ISO 27001)。", desc_ja: "情報セキュリティマネジメントシステム。" },
    { id: 223, cat: "電腦系統", zh: "機密性", ja: "機密性", yomi: "きみつせい", eng: "Confidentiality", desc_zh: "資安三要素之一，確保只有授權者能存取。", desc_ja: "許可された人だけがアクセスできること。" },
    { id: 224, cat: "電腦系統", zh: "完整性", ja: "完全性", yomi: "かんぜんせい", eng: "Integrity", desc_zh: "資安三要素之一，確保資料準確未被竄改。", desc_ja: "データが正確で改ざんされていないこと。" },
    { id: 225, cat: "電腦系統", zh: "可用性", ja: "可用性", yomi: "かようせい", eng: "Availability", desc_zh: "資安三要素之一，確保需要時能使用系統。", desc_ja: "必要な時にいつでも使えること。" },
    { id: 226, cat: "電腦系統", zh: "風險評估", ja: "リスクアセスメント", yomi: "りすくあせすめんと", eng: "Risk Assessment", desc_zh: "分析威脅與脆弱性，評估潛在損失。", desc_ja: "脅威や脆弱性を分析し損失を予測する。" },
    { id: 227, cat: "電腦系統", zh: "BYOD", ja: "BYOD", yomi: "びーわいおーでぃー", eng: "Bring Your Own Device", desc_zh: "員工攜帶私人設備處理公務。", desc_ja: "私物端末を業務に利用すること。" },
    { id: 228, cat: "電腦系統", zh: "MDM", ja: "MDM", yomi: "えむでぃーえむ", eng: "Mobile Device Management", desc_zh: "行動裝置管理，統一控管員工手機平板。", desc_ja: "モバイル端末を統合管理するシステム。" },
    { id: 229, cat: "電腦系統", zh: "VPN通道", ja: "トンネリング", yomi: "とんねりんぐ", eng: "Tunneling", desc_zh: "在網路上建立虛擬傳輸通道的技術。", desc_ja: "仮想的な通信路を作る技術。" },
    { id: 230, cat: "電腦系統", zh: "混合雲", ja: "ハイブリッドクラウド", yomi: "はいぶりっどくらうど", eng: "Hybrid Cloud", desc_zh: "結合私有雲與公有雲的架構。", desc_ja: "私有雲と公有雲を組み合わせた形態。" },

    // --- 6. 技術管理 (Dev & Project) ---
    { id: 34, cat: "技術管理", zh: "瀑布模型", ja: "ウォーターフォール", yomi: "うぉーたーふぉーる", eng: "Waterfall", desc_zh: "按順序開發，不回頭。", desc_ja: "順序通り進める開発。" },
    { id: 35, cat: "技術管理", zh: "敏捷開發", ja: "アジャイル", yomi: "あじゃいる", eng: "Agile", desc_zh: "短週期反覆開發。", desc_ja: "短期間の反復開発。" },
    { id: 106, cat: "技術管理", zh: "物件導向", ja: "オブジェクト指向", yomi: "おぶじぇくと", eng: "Object-Oriented", desc_zh: "以物件為中心開發。", desc_ja: "モノ中心の開発。" },
    { id: 36, cat: "技術管理", zh: "WBS", ja: "WBS", yomi: "だぶりゅーびーえす", eng: "WBS", desc_zh: "工作分解結構。", desc_ja: "作業分解図。" },
    { id: 37, cat: "技術管理", zh: "關鍵路徑", ja: "クリティカルパス", yomi: "くりてぃかるぱす", eng: "Critical Path", desc_zh: "最長路徑，決定工期。", desc_ja: "最長経路。" },
    { id: 38, cat: "技術管理", zh: "EVM", ja: "EVM", yomi: "いーぶいえむ", eng: "EVM", desc_zh: "用金額管理進度。", desc_ja: "金額で進捗管理。" },
    { id: 126, cat: "技術管理", zh: "PMBOK", ja: "PMBOK", yomi: "ぴんぼっく", eng: "PMBOK", desc_zh: "專案管理知識體系。", desc_ja: "PMの知識体系。" },
    { id: 121, cat: "技術管理", zh: "ITIL", ja: "ITIL", yomi: "あいてぃる", eng: "ITIL", desc_zh: "IT服務管理最佳實務。", desc_ja: "ITサービス管理事例。" },
    { id: 123, cat: "技術管理", zh: "事件管理", ja: "インシデント管理", yomi: "いんしでんと", eng: "Incident Mgmt", desc_zh: "盡快恢復服務。", desc_ja: "迅速な復旧。" },
    { id: 124, cat: "技術管理", zh: "問題管理", ja: "問題管理", yomi: "もんだいかんり", eng: "Problem Mgmt", desc_zh: "查明根本原因。", desc_ja: "根本原因の究明。" },
    // --- 新增 231-250 (資料庫/策略/管理) ---
    { id: 231, cat: "電腦系統", zh: "ER圖", ja: "E-R図", yomi: "いーあーるず", eng: "E-R Diagram", desc_zh: "描述實體 (Entity) 與關係 (Relationship) 的圖。", desc_ja: "実体と関係を表す図。" },
    { id: 232, cat: "電腦系統", zh: "NoSQL", ja: "NoSQL", yomi: "のーえすきゅーえる", eng: "NoSQL", desc_zh: "非關聯式資料庫的總稱，適合大數據。", desc_ja: "RDB以外のDB総称。ビッグデータ向き。" },
    { id: 233, cat: "電腦系統", zh: "資料倉儲", ja: "データウェアハウス", yomi: "でーたうぇあはうす", eng: "Data Warehouse", desc_zh: "整合多個來源的歷史資料，用於分析。", desc_ja: "分析用に時系列データを統合したもの。" },
    { id: 234, cat: "電腦系統", zh: "資料探勘", ja: "データマイニング", yomi: "でーたみにんぐ", eng: "Data Mining", desc_zh: "從大量資料中挖掘未知規則的技術。", desc_ja: "大量データから規則性を発掘する技術。" },
    { id: 235, cat: "技術管理", zh: "ABC分析", ja: "ABC分析", yomi: "えーびーしーぶんせき", eng: "ABC Analysis", desc_zh: "根據重要性將項目分為 A、B、C 三類。", desc_ja: "重要度で3ランクに分ける分析手法。" },
    { id: 236, cat: "技術管理", zh: "帕累托圖", ja: "パレート図", yomi: "ぱれーとず", eng: "Pareto Chart", desc_zh: "結合長條圖與累積曲線，用於找出主要問題。", desc_ja: "棒グラフと折れ線で重要項目を特定する。" },
    { id: 237, cat: "技術管理", zh: "散布圖", ja: "散布図", yomi: "さんぷず", eng: "Scatter Plot", desc_zh: "用點表示兩個變數間的關係 (相關性)。", desc_ja: "2変数の相関関係を見るグラフ。" },
    { id: 238, cat: "技術管理", zh: "損益表", ja: "損益計算書", yomi: "そんえきけいさんしょ", eng: "P/L (Profit and Loss)", desc_zh: "顯示企業一段時間內的盈利狀況。", desc_ja: "企業の経営成績(利益)を表す表。" },
    { id: 239, cat: "技術管理", zh: "資產負債表", ja: "貸借対照表", yomi: "たいしゃくたいしょうひょう", eng: "Balance Sheet (B/S)", desc_zh: "顯示企業在特定時間點的財務狀況 (資產/負債)。", desc_ja: "企業の財政状態(資産・負債)を表す表。" },
    { id: 240, cat: "技術管理", zh: "ROI", ja: "ROI", yomi: "あーるおーあい", eng: "Return On Investment", desc_zh: "投資報酬率，衡量投資獲利的指標。", desc_ja: "投資対効果。投資に対する利益率。" },
    { id: 241, cat: "技術管理", zh: "TCO", ja: "TCO", yomi: "てぃーしーおー", eng: "Total Cost of Ownership", desc_zh: "總體擁有成本，包含採購、維護、管理等。", desc_ja: "導入から廃棄までの総コスト。" },
    { id: 242, cat: "技術管理", zh: "損益平衡點", ja: "損益分岐点", yomi: "そんえきぶんきてん", eng: "Break-even Point", desc_zh: "收入與成本相等，不賺不賠的銷售額。", desc_ja: "利益がゼロになる売上高。" },
    { id: 243, cat: "技術管理", zh: "核心競爭力", ja: "コアコンピタンス", yomi: "こあこんぴたんす", eng: "Core Competence", desc_zh: "企業獨有的、他社難以模仿的強項。", desc_ja: "他社が真似できない核となる強み。" },
    { id: 244, cat: "技術管理", zh: "藍海策略", ja: "ブルーオーシャン", yomi: "ぶるーおーしゃん", eng: "Blue Ocean Strategy", desc_zh: "開創無競爭的新市場空間。", desc_ja: "競争のない未開拓市場を創る戦略。" },
    { id: 245, cat: "技術管理", zh: "長尾效應", ja: "ロングテール", yomi: "ろんぐてーる", eng: "Long Tail", desc_zh: "冷門商品總銷售額超過熱門商品的現象。", desc_ja: "死に筋商品の合計が売上の多くを占める。" },
    { id: 246, cat: "技術管理", zh: "腦力激盪", ja: "ブレーンストーミング", yomi: "ぶれーんすとーみんぐ", eng: "Brainstorming", desc_zh: "多人自由提出想法，禁止批評的討論法。", desc_ja: "批判禁止で自由にアイデアを出し合う。" },
    { id: 247, cat: "技術管理", zh: "KJ法", ja: "KJ法", yomi: "けーじぇいほう", eng: "KJ Method", desc_zh: "將點子寫在卡片上並分類整理的發想法。", desc_ja: "カードを使ってアイデアを整理する手法。" },
    { id: 248, cat: "技術管理", zh: "甘特圖", ja: "ガントチャート", yomi: "がんとちゃーと", eng: "Gantt Chart", desc_zh: "用條狀圖顯示專案進度的圖表。", desc_ja: "日程と進捗を横棒で表した図。" },
    { id: 249, cat: "技術管理", zh: "魚骨圖", ja: "特性要因図", yomi: "とくせいよういんず", eng: "Fishbone Diagram", desc_zh: "分析問題原因與結果關係的圖 (石川圖)。", desc_ja: "原因と結果の関係を整理する図。" },
    { id: 250, cat: "技術管理", zh: "雷達圖", ja: "レーダーチャート", yomi: "れーだーちゃーと", eng: "Radar Chart", desc_zh: "顯示多個項目平衡狀態的放射狀圖表。", desc_ja: "複数項目のバランスを見る放射状の図。" }
];