const questionData = [ 
    // --- 1. 基礎理論 (Basic Theory) ---
    { id: 1, cat: "基礎理論", zh: "位元", ja: "ビット", yomi: "びっと", eng: "Bit", desc_zh: "最小的資訊單位，只能表示 0 或 1。", desc_ja: "情報の最小単位。0 または 1 のいずれかを表します。" },
    { id: 2, cat: "基礎理論", zh: "位元組", ja: "バイト", yomi: "ばいと", eng: "Byte", desc_zh: "由 8 個位元組成，通常用來表示一個字元。", desc_ja: "8ビットから構成され、通常、1文字を表す単位です。" },
    { id: 3, cat: "基礎理論", zh: "二進位", ja: "2進数", yomi: "にしんすう", eng: "Binary Number", desc_zh: "僅使用 0 和 1 來表示數值的系統。", desc_ja: "0 と 1 のみを用いて数を表現する方法。" },
    { id: 4, cat: "基礎理論", zh: "二補數", ja: "2の補数", yomi: "にのほすう", eng: "Two's Complement", desc_zh: "在電腦中表示負數的方法。", desc_ja: "コンピュータで負の数を表現する方法。" },
    { id: 5, cat: "基礎理論", zh: "浮點數", ja: "浮動小数点", yomi: "ふどうしょうすうてん", eng: "Floating Point", desc_zh: "用於表示實數，由符號、指數、尾數組成。", desc_ja: "実数を表現する方式。符号、指数、仮数からなる。" },
    { id: 6, cat: "基礎理論", zh: "捨位誤差", ja: "丸め誤差", yomi: "まるめごさ", eng: "Rounding Error", desc_zh: "因位數有限，四雪五入或無條件捨去導致的計算誤差。", desc_ja: "桁数制限により、四捨五入や切り捨てで生じる計算誤差。" },
    { id: 7, cat: "基礎理論", zh: "AND 閘", ja: "AND ゲート", yomi: "あんどげーと", eng: "AND Gate", desc_zh: "邏輯乘。所有輸入為 1 時，輸出才為 1。", desc_ja: "論理積。全ての入力が 1 の時のみ、出力が 1 となる。" },
    { id: 8, cat: "基礎理論", zh: "OR 閘", ja: "OR ゲート", yomi: "おあげーと", eng: "OR Gate", desc_zh: "邏輯和。任一輸入為 1 時，輸出即為 1。", desc_ja: "論理和。いずれかの入力が 1 の時、出力が 1 となる。" },
    { id: 9, cat: "基礎理論", zh: "XOR 閘", ja: "排他的論理和", yomi: "はいたてきろんりわ", eng: "Exclusive OR (XOR)", desc_zh: "當兩個輸入不同時，輸出為 1。", desc_ja: "2つの入力が異なるときのみ、出力が 1 となる。" },
    { id: 10, cat: "基礎理論", zh: "資訊量", ja: "情報量", yomi: "じょうほうりょう", eng: "Information Amount", desc_zh: "事件發生機率越低，資訊量越大。", desc_ja: "事象の発生確率が低いほど、情報量は大きくなる。" },
    { id: 51, cat: "基礎理論", zh: "堆疊", ja: "スタック", yomi: "すたっく", eng: "Stack", desc_zh: "後進先出 (LIFO) 的資料結構。", desc_ja: "後入れ先出し (LIFO) のデータ構造。" },
    { id: 52, cat: "基礎理論", zh: "佇列", ja: "キュー", yomi: "きゅー", eng: "Queue", desc_zh: "先進先出 (FIFO) 的資料結構。", desc_ja: "先入れ先出し (FIFO) のデータ構造。" },
    { id: 53, cat: "基礎理論", zh: "陣列", ja: "配列", yomi: "はいれつ", eng: "Array", desc_zh: "相同類型的資料連續排列的結構。", desc_ja: "同じ型のデータを連続的に並べた構造。" },
    { id: 54, cat: "基礎理論", zh: "連結串列", ja: "連結リスト", yomi: "れんけつりすと", eng: "Linked List", desc_zh: "資料包含指向下一個資料位址的結構。", desc_ja: "データが次のデータの場所を指し示す構造。" },
    { id: 55, cat: "基礎理論", zh: "二元樹", ja: "二分木", yomi: "にぶんぎ", eng: "Binary Tree", desc_zh: "每個節點最多有兩個子節點的樹狀結構。", desc_ja: "各ノードが最大2つの子を持つ木構造。" },
    { id: 56, cat: "基礎理論", zh: "線性搜尋", ja: "線形探索", yomi: "せんけいたんさく", eng: "Linear Search", desc_zh: "從頭開始依序尋找資料的方法。", desc_ja: "先頭から順にデータを探す方法。" },
    { id: 57, cat: "基礎理論", zh: "二分搜尋", ja: "二分探索", yomi: "にぶんたんさく", eng: "Binary Search", desc_zh: "在已排序的資料中，反覆將範圍減半來搜尋。", desc_ja: "整列済みデータの中央を見て、範囲を半分に絞る探索法。" },
    { id: 58, cat: "基礎理論", zh: "雜湊法", ja: "ハッシュ法", yomi: "はっしゅほう", eng: "Hashing", desc_zh: "利用函數計算儲存位置，實現快速存取。", desc_ja: "関数で格納場所を計算し、高速アクセスを実現する。" },
    { id: 59, cat: "基礎理論", zh: "氣泡排序", ja: "バブルソート", yomi: "ばぶるそーと", eng: "Bubble Sort", desc_zh: "重複交換相鄰元素以進行排序。", desc_ja: "隣り合う要素を交換しながら整列する。" },
    { id: 60, cat: "基礎理論", zh: "快速排序", ja: "クイックソート", yomi: "くいっくそーと", eng: "Quick Sort", desc_zh: "選定基準值分割資料的高速排序法。", desc_ja: "基準値を決めてデータを分割する高速な整列法。" },
    { id: 151, cat: "基礎理論", zh: "逆波蘭表示法", ja: "逆ポーランド記法", yomi: "ぎゃくぽーらんどきほう", eng: "RPN", desc_zh: "將運算子寫在運算元後面的表示法。", desc_ja: "演算子を被演算子の後ろに記述する方法。" },
    { id: 152, cat: "基礎理論", zh: "遞迴", ja: "再帰", yomi: "さいき", eng: "Recursive", desc_zh: "函數在執行過程中呼叫自身的技巧。", desc_ja: "関数が自分自身を呼び出すこと。" },
    { id: 153, cat: "基礎理論", zh: "演算法複雜度", ja: "計算量", yomi: "けいさんりょう", eng: "Computational Complexity", desc_zh: "衡量演算法執行時間或空間的指標 (O(n))。", desc_ja: "アルゴリズムの実行時間やメモリ使用量の尺度。" },
    { id: 154, cat: "基礎理論", zh: "有限狀態機", ja: "オートマトン", yomi: "おーとまとん", eng: "Automaton", desc_zh: "根據輸入在不同狀態間轉換的模型。", desc_ja: "入力に応じて状態が遷移するモデル。" },
    { id: 155, cat: "基礎理論", zh: "真值表", ja: "真理値表", yomi: "しんりちひょう", eng: "Truth Table", desc_zh: "列出邏輯電路所有可能輸入與輸出的表格。", desc_ja: "論理回路の全入力と出力の組み合わせを表にしたもの。" },
    { id: 156, cat: "基礎理論", zh: "NAND 閘", ja: "NAND ゲート", yomi: "なんどげーと", eng: "NAND Gate", desc_zh: "只有當所有輸入為 1 時，輸出才為 0。", desc_ja: "入力が全て1の時だけ0を出力する。" },
    { id: 157, cat: "基礎理論", zh: "堆積", ja: "ヒープ", yomi: "ひーぷ", eng: "Heap", desc_zh: "一種特殊的樹狀結構，用於優先權佇列。", desc_ja: "優先度付きキューなどに使われる木構造。" },
    { id: 158, cat: "基礎理論", zh: "雜湊碰撞", ja: "シノニム", yomi: "しのにむ", eng: "Synonym", desc_zh: "雜湊法中，不同資料計算出相同雜湊值的現象。", desc_ja: "異なるデータから同じハッシュ値が出ること。" },
    { id: 159, cat: "基礎理論", zh: "根目錄", ja: "ルートディレクトリ", yomi: "るーとでぃれくとり", eng: "Root Directory", desc_zh: "檔案系統階層結構的最頂層。", desc_ja: "ファイル階層構造の最上位。" },
    { id: 160, cat: "基礎理論", zh: "絕對路徑", ja: "絶対パス", yomi: "ぜったいぱす", eng: "Absolute Path", desc_zh: "從根目錄開始完整描述檔案位置的路徑。", desc_ja: "ルートからファイル位置を完全に記述するパス。" },
    { id: 313, cat: "基礎理論", zh: "ls", ja: "ls", yomi: "えるえす", eng: "list", desc_zh: "Linux 指令：列出目錄下的檔案。", desc_ja: "Linuxコマンド：ファイル一覧を表示。" },
    { id: 314, cat: "基礎理論", zh: "cd", ja: "cd", yomi: "しーでぃー", eng: "change directory", desc_zh: "Linux 指令：切換當前目錄。", desc_ja: "Linuxコマンド：ディレクトリを移動。" },
    { id: 315, cat: "基礎理論", zh: "cp", ja: "cp", yomi: "しーぴー", eng: "copy", desc_zh: "Linux 指令：複製檔案或目錄。", desc_ja: "Linuxコマンド：ファイルをコピーする。" },
    { id: 316, cat: "基礎理論", zh: "mv", ja: "mv", yomi: "えむぶい", eng: "move", desc_zh: "Linux 指令：移動或重新命名檔案。", desc_ja: "Linuxコマンド：ファイルを移動・改名。" },
    { id: 317, cat: "基礎理論", zh: "rm", ja: "rm", yomi: "あーるえむ", eng: "remove", desc_zh: "Linux 指令：刪除檔案。", desc_ja: "Linuxコマンド：ファイルを削除する。" },
    { id: 318, cat: "基礎理論", zh: "pwd", ja: "pwd", yomi: "ぴーだぶりゅーでぃー", eng: "print working directory", desc_zh: "Linux 指令：顯示目前所在路徑。", desc_ja: "Linuxコマンド：現在のパスを表示。" },
    { id: 319, cat: "基礎理論", zh: "chmod", ja: "chmod", yomi: "ちぇんじもーど", eng: "change mode", desc_zh: "Linux 指令：變更檔案權限。", desc_ja: "Linuxコマンド：ファイル権限を変更。" },
    { id: 320, cat: "基礎理論", zh: "grep", ja: "grep", yomi: "ぐれっぷ", eng: "global regular expression print", desc_zh: "Linux 指令：搜尋檔案中的字串。", desc_ja: "Linuxコマンド：文字列を検索する。" },

    // --- 2. 電腦系統：硬體 (Hardware) ---
    { id: 11, cat: "電腦系統", zh: "馮·諾伊曼架構", ja: "ノイマン型", yomi: "のいまんがた", eng: "Von Neumann", desc_zh: "程式內建方式，指令和資料都存在記憶體中。", desc_ja: "命令とデータがメモリに格納される方式。" },
    { id: 12, cat: "電腦系統", zh: "CPU", ja: "中央処理装置", yomi: "ちゅうおうしょりそうち", eng: "CPU", desc_zh: "負責執行指令與運算。", desc_ja: "命令の実行と演算を行う。" },
    { id: 13, cat: "電腦系統", zh: "快取記憶體", ja: "キャッシュメモリ", yomi: "きゃっしゅめもり", eng: "Cache", desc_zh: "位於 CPU 與 RAM 之間，加速資料存取。", desc_ja: "CPUとRAMの間にあり高速化する。" },
    { id: 14, cat: "電腦系統", zh: "RAM", ja: "RAM", yomi: "らむ", eng: "RAM", desc_zh: "揮發性記憶體，電源關閉後資料消失。", desc_ja: "電源を切るとデータが消える揮発性メモリ。" },
    { id: 15, cat: "電腦系統", zh: "ROM", ja: "ROM", yomi: "ろむ", eng: "ROM", desc_zh: "非揮發性記憶體，儲存 BIOS 等。", desc_ja: "不揮発性メモリ。BIOS等を保存。" },
    { id: 16, cat: "電腦系統", zh: "虛擬記憶體", ja: "仮想記憶", yomi: "かそうきおく", eng: "Virtual Memory", desc_zh: "將硬碟當作記憶體使用。", desc_ja: "HDDをメモリの一部として扱う技術。" },
    { id: 17, cat: "電腦系統", zh: "RAID 0", ja: "ストライピング", yomi: "すとらいぴんぐ", eng: "Striping", desc_zh: "資料分散寫入，速度快但無容錯。", desc_ja: "分散書き込み。高速だが耐障害性なし。" },
    { id: 18, cat: "電腦系統", zh: "RAID 1", ja: "ミラーリング", yomi: "みらーりんぐ", eng: "Mirroring", desc_zh: "資料完整複製到兩顆硬碟。", desc_ja: "複製書き込み。信頼性が高い。" },
    { id: 19, cat: "電腦系統", zh: "RAID 5", ja: "RAID 5", yomi: "れーどふぁいぶ", eng: "RAID 5", desc_zh: "分散寫入資料與同位檢查碼。", desc_ja: "データとパリティを分散書き込み。" },
    { id: 61, cat: "電腦系統", zh: "GPU", ja: "GPU", yomi: "じーぴーゆー", eng: "GPU", desc_zh: "圖形處理器，擅長並行運算 (如 AI、圖像)。", desc_ja: "画像処理装置。並列処理（AI、画像）が得意。" },
    { id: 62, cat: "電腦系統", zh: "SSD", ja: "SSD", yomi: "えすえすでぃー", eng: "SSD", desc_zh: "使用快閃記憶體的儲存裝置，速度比 HDD 快。", desc_ja: "フラッシュメモリを使った記憶装置。HDDより高速。" },
    { id: 63, cat: "電腦系統", zh: "RFID", ja: "RFID", yomi: "あーるえふあいでぃー", eng: "RFID", desc_zh: "使用無線電波進行非接觸式資料讀寫的技術 (如 IC 卡)。", desc_ja: "電波を用いた非接触データ読み書き技術 (ICカード等)。" },
    { id: 64, cat: "電腦系統", zh: "NFC", ja: "NFC", yomi: "えぬえふしー", eng: "NFC", desc_zh: "近距離無線通訊技術 (如手機支付)。", desc_ja: "近距離無線通信技術 (スマホ決済など)。" },
    { id: 65, cat: "電腦系統", zh: "OCR", ja: "OCR", yomi: "おーしーあーる", eng: "OCR", desc_zh: "光學字元辨識，將圖片中的文字轉換為文字資料。", desc_ja: "画像内の文字をテキストデータに変換する技術。" },
    { id: 161, cat: "電腦系統", zh: "暫存器", ja: "レジスタ", yomi: "れじすた", eng: "Register", desc_zh: "CPU 內部速度最快的超小型記憶體。", desc_ja: "CPU内部にある超高速な記憶領域。" },
    { id: 162, cat: "電腦系統", zh: "時脈頻率", ja: "クロック周波数", yomi: "くろっくしゅうはすう", eng: "Clock Frequency", desc_zh: "CPU 每秒執行的週期數 (Hz)。", desc_ja: "CPUの処理速度の指標。Hzで表す。" },
    { id: 163, cat: "電腦系統", zh: "匯流排", ja: "バス", yomi: "ばす", eng: "Bus", desc_zh: "電腦內部傳輸資料的通道。", desc_ja: "コンピュータ内部のデータ伝送路。" },
    { id: 164, cat: "電腦系統", zh: "A/D轉換器", ja: "A/D変換器", yomi: "えーでぃーへんかんき", eng: "A/D Converter", desc_zh: "將類比訊號 (如聲音) 轉為數位訊號。", desc_ja: "アナログ信号をデジタル信号に変換する。" },
    { id: 165, cat: "電腦系統", zh: "致動器", ja: "アクチュエータ", yomi: "あくちゅえーた", eng: "Actuator", desc_zh: "將電訊號轉換為物理動作的裝置 (如馬達)。", desc_ja: "電気信号を物理的な動きに変える装置。" },
    { id: 166, cat: "電腦系統", zh: "感測器", ja: "センサ", yomi: "せんさ", eng: "Sensor", desc_zh: "檢測物理量 (光、溫度) 並轉為電子訊號。", desc_ja: "物理量(光・温度)を検知し信号にする。" },
    { id: 167, cat: "電腦系統", zh: "嵌入式系統", ja: "組込みシステム", yomi: "くみこみしすてむ", eng: "Embedded System", desc_zh: "內建於機器中，執行特定功能的電腦。", desc_ja: "機器に内蔵され特定機能を実現するPC。" },
    { id: 168, cat: "電腦系統", zh: "隨插即用", ja: "プラグアンドプレイ", yomi: "ぷらぐあんどぷれい", eng: "Plug and Play", desc_zh: "連接裝置後自動設定即可使用。", desc_ja: "機器接続時に自動設定ですぐ使える機能。" },
    { id: 169, cat: "電腦系統", zh: "HDMI", ja: "HDMI", yomi: "えいちでぃーえむあい", eng: "HDMI", desc_zh: "傳輸高品質影像與聲音的數位介面。", desc_ja: "映像と音声を伝送するデジタル端子。" },
    { id: 170, cat: "電腦系統", zh: "USB", ja: "USB", yomi: "ゆーえすびー", eng: "USB", desc_zh: "通用的序列匯流排介面，支援熱插拔。", desc_ja: "汎用的なシリアルバス規格。" },
    { id: 171, cat: "電腦系統", zh: "藍牙", ja: "Bluetooth", yomi: "ぶるーとぅーす", eng: "Bluetooth", desc_zh: "短距離低功耗的無線通訊技術。", desc_ja: "近距離・低消費電力の無線通信技術。" },
    { id: 172, cat: "電腦系統", zh: "SRAM", ja: "SRAM", yomi: "えすらむ", eng: "SRAM", desc_zh: "速度快不需要更新動作，常用於快取。", desc_ja: "高速でリフレッシュ不要。キャッシュに利用。" },
    { id: 173, cat: "電腦系統", zh: "DRAM", ja: "DRAM", yomi: "でぃーらむ", eng: "DRAM", desc_zh: "需定期更新動作，容量大，用於主記憶體。", desc_ja: "リフレッシュ必要。主記憶に利用。" },
    { id: 174, cat: "電腦系統", zh: "快閃記憶體", ja: "フラッシュメモリ", yomi: "ふらっしゅめもり", eng: "Flash Memory", desc_zh: "可電子抹除的非揮發性記憶體 (如 USB)。", desc_ja: "電気的に消去可能な不揮発性メモリ。" },
    { id: 175, cat: "電腦系統", zh: "多核心", ja: "マルチコア", yomi: "まるちこあ", eng: "Multi-core", desc_zh: "一個 CPU 封裝中包含多個處理核心。", desc_ja: "1つのCPUに複数の処理コアを持つこと。" },
    { id: 321, cat: "電腦系統", zh: "RISC", ja: "RISC", yomi: "りすく", eng: "Reduced Instruction Set Computer", desc_zh: "精簡指令集，指令簡單執行快 (如 ARM)。", desc_ja: "命令を単純化し高速化したCPU (スマホ等)。" },
    { id: 322, cat: "電腦系統", zh: "CISC", ja: "CISC", yomi: "しすく", eng: "Complex Instruction Set Computer", desc_zh: "複雜指令集，單一指令功能強 (如 Intel x86)。", desc_ja: "複雑な命令を持つCPU (PC等)。" },
    { id: 323, cat: "電腦系統", zh: "MIPS", ja: "MIPS", yomi: "みっぷす", eng: "Million Instructions Per Second", desc_zh: "衡量 CPU 速度的指標，每秒百萬指令數。", desc_ja: "CPU性能指標。1秒間の命令実行数(百万)。" },
    { id: 324, cat: "電腦系統", zh: "FLOPS", ja: "FLOPS", yomi: "ふろっぷす", eng: "Floating-point Operations Per Second", desc_zh: "每秒浮點運算次數，衡量超級電腦性能。", desc_ja: "スパコン等の性能指標。浮動小数点演算数。" },
    { id: 325, cat: "電腦系統", zh: "VLIW", ja: "VLIW", yomi: "ぶいえるあいだぶりゅー", eng: "Very Long Instruction Word", desc_zh: "超長指令字，同時執行多個運算。", desc_ja: "複数の命令をまとめて実行する方式。" },
    { id: 326, cat: "電腦系統", zh: "SoC", ja: "SoC", yomi: "えすおーしー", eng: "System on a Chip", desc_zh: "將系統所有功能整合在單一晶片上。", desc_ja: "主要機能を1つのチップに集約したもの。" },
    { id: 327, cat: "電腦系統", zh: "BIOS", ja: "BIOS", yomi: "ばいおす", eng: "Basic Input Output System", desc_zh: "電腦開機最先執行的韌體。", desc_ja: "PC起動時にハードを制御するプログラム。" },
    { id: 328, cat: "電腦系統", zh: "UEFI", ja: "UEFI", yomi: "ゆーいーえふあい", eng: "Unified Extensible Firmware Interface", desc_zh: "BIOS 的後繼者，支援大容量硬碟與快速啟動。", desc_ja: "BIOSの後継。大容量HDD対応・高速起動。" },
    { id: 329, cat: "電腦系統", zh: "DisplayPort", ja: "DisplayPort", yomi: "でぃすぷれいぽーと", eng: "DisplayPort", desc_zh: "電腦連接螢幕的數位影音介面。", desc_ja: "PCとモニタを接続するデジタル規格。" },
    { id: 330, cat: "電腦系統", zh: "Thunderbolt", ja: "Thunderbolt", yomi: "さんだーぼると", eng: "Thunderbolt", desc_zh: "Intel 開發的高速傳輸介面。", desc_ja: "Intel開発の高速データ伝送技術。" },

    // --- 3. 電腦系統：OS 與軟體 ---
    { id: 66, cat: "電腦系統", zh: "OSS", ja: "OSS", yomi: "おーえすえす", eng: "OSS", desc_zh: "開放原始碼軟體，原始碼公開且可自由修改。", desc_ja: "ソースコードが公開され、自由に修正可能なソフト。" },
    { id: 67, cat: "電腦系統", zh: "BIOS", ja: "BIOS", yomi: "ばいおす", eng: "BIOS", desc_zh: "電腦啟動時最先執行的程式，控制硬體。", desc_ja: "起動時に最初に実行され、ハードウェアを制御する。" },
    { id: 68, cat: "電腦系統", zh: "中介軟體", ja: "ミドルウェア", yomi: "みどるうぇあ", eng: "Middleware", desc_zh: "位於 OS 和應用程式之間，提供共通功能的軟體。", desc_ja: "OSとアプリの間にあり、共通機能を提供するソフト。" },
    { id: 69, cat: "電腦系統", zh: "API", ja: "API", yomi: "えーぴーあい", eng: "API", desc_zh: "讓軟體之間交換功能或資料的介面。", desc_ja: "ソフト同士が機能やデータをやり取りする窓口。" },
    { id: 70, cat: "電腦系統", zh: "批次處理", ja: "バッチ処理", yomi: "ばっちしょり", eng: "Batch Processing", desc_zh: "累積一定量的資料後，一次性進行處理。", desc_ja: "データを一定量ためてから一括で処理する方式。" },
    { id: 71, cat: "電腦系統", zh: "即時處理", ja: "リアルタイム処理", yomi: "りあるたいむしょり", eng: "Real-time", desc_zh: "資料產生時立即進行處理。", desc_ja: "データ発生時に即座に処理を行う方式。" },
    { id: 72, cat: "電腦系統", zh: "備份", ja: "バックアップ", yomi: "ばっくあっぷ", eng: "Backup", desc_zh: "複製資料以防遺失。", desc_ja: "データ消失に備えて複製をとること。" },
    { id: 73, cat: "電腦系統", zh: "完整備份", ja: "フルバックアップ", yomi: "ふるばっくあっぷ", eng: "Full Backup", desc_zh: "備份所有資料。", desc_ja: "全てのデータをバックアップする。" },
    { id: 74, cat: "電腦系統", zh: "差異備份", ja: "差分バックアップ", yomi: "さぶんばっくあっぷ", eng: "Differential", desc_zh: "備份自上次「完整備份」以來變更的資料。", desc_ja: "前回の「フルバックアップ」からの変更分を保存。" },
    { id: 75, cat: "電腦系統", zh: "增量備份", ja: "増分バックアップ", yomi: "ぞうぶんばっくあっぷ", eng: "Incremental", desc_zh: "備份自上次「任何備份」以來變更的資料。", desc_ja: "前回の「バックアップ」からの変更分のみ保存。" },
    { id: 176, cat: "電腦系統", zh: "周轉時間", ja: "ターンアラウンドタイム", yomi: "たーんあらうんどたいむ", eng: "Turnaround Time", desc_zh: "從提交工作到輸出結果的總時間。", desc_ja: "処理依頼から結果出力までの全時間。" },
    { id: 177, cat: "電腦系統", zh: "回應時間", ja: "レスポンスタイム", yomi: "れすぽんすたいむ", eng: "Response Time", desc_zh: "從發出指令到系統開始反應的時間。", desc_ja: "指示から反応が始まるまでの時間。" },
    { id: 178, cat: "電腦系統", zh: "吞吐量", ja: "スループット", yomi: "するーぷっと", eng: "Throughput", desc_zh: "單位時間內處理的工作量。", desc_ja: "単位時間あたりの処理能力。" },
    { id: 179, cat: "電腦系統", zh: "多工處理", ja: "マルチタスク", yomi: "まるちたすく", eng: "Multitasking", desc_zh: "同時執行多個程式的技術。", desc_ja: "複数の処理を並行して行う技術。" },
    { id: 180, cat: "電腦系統", zh: "假脫機", ja: "スプーリング", yomi: "すぷーりんぐ", eng: "Spooling", desc_zh: "將資料暫存以緩解慢速裝置的等待。", desc_ja: "データを一時保存し、待ちを減らす。" },
    { id: 181, cat: "電腦系統", zh: "死結", ja: "デッドロック", yomi: "でっどろっく", eng: "Deadlock", desc_zh: "兩個程序互等對方釋放資源，導致停擺。", desc_ja: "処理が互いの資源空きを待ち、停止する状態。" },
    { id: 182, cat: "電腦系統", zh: "記憶體洩漏", ja: "メモリリーク", yomi: "めもりりーく", eng: "Memory Leak", desc_zh: "程式未釋放不再使用的記憶體。", desc_ja: "メモリが解放されず、使用可能領域が減る。" },
    { id: 183, cat: "電腦系統", zh: "碎片化", ja: "フラグメンテーション", yomi: "ふらぐめんてーしょん", eng: "Fragmentation", desc_zh: "記憶體或硬碟空間變得零散，降低效率。", desc_ja: "記憶領域が断片化し、効率が落ちる現象。" },
    { id: 184, cat: "電腦系統", zh: "排程", ja: "スケジューリング", yomi: "すけじゅーりんぐ", eng: "Scheduling", desc_zh: "決定 CPU 分配給哪個程序的機制。", desc_ja: "CPUをどの処理に割り当てるか決めること。" },
    { id: 185, cat: "電腦系統", zh: "輪詢", ja: "ラウンドロビン", yomi: "らうんどろびん", eng: "Round Robin", desc_zh: "依序分配固定時間給每個程序。", desc_ja: "各処理に一定時間を順に割り当てる方式。" },
    { id: 186, cat: "電腦系統", zh: "目錄", ja: "ディレクトリ", yomi: "でぃれくとり", eng: "Directory", desc_zh: "用於分類和管理檔案的資料夾。", desc_ja: "ファイルを整理・管理するフォルダ。" },
    { id: 187, cat: "電腦系統", zh: "壓縮", ja: "圧縮", yomi: "あっしゅく", eng: "Compression", desc_zh: "縮小檔案容量的技術。", desc_ja: "データのサイズを小さくする技術。" },
    { id: 188, cat: "電腦系統", zh: "封存", ja: "アーカイブ", yomi: "あーかいぶ", eng: "Archive", desc_zh: "將多個檔案整合成一個檔案。", desc_ja: "複数ファイルを一つにまとめること。" },
    { id: 189, cat: "電腦系統", zh: "GUI", ja: "GUI", yomi: "じーゆーあい", eng: "GUI", desc_zh: "透過圖形和滑鼠操作的介面。", desc_ja: "画像やマウスで操作する画面。" },
    { id: 190, cat: "電腦系統", zh: "CUI", ja: "CUI", yomi: "しーゆーあい", eng: "CUI", desc_zh: "透過鍵盤輸入文字指令操作的介面。", desc_ja: "文字入力で操作する画面。" },
    { id: 261, cat: "電腦系統", zh: "編譯器", ja: "コンパイラ", yomi: "こんぱいら", eng: "Compiler", desc_zh: "將原始碼一次性轉換為機器語言的程式。", desc_ja: "ソースを一括で機械語に変換するソフト。" },
    { id: 262, cat: "電腦系統", zh: "直譯器", ja: "インタプリタ", yomi: "いんたぷりた", eng: "Interpreter", desc_zh: "逐行翻譯並執行原始碼的程式。", desc_ja: "ソースを逐次翻訳しながら実行するソフト。" },
    { id: 263, cat: "電腦系統", zh: "連結器", ja: "リンカ", yomi: "りんか", eng: "Linker", desc_zh: "將編譯後的多個目的檔結合成執行檔。", desc_ja: "複数ファイルを結合し実行形式にする。" },
    { id: 264, cat: "電腦系統", zh: "載入器", ja: "ローダ", yomi: "ろーだ", eng: "Loader", desc_zh: "將執行檔載入記憶體並執行的程式。", desc_ja: "実行ファイルをメモリに読み込むソフト。" },
    { id: 265, cat: "電腦系統", zh: "垃圾回收", ja: "ガベージコレクション", yomi: "がべーじこれくしょん", eng: "Garbage Collection", desc_zh: "自動釋放不再使用的記憶體空間。", desc_ja: "不要なメモリ領域を自動的に解放する。" },
    { id: 266, cat: "電腦系統", zh: "遞迴呼叫", ja: "リエントラント", yomi: "りえんとらんと", eng: "Reentrant", desc_zh: "可重入，多個程式同時呼叫也不會出錯。", desc_ja: "複数のタスクから同時呼び出し可能な性質。" },
    { id: 267, cat: "電腦系統", zh: "動態連結函式庫", ja: "DLL", yomi: "でぃーえるえる", eng: "Dynamic Link Library", desc_zh: "程式執行時才載入的函式庫。", desc_ja: "実行時に結合されるライブラリ。" },
    { id: 301, cat: "電腦系統", zh: "JPEG", ja: "JPEG", yomi: "じぇいぺぐ", eng: "JPEG", desc_zh: "破壞性壓縮的靜態影像格式，適合照片。", desc_ja: "非可逆圧縮の画像形式。写真向き。" },
    { id: 302, cat: "電腦系統", zh: "PNG", ja: "PNG", yomi: "ぴんぐ", eng: "PNG", desc_zh: "非破壞性壓縮的影像格式，支援透明背景。", desc_ja: "可逆圧縮の画像形式。透過背景に対応。" },
    { id: 303, cat: "電腦系統", zh: "GIF", ja: "GIF", yomi: "じふ", eng: "GIF", desc_zh: "支援動畫的影像格式，色彩限 256 色。", desc_ja: "アニメーション可能な画像形式。256色制限。" },
    { id: 304, cat: "電腦系統", zh: "BMP", ja: "BMP", yomi: "びっとまっぷ", eng: "BMP", desc_zh: "Windows 標準的無壓縮影像格式，檔案較大。", desc_ja: "Windows標準の無圧縮画像形式。サイズ大。" },
    { id: 305, cat: "電腦系統", zh: "SVG", ja: "SVG", yomi: "えすぶいじー", eng: "SVG", desc_zh: "向量圖檔，放大縮小不失真。", desc_ja: "ベクタ形式画像。拡大縮小しても劣化しない。" },
    { id: 306, cat: "電腦系統", zh: "MP3", ja: "MP3", yomi: "えむぴーすりー", eng: "MP3", desc_zh: "廣泛使用的破壞性壓縮音訊格式。", desc_ja: "広く普及している非可逆圧縮音声形式。" },
    { id: 307, cat: "電腦系統", zh: "MP4", ja: "MP4", yomi: "えむぴーふぉー", eng: "MP4", desc_zh: "常用的影音容器格式，包含影像與聲音。", desc_ja: "動画と音声を格納する一般的なコンテナ形式。" },
    { id: 308, cat: "電腦系統", zh: "CSV", ja: "CSV", yomi: "しーえすぶい", eng: "CSV", desc_zh: "以逗號分隔值的純文字檔案，用於試算表。", desc_ja: "カンマ区切りのテキストデータ。表計算で利用。" },
    { id: 309, cat: "電腦系統", zh: "JSON", ja: "JSON", yomi: "じぇいそん", eng: "JSON", desc_zh: "輕量級資料交換格式，易於人閱讀。", desc_ja: "軽量なデータ交換形式。人間にも読みやすい。" },
    { id: 310, cat: "電腦系統", zh: "XML", ja: "XML", yomi: "えっくすえむえる", eng: "XML", desc_zh: "可延伸標記式語言，用於結構化資料。", desc_ja: "文書やデータを記述するマークアップ言語。" },
    { id: 311, cat: "電腦系統", zh: "ZIP", ja: "ZIP", yomi: "じっぷ", eng: "ZIP", desc_zh: "通用的檔案壓縮格式。", desc_ja: "一般的なファイル圧縮形式。" },
    { id: 312, cat: "電腦系統", zh: "PDF", ja: "PDF", yomi: "ぴーでぃーえふ", eng: "PDF", desc_zh: "可攜式文件格式，確保跨平台顯示一致。", desc_ja: "環境に依存せず文書を表示できる形式。" },

    // --- 4. 電腦系統：資料庫 (Database) ---
    { id: 20, cat: "電腦系統", zh: "RDB", ja: "リレーショナルDB", yomi: "りれーしょなるでーたべーす", eng: "Relational Database", desc_zh: "關聯式資料庫，以表格形式管理資料。", desc_ja: "データを表形式で管理するデータベース。" },
    { id: 21, cat: "電腦系統", zh: "SQL", ja: "SQL", yomi: "えすきゅーえる", eng: "SQL", desc_zh: "操作資料庫的標準語言。", desc_ja: "データベースを操作する標準言語。" },
    { id: 22, cat: "電腦系統", zh: "正規化", ja: "正規化", yomi: "せいきか", eng: "Normalization", desc_zh: "消除資料重複與異常的過程。", desc_ja: "データの重複や矛盾を排除するプロセス。" },
    { id: 23, cat: "電腦系統", zh: "ACID特性", ja: "ACID特性", yomi: "あしっどとくせい", eng: "ACID Properties", desc_zh: "確保交易可靠性的四個特性(原子/一致/隔離/持久)。", desc_ja: "トランザクションの信頼性を保証する4つの性質。" },
    { id: 24, cat: "電腦系統", zh: "交易", ja: "トランザクション", yomi: "とらんざくしょん", eng: "Transaction", desc_zh: "一組不可分割的資料庫操作單元。", desc_ja: "分割できない一連のデータベース処理単位。" },
    { id: 76, cat: "電腦系統", zh: "主鍵", ja: "主キー", yomi: "しゅきー", eng: "Primary Key", desc_zh: "唯一識別表格中每一筆記錄的欄位。", desc_ja: "行を一意に識別するための列。" },
    { id: 77, cat: "電腦系統", zh: "外鍵", ja: "外部キー", yomi: "がいぶきー", eng: "Foreign Key", desc_zh: "用來關聯其他表格的欄位。", desc_ja: "他の表を参照するための列。" },
    { id: 78, cat: "電腦系統", zh: "SELECT", ja: "SELECT", yomi: "せれくと", eng: "SELECT", desc_zh: "SQL指令：查詢資料。", desc_ja: "SQL命令：データを検索する。" },
    { id: 79, cat: "電腦系統", zh: "INSERT", ja: "INSERT", yomi: "いんさーと", eng: "INSERT", desc_zh: "SQL指令：新增資料。", desc_ja: "SQL命令：データを追加する。" },
    { id: 80, cat: "電腦系統", zh: "UPDATE", ja: "UPDATE", yomi: "あっぷでーと", eng: "UPDATE", desc_zh: "SQL指令：更新資料。", desc_ja: "SQL命令：データを更新する。" },
    { id: 231, cat: "電腦系統", zh: "ER圖", ja: "E-R図", yomi: "いーあーるず", eng: "ER Diagram", desc_zh: "描述實體與關係的圖。", desc_ja: "実体と関係を表す図。" },
    { id: 232, cat: "電腦系統", zh: "NoSQL", ja: "NoSQL", yomi: "のーえすきゅーえる", eng: "NoSQL", desc_zh: "非關聯式資料庫的總稱，適合大數據。", desc_ja: "RDB以外のDB総称。ビッグデータ向き。" },
    { id: 233, cat: "電腦系統", zh: "資料倉儲", ja: "データウェアハウス", yomi: "でーたうぇあはうす", eng: "Data Warehouse", desc_zh: "整合多個來源的歷史資料，用於分析。", desc_ja: "分析用に時系列データを統合したもの。" },
    { id: 234, cat: "電腦系統", zh: "資料探勘", ja: "データマイニング", yomi: "でーたみにんぐ", eng: "Data Mining", desc_zh: "從大量資料中挖掘未知規則的技術。", desc_ja: "大量データから規則性を発掘する技術。" },

    // --- 5. 電腦系統：網路 (Network) ---
    { id: 25, cat: "電腦系統", zh: "OSI模型", ja: "OSI参照モデル", yomi: "おーえすあい", eng: "OSI Model", desc_zh: "通訊7層模型。", desc_ja: "通信の7階層モデル。" },
    { id: 26, cat: "電腦系統", zh: "TCP/IP", ja: "TCP/IP", yomi: "てぃーしーぴー", eng: "TCP/IP", desc_zh: "網際網路標準協定。", desc_ja: "ネットの標準プロトコル。" },
    { id: 27, cat: "電腦系統", zh: "IP地址", ja: "IPアドレス", yomi: "あいぴーあどれす", eng: "IP Address", desc_zh: "網路邏輯位址。", desc_ja: "ネット上の住所。" },
    { id: 28, cat: "電腦系統", zh: "MAC地址", ja: "MACアドレス", yomi: "まっくあどれす", eng: "MAC Address", desc_zh: "硬體實體位址。", desc_ja: "機器の物理アドレス。" },
    { id: 29, cat: "電腦系統", zh: "DHCP", ja: "DHCP", yomi: "でぃーえいちしーぴー", eng: "DHCP", desc_zh: "自動分配 IP。", desc_ja: "IP自動割り当て。" },
    { id: 30, cat: "電腦系統", zh: "NAT", ja: "NAT", yomi: "なっと", eng: "NAT", desc_zh: "轉換私有與公共 IP。", desc_ja: "IPアドレス変換。" },
    { id: 81, cat: "電腦系統", zh: "DNS", ja: "DNS", yomi: "でぃーえぬえす", eng: "DNS", desc_zh: "網域名稱轉 IP。", desc_ja: "ドメイン名をIPに変換。" },
    { id: 82, cat: "電腦系統", zh: "HTTP", ja: "HTTP", yomi: "えいちてぃーてぃーぴー", eng: "HTTP", desc_zh: "網頁傳輸協定。", desc_ja: "Web通信プロトコル。" },
    { id: 83, cat: "電腦系統", zh: "SMTP", ja: "SMTP", yomi: "えすえむてぃーぴー", eng: "SMTP", desc_zh: "發信協定。", desc_ja: "メール送信プロトコル。" },
    { id: 84, cat: "電腦系統", zh: "POP3", ja: "POP3", yomi: "ぽっぷすりー", eng: "POP3", desc_zh: "收信協定 (下載後刪除)。", desc_ja: "メール受信 (DL後削除)。" },
    { id: 85, cat: "電腦系統", zh: "IMAP", ja: "IMAP", yomi: "あいまっぷ", eng: "IMAP", desc_zh: "收信協定 (在伺服器管理)。", desc_ja: "メール受信 (サーバ管理)。" },
    { id: 86, cat: "電腦系統", zh: "FTP", ja: "FTP", yomi: "えふてぃーぴー", eng: "FTP", desc_zh: "檔案傳輸協定。", desc_ja: "ファイル転送。" },
    { id: 87, cat: "電腦系統", zh: "NTP", ja: "NTP", yomi: "えぬてぃーぴー", eng: "NTP", desc_zh: "時間同步協定。", desc_ja: "時刻同期。" },
    { id: 88, cat: "電腦系統", zh: "ARP", ja: "ARP", yomi: "あーぷ", eng: "ARP", desc_zh: "IP 轉 MAC。", desc_ja: "IPからMACを調査。" },
    { id: 89, cat: "電腦系統", zh: "路由器", ja: "ルータ", yomi: "るーた", eng: "Router", desc_zh: "不同網路間的路徑選擇。", desc_ja: "NW間の経路選択。" },
    { id: 90, cat: "電腦系統", zh: "交換器", ja: "スイッチ", yomi: "すいっち", eng: "Switch", desc_zh: "同網路內的資料轉發。", desc_ja: "NW内のデータ転送。" },
    { id: 191, cat: "電腦系統", zh: "子網路遮罩", ja: "サブネットマスク", yomi: "さぶねっとますく", eng: "Subnet Mask", desc_zh: "用來區分 IP 位址中網路位址與主機位址。", desc_ja: "IPアドレスのNW部とホスト部を分ける。" },
    { id: 192, cat: "電腦系統", zh: "預設閘道", ja: "デフォルトゲートウェイ", yomi: "でふぉるとげーとうぇい", eng: "Default Gateway", desc_zh: "通往外部網路的出口 (路由器)。", desc_ja: "外部NWへの出入り口 (ルータ等)。" },
    { id: 193, cat: "電腦系統", zh: "IPv6", ja: "IPv6", yomi: "あいぴーぶいろく", eng: "IPv6", desc_zh: "128位元的 IP 地址，解決 IPv4 枯竭問題。", desc_ja: "128ビットのIPアドレス。IPv4枯渇対策。" },
    { id: 194, cat: "電腦系統", zh: "連接埠號", ja: "ポート番号", yomi: "ぽーとばんごう", eng: "Port Number", desc_zh: "識別通訊應用程式的編號 (80=Web)。", desc_ja: "アプリを識別する番号 (80=Web等)。" },
    { id: 195, cat: "電腦系統", zh: "HTTPS", ja: "HTTPS", yomi: "えいちてぃーてぃーぴーえす", eng: "HTTPS", desc_zh: "加密的 HTTP 通訊。", desc_ja: "暗号化されたWeb通信。" },
    { id: 196, cat: "電腦系統", zh: "SSH", ja: "SSH", yomi: "えすえすえいち", eng: "SSH", desc_zh: "遠端安全登入並操作電腦的協定。", desc_ja: "遠隔地から安全に操作するプロトコル。" },
    { id: 197, cat: "電腦系統", zh: "代理伺服器", ja: "プロキシ", yomi: "ぷろきし", eng: "Proxy", desc_zh: "代替內部電腦存取網際網路的伺服器。", desc_ja: "代理でネット接続するサーバ。" },
    { id: 198, cat: "電腦系統", zh: "LAN", ja: "LAN", yomi: "らん", eng: "LAN", desc_zh: "區域網路 (如辦公室或家庭內)。", desc_ja: "構内ネットワーク。" },
    { id: 199, cat: "電腦系統", zh: "WAN", ja: "WAN", yomi: "わん", eng: "WAN", desc_zh: "廣域網路 (連接不同地點的網路)。", desc_ja: "広域ネットワーク。" },
    { id: 200, cat: "電腦系統", zh: "Ping", ja: "Ping", yomi: "ぴん", eng: "Ping", desc_zh: "確認網路連線是否通暢的指令。", desc_ja: "接続確認を行うコマンド。" },
    { id: 201, cat: "電腦系統", zh: "封包", ja: "パケット", yomi: "ぱけっと", eng: "Packet", desc_zh: "網路傳輸的資料小塊。", desc_ja: "通信データの小包。" },
    { id: 202, cat: "電腦系統", zh: "VLAN", ja: "VLAN", yomi: "ぶいらん", eng: "VLAN", desc_zh: "在物理網路上邏輯分割出的虛擬網路。", desc_ja: "仮想的に分割されたLAN。" },
    { id: 203, cat: "電腦系統", zh: "ESSID", ja: "ESSID", yomi: "いーえすえすあいでぃー", eng: "ESSID", desc_zh: "無線網路基地台的識別名稱。", desc_ja: "無線LANアクセスポイントの識別名。" },
    { id: 204, cat: "電腦系統", zh: "MIME", ja: "MIME", yomi: "まいむ", eng: "MIME", desc_zh: "讓電子郵件支援文字以外格式的標準。", desc_ja: "メールで画像等を扱うための規格。" },
    { id: 205, cat: "電腦系統", zh: "VoIP", ja: "VoIP", yomi: "ぼいっぷ", eng: "VoIP", desc_zh: "在網路上傳輸語音的技術 (網路電話)。", desc_ja: "ネットで音声を送る技術 (IP電話)。" },
    { id: 206, cat: "電腦系統", zh: "SDN", ja: "SDN", yomi: "えすでぃーえぬ", eng: "SDN", desc_zh: "透過軟體集中控制網路架構。", desc_ja: "ソフトでNW構成を制御する技術。" },
    { id: 207, cat: "電腦系統", zh: "迴路位址", ja: "ループバックアドレス", yomi: "るーぷばっくあどれす", eng: "Loopback", desc_zh: "指向本機自己的 IP (127.0.0.1)。", desc_ja: "自分自身を指すIP (127.0.0.1)。" },
    { id: 208, cat: "電腦系統", zh: "廣播", ja: "ブロードキャスト", yomi: "ぶろーどきゃすと", eng: "Broadcast", desc_zh: "向網路上所有裝置發送資料。", desc_ja: "NW内の全機器にデータを送る。" },
    { id: 209, cat: "電腦系統", zh: "串流", ja: "ストリーミング", yomi: "すとりーみんぐ", eng: "Streaming", desc_zh: "邊下載邊播放影音的技術。", desc_ja: "DLしながら再生する技術。" },
    { id: 210, cat: "電腦系統", zh: "IoT閘道器", ja: "IoTゲートウェイ", yomi: "あいおーてぃーげーとうぇい", eng: "IoT Gateway", desc_zh: "連接感測器與雲端的橋樑設備。", desc_ja: "センサとクラウドを繋ぐ中継機。" },
    { id: 229, cat: "電腦系統", zh: "VPN通道", ja: "トンネリング", yomi: "とんねりんぐ", eng: "Tunneling", desc_zh: "在網路上建立虛擬傳輸通道的技術。", desc_ja: "仮想的な通信路を作る技術。" },
    { id: 230, cat: "電腦系統", zh: "混合雲", ja: "ハイブリッドクラウド", yomi: "はいぶりっどくらうど", eng: "Hybrid Cloud", desc_zh: "結合私有雲與公有雲的架構。", desc_ja: "私有雲と公有雲を組み合わせた形態。" },
    { id: 257, cat: "電腦系統", zh: "叢集", ja: "クラスタ", yomi: "くらすた", eng: "Cluster", desc_zh: "多台電腦連接並像一台機器般運作。", desc_ja: "複数台を接続し1台のように見せる技術。" },
    { id: 258, cat: "電腦系統", zh: "NAS", ja: "NAS", yomi: "なす", eng: "NAS", desc_zh: "連接網路直接使用的檔案儲存裝置。", desc_ja: "ネットに接続して使うファイルサーバ。" },
    { id: 259, cat: "電腦系統", zh: "SAN", ja: "SAN", yomi: "さん", eng: "SAN", desc_zh: "伺服器與儲存裝置之間的高速專用網路。", desc_ja: "サーバとストレージを結ぶ高速専用網。" },
    { id: 260, cat: "電腦系統", zh: "精簡型電腦", ja: "シンクライアント", yomi: "しんくらいあんと", eng: "Thin Client", desc_zh: "客戶端只負責顯示，處理在伺服器端進行。", desc_ja: "処理をサーバ側で行う最小限機能の端末。" },
    { id: 268, cat: "電腦系統", zh: "UPS", ja: "UPS", yomi: "ゆーぴーえす", eng: "UPS", desc_zh: "不斷電系統，停電時提供臨時電力。", desc_ja: "停電時に電力を供給する無停電電源装置。" },
    { id: 269, cat: "電腦系統", zh: "PWM", ja: "PWM", yomi: "ぴーだぶりゅーえむ", eng: "PWM", desc_zh: "脈衝寬度調變，用於控制馬達轉速或LED亮度。", desc_ja: "パルス幅で電圧等を制御する方式。" },
    { id: 270, cat: "電腦系統", zh: "驅動程式", ja: "デバイスドライバ", yomi: "でばいすどらいば", eng: "Device Driver", desc_zh: "控制硬體裝置的軟體。", desc_ja: "周辺機器を制御するためのソフト。" },
    { id: 271, cat: "電腦系統", zh: "SNMP", ja: "SNMP", yomi: "えすえぬえむぴー", eng: "SNMP", desc_zh: "監控網路設備狀態的協定。", desc_ja: "ネットワーク機器を監視するプロトコル。" },
    { id: 272, cat: "電腦系統", zh: "Telnet", ja: "Telnet", yomi: "てるねっと", eng: "Telnet", desc_zh: "早期的遠端登入協定 (未加密，不安全)。", desc_ja: "遠隔操作プロトコル (暗号化なし)。" },
    { id: 273, cat: "電腦系統", zh: "LPWA", ja: "LPWA", yomi: "えるぴーだぶりゅえー", eng: "LPWA", desc_zh: "低功耗廣域網路，適合 IoT。", desc_ja: "省電力で広範囲をカバーする無線技術。" },
    { id: 274, cat: "電腦系統", zh: "5G", ja: "5G", yomi: "ふぁいぶじー", eng: "5G", desc_zh: "第五代行動通訊 (高速、低延遲、多連結)。", desc_ja: "高速・低遅延・多数接続の移動通信。" },
    { id: 275, cat: "電腦系統", zh: "MAC位址過濾", ja: "MACアドレスフィルタリング", yomi: "まっくあどれすふぃるたりんぐ", eng: "MAC Filtering", desc_zh: "只允許特定 MAC 位址的裝置連線。", desc_ja: "特定のMACアドレスのみ接続を許可する。" },
    { id: 276, cat: "電腦系統", zh: "WPA3", ja: "WPA3", yomi: "だぶりゅーぴーえーすりー", eng: "WPA3", desc_zh: "最新的無線網路加密標準，比 WPA2 更安全。", desc_ja: "最新の無線LANセキュリティ規格。" },

    // --- 6. 電腦系統：安全 (Security) ---
    { id: 31, cat: "電腦系統", zh: "公開金鑰加密", ja: "公開鍵暗号", yomi: "こうかいかぎあんごう", eng: "Public Key", desc_zh: "雙鑰匙：公鑰加密，私鑰解密。", desc_ja: "2つの鍵。公開鍵で暗号化、秘密鍵で復号。" },
    { id: 32, cat: "電腦系統", zh: "共通金鑰加密", ja: "共通鍵暗号", yomi: "きょうつうかぎあんごう", eng: "Symmetric Key", desc_zh: "單鑰匙：加密解密用同一把。", desc_ja: "1つの鍵。暗号化と復号が同じ。" },
    { id: 33, cat: "電腦系統", zh: "數位簽章", ja: "デジタル署名", yomi: "でじたるしょめい", eng: "Digital Signature", desc_zh: "防竄改與確認身分。", desc_ja: "改ざん検知と本人確認。" },
    { id: 91, cat: "電腦系統", zh: "防火牆", ja: "ファイアウォール", yomi: "ふぁいあうぉーる", eng: "Firewall", desc_zh: "阻擋未授權存取。", desc_ja: "不正アクセス遮断。" },
    { id: 92, cat: "電腦系統", zh: "WAF", ja: "WAF", yomi: "わふ", eng: "WAF", desc_zh: "Web 應用防火牆。", desc_ja: "Webアプリ用ファイアウォール。" },
    { id: 93, cat: "電腦系統", zh: "DMZ", ja: "DMZ", yomi: "でぃーえむぜっと", eng: "DMZ", desc_zh: "非軍事區，隔離內外網。", desc_ja: "外部公開用の隔離エリア。" },
    { id: 94, cat: "電腦系統", zh: "VPN", ja: "VPN", yomi: "ぶいぴーえぬ", eng: "VPN", desc_zh: "虛擬私有網路，加密通道。", desc_ja: "仮想的な専用線。" },
    { id: 95, cat: "電腦系統", zh: "惡意軟體", ja: "マルウェア", yomi: "まるうぇあ", eng: "Malware", desc_zh: "惡意程式總稱。", desc_ja: "悪意あるソフトの総称。" },
    { id: 96, cat: "電腦系統", zh: "勒索軟體", ja: "ランサムウェア", yomi: "らんさむうぇあ", eng: "Ransomware", desc_zh: "加密檔案勒索贖金。", desc_ja: "ファイルを人質に身代金要求。" },
    { id: 97, cat: "電腦系統", zh: "網路釣魚", ja: "フィッシング", yomi: "ふぃっしんぐ", eng: "Phishing", desc_zh: "偽裝網站騙個資。", desc_ja: "偽サイトで情報詐取。" },
    { id: 98, cat: "電腦系統", zh: "社交工程", ja: "ソーシャルエンジニアリング", yomi: "そーしゃる", eng: "Social Engineering", desc_zh: "利用心理弱點騙取資訊。", desc_ja: "心理的な隙をつく攻撃。" },
    { id: 99, cat: "電腦系統", zh: "DoS攻擊", ja: "DoS攻撃", yomi: "どすこうげき", eng: "DoS", desc_zh: "癱瘓伺服器。", desc_ja: "サーバ停止攻撃。" },
    { id: 100, cat: "電腦系統", zh: "SQL注入", ja: "SQLインジェクション", yomi: "えすきゅーえる", eng: "SQL Injection", desc_zh: "注入惡意 SQL 攻擊資料庫。", desc_ja: "DBを不正操作する攻撃。" },
    { id: 101, cat: "電腦系統", zh: "XSS", ja: "XSS", yomi: "くろすさいと", eng: "XSS", desc_zh: "網頁植入惡意腳本。", desc_ja: "Webに悪意あるスクリプト埋め込み。" },
    { id: 102, cat: "電腦系統", zh: "暴力破解", ja: "ブルートフォース", yomi: "ぶるーとふぉーす", eng: "Brute Force", desc_zh: "嘗試所有密碼組合。", desc_ja: "総当たり攻撃。" },
    { id: 103, cat: "電腦系統", zh: "多因素認證", ja: "多要素認証", yomi: "たようそにんしょう", eng: "MFA", desc_zh: "兩種以上驗證方式。", desc_ja: "2つ以上の要素で認証。" },
    { id: 104, cat: "電腦系統", zh: "生物辨識", ja: "バイオメトリクス", yomi: "ばいおめとりくす", eng: "Biometrics", desc_zh: "指紋、臉部等認證。", desc_ja: "生体情報での認証。" },
    { id: 105, cat: "電腦系統", zh: "CA", ja: "認証局", yomi: "にんしょうきょく", eng: "CA", desc_zh: "發行數位憑證的機構。", desc_ja: "証明書発行機関。" },
    { id: 211, cat: "電腦系統", zh: "零信任", ja: "ゼロトラスト", yomi: "ぜろとらすと", eng: "Zero Trust", desc_zh: "不信任任何內外網，每次存取都驗證。", desc_ja: "全てを信頼せず毎回検証する概念。" },
    { id: 212, cat: "電腦系統", zh: "APT攻擊", ja: "APT攻撃", yomi: "えーぴーてぃーこうげき", eng: "APT Attack", desc_zh: "針對特定目標長期潛伏的持續性攻擊。", desc_ja: "特定の標的を執拗に攻撃する手法。" },
    { id: 213, cat: "電腦系統", zh: "字典攻擊", ja: "辞書攻撃", yomi: "じしょこうげき", eng: "Dictionary Attack", desc_zh: "使用常用單字列表嘗試破解密碼。", desc_ja: "単語リストを使ってパスワードを破る。" },
    { id: 214, cat: "電腦系統", zh: "彩虹表", ja: "レインボーテーブル", yomi: "れいんぼーてーぶる", eng: "Rainbow Table", desc_zh: "預先計算雜湊值以快速破解密碼的對照表。", desc_ja: "ハッシュ値を事前計算したクラック用表。" },
    { id: 215, cat: "電腦系統", zh: "加鹽", ja: "ソルト", yomi: "そると", eng: "Salting", desc_zh: "在密碼中加入隨機字串再雜湊，防止彩虹表。", desc_ja: "乱数を付加してハッシュ化し解読を防ぐ。" },
    { id: 216, cat: "電腦系統", zh: "鍵盤側錄", ja: "キーロガー", yomi: "きーろがー", eng: "Keylogger", desc_zh: "記錄使用者按鍵輸入的惡意軟體。", desc_ja: "キー入力操作を記録するスパイウェア。" },
    { id: 217, cat: "電腦系統", zh: "Rootkit", ja: "ルートキット", yomi: "るーときっと", eng: "Rootkit", desc_zh: "隱藏攻擊痕跡並維持入侵權限的工具包。", desc_ja: "侵入の痕跡を隠し権限を維持するツール。" },
    { id: 218, cat: "電腦系統", zh: "DDos攻擊", ja: "DDoS攻撃", yomi: "でぃーどすこうげき", eng: "DDoS", desc_zh: "利用多台電腦分散同時發動 DoS 攻擊。", desc_ja: "多数の機器から一斉に攻撃を仕掛ける。" },
    { id: 219, cat: "電腦系統", zh: "加密雜湊函數", ja: "ハッシュ関数", yomi: "はっしゅかんすう", eng: "Hash Function", desc_zh: "將資料轉換為固定長度亂碼，不可逆。", desc_ja: "データを固定長の要約値に変換する関数。" },
    { id: 220, cat: "電腦系統", zh: "PKI", ja: "PKI", yomi: "ぴーけーあい", eng: "PKI", desc_zh: "公開金鑰基礎建設，管理憑證的體系。", desc_ja: "公開鍵暗号基盤。証明書を管理する仕組み。" },
    { id: 221, cat: "電腦系統", zh: "CRL", ja: "CRL", yomi: "しーあーるえる", eng: "CRL", desc_zh: "憑證撤銷清單，列出已失效的數位憑證。", desc_ja: "有効期限前に無効になった証明書リスト。" },
    { id: 222, cat: "電腦系統", zh: "ISMS", ja: "ISMS", yomi: "あいえすえむえす", eng: "ISMS", desc_zh: "資訊安全管理系統。", desc_ja: "情報セキュリティマネジメントシステム。" },
    { id: 223, cat: "電腦系統", zh: "機密性", ja: "機密性", yomi: "きみつせい", eng: "Confidentiality", desc_zh: "資安三要素之一，確保只有授權者能存取。", desc_ja: "許可された人だけがアクセスできること。" },
    { id: 224, cat: "電腦系統", zh: "完整性", ja: "完全性", yomi: "かんぜんせい", eng: "Integrity", desc_zh: "資安三要素之一，確保資料準確未被竄改。", desc_ja: "データが正確で改ざんされていないこと。" },
    { id: 225, cat: "電腦系統", zh: "可用性", ja: "可用性", yomi: "かようせい", eng: "Availability", desc_zh: "資安三要素之一，確保需要時能使用系統。", desc_ja: "必要な時にいつでも使えること。" },
    { id: 226, cat: "電腦系統", zh: "風險評估", ja: "リスクアセスメント", yomi: "りすくあせすめんと", eng: "Risk Assessment", desc_zh: "分析威脅與脆弱性，評估潛在損失。", desc_ja: "脅威や脆弱性を分析し損失を予測する。" },
    { id: 227, cat: "電腦系統", zh: "BYOD", ja: "BYOD", yomi: "びーわいおーでぃー", eng: "BYOD", desc_zh: "員工攜帶私人設備處理公務。", desc_ja: "私物端末を業務に利用すること。" },
    { id: 228, cat: "電腦系統", zh: "MDM", ja: "MDM", yomi: "えむでぃーえむ", eng: "MDM", desc_zh: "行動裝置管理，統一控管員工手機平板。", desc_ja: "モバイル端末を統合管理するシステム。" },
    { id: 251, cat: "電腦系統", zh: "高可用性", ja: "ハイアベイラビリティ", yomi: "はいあべいらびりてぃ", eng: "HA", desc_zh: "系統長時間持續運作不中斷的能力。", desc_ja: "システムが停止せず稼働し続ける能力。" },
    { id: 252, cat: "電腦系統", zh: "容錯", ja: "フォールトトレランス", yomi: "ふぉーるととれらんす", eng: "Fault Tolerance", desc_zh: "即使部分故障，系統仍能繼續運作的特性。", desc_ja: "一部が故障しても稼働を続ける性質。" },
    { id: 253, cat: "電腦系統", zh: "失效安全", ja: "フェールセーフ", yomi: "ふぇーるせーふ", eng: "Fail Safe", desc_zh: "故障時以安全為優先，停止系統運作。", desc_ja: "故障時に安全を優先しシステムを止める。" },
    { id: 254, cat: "電腦系統", zh: "失效軟運作", ja: "フェールソフト", yomi: "ふぇーるそふと", eng: "Fail Soft", desc_zh: "故障時降低效能，但維持基本運作。", desc_ja: "故障時に機能を落として継続する。" },
    { id: 255, cat: "電腦系統", zh: "雙工系統", ja: "デュプレックスシステム", yomi: "でゅぷれっくす", eng: "Duplex System", desc_zh: "主系統運作，副系統待機，故障時切換。", desc_ja: "主系で処理し待機系へ切り替える方式。" },
    { id: 256, cat: "電腦系統", zh: "雙重系統", ja: "デュアルシステム", yomi: "でゅあるしすてむ", eng: "Dual System", desc_zh: "兩套系統同時進行相同處理並比對結果。", desc_ja: "2系統で同じ処理を行い結果を照合する。" },
    { id: 277, cat: "電腦系統", zh: "TPM", ja: "TPM", yomi: "てぃーぴーえむ", eng: "TPM", desc_zh: "內建於電腦主機板的安全晶片。", desc_ja: "PCにあるセキュリティチップ。" },
    { id: 278, cat: "電腦系統", zh: "沙箱", ja: "サンドボックス", yomi: "さんどぼっくす", eng: "Sandbox", desc_zh: "隔離的執行環境，用於測試不明程式。", desc_ja: "隔離された仮想環境。ウイルス解析に利用。" },
    { id: 279, cat: "電腦系統", zh: "滲透測試", ja: "ペネトレーションテスト", yomi: "ぺねとれーしょんてすと", eng: "Penetration Test", desc_zh: "模擬駭客攻擊以找出系統漏洞。", desc_ja: "侵入を試みて脆弱性を探すテスト。" },
    { id: 280, cat: "電腦系統", zh: "數位鑑識", ja: "デジタルフォレンジック", yomi: "でじたるふぉれんじっく", eng: "Digital Forensics", desc_zh: "收集與分析數位證據以調查犯罪。", desc_ja: "犯罪捜査のための電子的証拠解析。" },

    // --- 7. 技術管理：開發與軟體工程 ---
    { id: 34, cat: "技術管理", zh: "瀑布模型", ja: "ウォーターフォール", yomi: "うぉーたーふぉーる", eng: "Waterfall", desc_zh: "按順序開發，不回頭。", desc_ja: "順序通り進める開発。" },
    { id: 35, cat: "技術管理", zh: "敏捷開發", ja: "アジャイル", yomi: "あじゃいる", eng: "Agile", desc_zh: "短週期反覆開發。", desc_ja: "短期間の反復開発。" },
    { id: 106, cat: "技術管理", zh: "物件導向", ja: "オブジェクト指向", yomi: "おぶじぇくと", eng: "Object-Oriented", desc_zh: "以物件為中心開發。", desc_ja: "モノ中心の開発。" },
    { id: 107, cat: "技術管理", zh: "類別", ja: "クラス", yomi: "くらす", eng: "Class", desc_zh: "物件的設計圖或模板。", desc_ja: "オブジェクトの設計図。" },
    { id: 108, cat: "技術管理", zh: "實體", ja: "インスタンス", yomi: "いんすたんす", eng: "Instance", desc_zh: "根據類別產生的實際物件。", desc_ja: "クラスから生成された実体。" },
    { id: 109, cat: "技術管理", zh: "封裝", ja: "カプセル化", yomi: "かぷせるか", eng: "Encapsulation", desc_zh: "隱藏物件內部的資料與實作細節。", desc_ja: "データと手続きをまとめ、詳細を隠蔽すること。" },
    { id: 110, cat: "技術管理", zh: "繼承", ja: "継承", yomi: "けいしょう", eng: "Inheritance", desc_zh: "承接既有類別的屬性與方法。", desc_ja: "既存クラスの性質を受け継ぐこと。" },
    { id: 111, cat: "技術管理", zh: "多型", ja: "ポリモーフィズム", yomi: "ぽりもーふぃずむ", eng: "Polymorphism", desc_zh: "同一訊息對不同物件有不同反應。", desc_ja: "同じ命令でも対象によって振る舞いが変わる性質。" },
    { id: 112, cat: "技術管理", zh: "UML", ja: "UML", yomi: "ゆーえむえる", eng: "UML", desc_zh: "軟體設計的標準圖示語言。", desc_ja: "ソフトウェア設計のための統一モデリング言語。" },
    { id: 113, cat: "技術管理", zh: "類別圖", ja: "クラス図", yomi: "くらすず", eng: "Class Diagram", desc_zh: "描述類別之間的靜態關係。", desc_ja: "クラス間の静的な関係を表す図。" },
    { id: 114, cat: "技術管理", zh: "使用案例圖", ja: "ユースケース図", yomi: "ゆーすけーすず", eng: "Use Case Diagram", desc_zh: "從使用者角度描述系統功能的圖。", desc_ja: "利用者視点でシステム機能を表す図。" },
    { id: 115, cat: "技術管理", zh: "黑箱測試", ja: "ブラックボックステスト", yomi: "ぶらっくぼっくすてすと", eng: "Black-box Testing", desc_zh: "只關注輸入與輸出，不看內部構造的測試。", desc_ja: "内部構造を見ず、入力と出力だけを確認するテスト。" },
    { id: 116, cat: "技術管理", zh: "白箱測試", ja: "ホワイトボックステスト", yomi: "ほわいとぼっくすてすと", eng: "White-box Testing", desc_zh: "檢查程式內部邏輯與結構的測試。", desc_ja: "プログラムの内部構造や論理を確認するテスト。" },
    { id: 117, cat: "技術管理", zh: "單元測試", ja: "単体テスト", yomi: "たんたいてすと", eng: "Unit Testing", desc_zh: "針對個別模組進行的測試。", desc_ja: "個々のモジュール単位で行うテスト。" },
    { id: 118, cat: "技術管理", zh: "整合測試", ja: "結合テスト", yomi: "けつごうてすと", eng: "Integration Testing", desc_zh: "組合多個模組進行的測試。", desc_ja: "複数のモジュールを組み合わせて行うテスト。" },
    { id: 119, cat: "技術管理", zh: "系統測試", ja: "システムテスト", yomi: "しすてむてすと", eng: "System Testing", desc_zh: "針對整個系統是否符合需求進行測試。", desc_ja: "システム全体が要件を満たすか確認するテスト。" },
    { id: 120, cat: "技術管理", zh: "DevOps", ja: "DevOps", yomi: "でぼぷす", eng: "DevOps", desc_zh: "開發 (Dev) 與維運 (Ops) 合作以加速開發。", desc_ja: "開発と運用が連携し、迅速に開発する手法。" },
    { id: 365, cat: "技術管理", zh: "CAD", ja: "CAD", yomi: "きゃど", eng: "CAD", desc_zh: "電腦輔助設計。", desc_ja: "コンピュータ支援設計。" },
    { id: 366, cat: "技術管理", zh: "CAM", ja: "CAM", yomi: "きゃむ", eng: "CAM", desc_zh: "電腦輔助製造。", desc_ja: "コンピュータ支援製造。" },

    // --- 8. 技術管理：專案與服務管理 ---
    { id: 36, cat: "技術管理", zh: "WBS", ja: "WBS", yomi: "だぶりゅーびーえす", eng: "WBS", desc_zh: "工作分解結構。", desc_ja: "作業分解図。" },
    { id: 37, cat: "技術管理", zh: "關鍵路徑", ja: "クリティカルパス", yomi: "くりてぃかるぱす", eng: "Critical Path", desc_zh: "最長路徑，決定工期。", desc_ja: "最長経路。" },
    { id: 38, cat: "技術管理", zh: "EVM", ja: "EVM", yomi: "いーぶいえむ", eng: "EVM", desc_zh: "用金額管理進度。", desc_ja: "金額で進捗管理。" },
    { id: 39, cat: "技術管理", zh: "SLA", ja: "SLA", yomi: "えすえるえー", eng: "SLA", desc_zh: "服務層級協定，品質保證。", desc_ja: "サービス品質の保証。" },
    { id: 40, cat: "技術管理", zh: "MTBF", ja: "MTBF", yomi: "えむてぃーびーえふ", eng: "MTBF", desc_zh: "平均無故障時間 (可靠性)。", desc_ja: "平均故障間隔 (信頼性)。" },
    { id: 41, cat: "技術管理", zh: "MTTR", ja: "MTTR", yomi: "えむてぃーてぃーあーる", eng: "MTTR", desc_zh: "平均修復時間 (可維護性)。", desc_ja: "平均修復時間 (保守性)。" },
    { id: 42, cat: "技術管理", zh: "稼動率", ja: "稼働率", yomi: "かどうりつ", eng: "Availability Rate", desc_zh: "系統正常運作時間的比例。", desc_ja: "システムが動作している割合。" },
    { id: 121, cat: "技術管理", zh: "ITIL", ja: "ITIL", yomi: "あいてぃる", eng: "ITIL", desc_zh: "IT服務管理最佳實務。", desc_ja: "ITサービス管理事例。" },
    { id: 122, cat: "技術管理", zh: "服務台", ja: "サービスデスク", yomi: "さーびすですく", eng: "Service Desk", desc_zh: "使用者的單一聯繫窗口。", desc_ja: "利用者からの問い合わせ窓口（単一接点）。" },
    { id: 123, cat: "技術管理", zh: "事件管理", ja: "インシデント管理", yomi: "いんしでんと", eng: "Incident Mgmt", desc_zh: "盡快恢復服務。", desc_ja: "迅速な復旧。" },
    { id: 124, cat: "技術管理", zh: "問題管理", ja: "問題管理", yomi: "もんだいかんり", eng: "Problem Mgmt", desc_zh: "查明根本原因。", desc_ja: "根本原因の究明。" },
    { id: 125, cat: "技術管理", zh: "變更管理", ja: "変更管理", yomi: "へんこうかんり", eng: "Change Mgmt", desc_zh: "評估並批准對系統的變更。", desc_ja: "システムへの変更を評価・承認する管理。" },
    { id: 126, cat: "技術管理", zh: "PMBOK", ja: "PMBOK", yomi: "ぴんぼっく", eng: "PMBOK", desc_zh: "專案管理知識體系。", desc_ja: "PMの知識体系。" },
    { id: 127, cat: "技術管理", zh: "範疇", ja: "スコープ", yomi: "すこーぷ", eng: "Scope", desc_zh: "專案的工作範圍。", desc_ja: "プロジェクトの作業範囲。" },
    { id: 128, cat: "技術管理", zh: "風險管理", ja: "リスク管理", yomi: "りすくかんり", eng: "Risk Mgmt", desc_zh: "識別並應對潛在風險的過程。", desc_ja: "リスクを特定し、対策を講じるプロセス。" },
    { id: 248, cat: "技術管理", zh: "甘特圖", ja: "ガントチャート", yomi: "がんとちゃーと", eng: "Gantt Chart", desc_zh: "用條狀圖顯示專案進度的圖表。", desc_ja: "日程と進捗を横棒で表した図。" },
    { id: 249, cat: "技術管理", zh: "魚骨圖", ja: "特性要因図", yomi: "とくせいよういんず", eng: "Fishbone Diagram", desc_zh: "分析問題原因與結果關係的圖 (石川圖)。", desc_ja: "原因と結果の関係を整理する図。" },
    { id: 250, cat: "技術管理", zh: "雷達圖", ja: "レーダーチャート", yomi: "れーだーちゃーと", eng: "Radar Chart", desc_zh: "顯示多個項目平衡狀態的放射狀圖表。", desc_ja: "複数項目のバランスを見る放射状の図。" },

    // --- 9. 技術管理：策略與法律 (Strategy & Legal) ---
    { id: 43, cat: "技術管理", zh: "SWOT分析", ja: "SWOT分析", yomi: "すうぉっとぶんせき", eng: "SWOT Analysis", desc_zh: "分析優勢、劣勢、機會、威脅。", desc_ja: "強み、弱み、機会、脅威を分析。" },
    { id: 44, cat: "技術管理", zh: "BPR", ja: "BPR", yomi: "びーぴーあーる", eng: "BPR", desc_zh: "業務流程重組。", desc_ja: "業務プロセスの抜本的改革。" },
    { id: 45, cat: "技術管理", zh: "CRM", ja: "CRM", yomi: "しーあーるえむ", eng: "CRM", desc_zh: "客戶關係管理。", desc_ja: "顧客関係管理。" },
    { id: 46, cat: "技術管理", zh: "BCP", ja: "BCP", yomi: "びーしーぴー", eng: "BCP", desc_zh: "業務連續性計畫 (防災)。", desc_ja: "事業継続計画。" },
    { id: 47, cat: "技術管理", zh: "核心能力", ja: "コアコンピタンス", yomi: "こあこんぴたんす", eng: "Core Competence", desc_zh: "企業的核心競爭優勢。", desc_ja: "競合他社に真似できない強み。" },
    { id: 48, cat: "技術管理", zh: "KPI", ja: "KPI", yomi: "けーぴーあい", eng: "KPI", desc_zh: "關鍵績效指標。", desc_ja: "重要業績評価指標。" },
    { id: 49, cat: "技術管理", zh: "IoT", ja: "IoT", yomi: "あいおーてぃー", eng: "IoT", desc_zh: "物聯網。", desc_ja: "モノのインターネット。" },
    { id: 50, cat: "技術管理", zh: "DX", ja: "DX", yomi: "でぃーえっくす", eng: "DX", desc_zh: "數位轉型。", desc_ja: "デジタル変革。" },
    { id: 129, cat: "技術管理", zh: "AI", ja: "AI", yomi: "えーあい", eng: "AI", desc_zh: "人工智慧。", desc_ja: "人工知能。" },
    { id: 130, cat: "技術管理", zh: "機器學習", ja: "機械学習", yomi: "きかいがくしゅう", eng: "Machine Learning", desc_zh: "讓電腦從數據中學習規則的技術。", desc_ja: "データからコンピュータが学習する技術。" },
    { id: 131, cat: "技術管理", zh: "深度學習", ja: "ディープラーニング", yomi: "でぃーぷらーにんぐ", eng: "Deep Learning", desc_zh: "模仿人腦神經網路的機器學習技術。", desc_ja: "脳神経回路を模した機械学習技術。" },
    { id: 132, cat: "技術管理", zh: "大數據", ja: "ビッグデータ", yomi: "びっぐでーた", eng: "Big Data", desc_zh: "巨大且多樣化的資料集合。", desc_ja: "巨大で多種多様なデータ群。" },
    { id: 133, cat: "技術管理", zh: "區塊鏈", ja: "ブロックチェーン", yomi: "ぶろっくちぇーん", eng: "Blockchain", desc_zh: "分散式帳本技術，難以竄改。", desc_ja: "分散型台帳技術。改ざんが困難。" },
    { id: 134, cat: "技術管理", zh: "雲端運算", ja: "クラウドコンピューティング", yomi: "くらうどこんぴゅーてぃんぐ", eng: "Cloud Computing", desc_zh: "透過網路使用伺服器資源的服務。", desc_ja: "ネット経由でIT資源を利用する形態。" },
    { id: 135, cat: "技術管理", zh: "SaaS", ja: "SaaS", yomi: "さーす", eng: "SaaS", desc_zh: "透過網路提供軟體功能 (如 Gmail)。", desc_ja: "ソフトの機能をネット経由で提供する。" },
    { id: 136, cat: "技術管理", zh: "PaaS", ja: "PaaS", yomi: "ぱーす", eng: "PaaS", desc_zh: "提供應用程式開發平台。", desc_ja: "アプリ開発のプラットフォームを提供する。" },
    { id: 137, cat: "技術管理", zh: "IaaS", ja: "IaaS", yomi: "いあーす", eng: "IaaS", desc_zh: "提供虛擬機、網路等基礎設施。", desc_ja: "仮想機やNWなどインフラを提供する。" },
    { id: 138, cat: "技術管理", zh: "邊緣運算", ja: "エッジコンピューティング", yomi: "えっじこんぴゅーてぃんぐ", eng: "Edge Computing", desc_zh: "在靠近使用者的位置處理數據以降低延遲。", desc_ja: "端末の近くで処理し、遅延を減らす技術。" },
    { id: 139, cat: "技術管理", zh: "著作權", ja: "著作権", yomi: "ちょさくけん", eng: "Copyright", desc_zh: "保護創作物的權利 (包含程式碼)。", desc_ja: "創作物を保護する権利 (プログラム含む)。" },
    { id: 140, cat: "技術管理", zh: "專利權", ja: "特許権", yomi: "とっきょけん", eng: "Patent", desc_zh: "保護發明與技術構想的權利。", desc_ja: "発明や技術的アイデアを保護する権利。" },
    { id: 141, cat: "技術管理", zh: "商標權", ja: "商標権", yomi: "しょうひょうけん", eng: "Trademark", desc_zh: "保護品牌名稱與標誌的權利。", desc_ja: "ブランド名やロゴを保護する権利。" },
    { id: 142, cat: "技術管理", zh: "營業秘密", ja: "営業秘密", yomi: "えいぎょうひみつ", eng: "Trade Secret", desc_zh: "具有秘密性與價值的商業資訊。", desc_ja: "秘密として管理される有用な情報。" },
    { id: 143, cat: "技術管理", zh: "PL法", ja: "PL法", yomi: "ぴーえるほう", eng: "PL Law", desc_zh: "產品責任法，針對產品缺陷造成損害的賠償。", desc_ja: "製造物責任法。製品の欠陥による損害賠償。" },
    { id: 144, cat: "技術管理", zh: "勞動派遣", ja: "労働者派遣", yomi: "ろうどうしゃはけん", eng: "Dispatching", desc_zh: "勞工接受派遣公司指揮，到客戶端工作。", desc_ja: "派遣元と雇用契約し、派遣先の指揮で働く。" },
    { id: 145, cat: "技術管理", zh: "承包", ja: "請負", yomi: "うけおい", eng: "Contracting", desc_zh: "承諾完成工作以換取報酬，指揮權在承包商。", desc_ja: "成果物の完成を約束する。指揮権は請負側。" },
    { id: 146, cat: "技術管理", zh: "準委任", ja: "準委任", yomi: "じゅんいにん", eng: "Quasi-mandate", desc_zh: "受託處理業務，不保證完成成果 (如顧問)。", desc_ja: "業務処理を委託する。完成責任はない。" },
    { id: 147, cat: "技術管理", zh: "個資法", ja: "個人情報保護法", yomi: "こじんじょうほうほごほう", eng: "APPI", desc_zh: "保護個人隱私資訊的法律。", desc_ja: "個人のプライバシー情報を守る法律。" },
    { id: 148, cat: "技術管理", zh: "合規", ja: "コンプライアンス", yomi: "こんぷらいあんす", eng: "Compliance", desc_zh: "企業遵守法律與倫理規範。", desc_ja: "法令遵守。企業がルールを守ること。" },
    { id: 149, cat: "技術管理", zh: "CSR", ja: "CSR", yomi: "しーえすあーる", eng: "CSR", desc_zh: "企業社會責任。", desc_ja: "企業の社会的責任。" },
    { id: 150, cat: "技術管理", zh: "SDGs", ja: "SDGs", yomi: "えすでぃーじーず", eng: "SDGs", desc_zh: "永續發展目標。", desc_ja: "持続可能な開発目標。" },
    { id: 235, cat: "技術管理", zh: "ABC分析", ja: "ABC分析", yomi: "えーびーしーぶんせき", eng: "ABC Analysis", desc_zh: "根據重要性將項目分為 A、B、C 三類。", desc_ja: "重要度で3ランクに分ける分析手法。" },
    { id: 236, cat: "技術管理", zh: "帕累托圖", ja: "パレート図", yomi: "ぱれーとず", eng: "Pareto Chart", desc_zh: "結合長條圖與累積曲線，找出主要問題。", desc_ja: "棒グラフと折れ線で重要項目を特定する。" },
    { id: 237, cat: "技術管理", zh: "散布圖", ja: "散布図", yomi: "さんぷず", eng: "Scatter Plot", desc_zh: "用點表示兩個變數間的關係 (相關性)。", desc_ja: "2変数の相関関係を見るグラフ。" },
    { id: 238, cat: "技術管理", zh: "損益表", ja: "損益計算書", yomi: "そんえきけいさんしょ", eng: "P/L", desc_zh: "顯示企業一段時間內的盈利狀況。", desc_ja: "企業の経営成績(利益)を表す表。" },
    { id: 239, cat: "技術管理", zh: "資產負債表", ja: "貸借対照表", yomi: "たいしゃくたいしょうひょう", eng: "B/S", desc_zh: "顯示企業在特定時間點的財務狀況。", desc_ja: "企業の財政状態(資産・負債)を表す表。" },
    { id: 240, cat: "技術管理", zh: "ROI", ja: "ROI", yomi: "あーるおーあい", eng: "ROI", desc_zh: "投資報酬率，衡量投資獲利的指標。", desc_ja: "投資対効果。投資に対する利益率。" },
    { id: 241, cat: "技術管理", zh: "TCO", ja: "TCO", yomi: "てぃーしーおー", eng: "TCO", desc_zh: "總體擁有成本，包含採購、維護等。", desc_ja: "導入から廃棄までの総コスト。" },
    { id: 242, cat: "技術管理", zh: "損益平衡點", ja: "損益分岐点", yomi: "そんえきぶんきてん", eng: "Break-even Point", desc_zh: "收入與成本相等，不賺不賠的銷售額。", desc_ja: "利益がゼロになる売上高。" },
    { id: 243, cat: "技術管理", zh: "核心競爭力", ja: "コアコンピタンス", yomi: "こあこんぴたんす", eng: "Core Competence", desc_zh: "企業獨有的、他社難以模仿的強項。", desc_ja: "他社が真似できない核となる強み。" },
    { id: 244, cat: "技術管理", zh: "藍海策略", ja: "ブルーオーシャン", yomi: "ぶるーおーしゃん", eng: "Blue Ocean", desc_zh: "開創無競爭的新市場空間。", desc_ja: "競争のない未開拓市場を創る戦略。" },
    { id: 245, cat: "技術管理", zh: "長尾效應", ja: "ロングテール", yomi: "ろんぐてーる", eng: "Long Tail", desc_zh: "冷門商品總銷售額超過熱門商品的現象。", desc_ja: "死に筋商品の合計が売上の多くを占める。" },
    { id: 246, cat: "技術管理", zh: "腦力激盪", ja: "ブレーンストーミング", yomi: "ぶれーんすとーみんぐ", eng: "Brainstorming", desc_zh: "多人自由提出想法，禁止批評。", desc_ja: "批判禁止で自由にアイデアを出し合う。" },
    { id: 247, cat: "技術管理", zh: "KJ法", ja: "KJ法", yomi: "けーじぇいほう", eng: "KJ Method", desc_zh: "將點子寫在卡片上並分類整理的發想法。", desc_ja: "カードを使ってアイデアを整理する手法。" },
    { id: 281, cat: "技術管理", zh: "PPM", ja: "PPM", yomi: "ぴーぴーえむ", eng: "PPM", desc_zh: "將產品分為問題兒、明星、金牛、敗犬。", desc_ja: "事業を4象限(花形・金のなる木等)で分析。" },
    { id: 282, cat: "技術管理", zh: "行銷4P", ja: "マーケティングミックス", yomi: "まーけてぃんぐみっくす", eng: "4P", desc_zh: "產品、價格、通路、推廣。", desc_ja: "製品・価格・流通・販促の4要素。" },
    { id: 283, cat: "技術管理", zh: "4C", ja: "4C", yomi: "よんしー", eng: "4C", desc_zh: "從顧客觀點出發的行銷要素 (成本、便利性等)。", desc_ja: "顧客視点の4要素 (コスト・利便性等)。" },
    { id: 284, cat: "技術管理", zh: "RFM分析", ja: "RFM分析", yomi: "あーるえふえむぶんせき", eng: "RFM Analysis", desc_zh: "根據最近購買日、頻率、金額分析顧客。", desc_ja: "最新購買日・頻度・金額で顧客を分析。" },
    { id: 285, cat: "技術管理", zh: "BSC", ja: "バランススコアカード", yomi: "ばらんすすこあかーど", eng: "Balanced Scorecard", desc_zh: "從財務、顧客、流程、學習四個視角評估績效。", desc_ja: "財務・顧客・業務・学習の4視点で評価。" },
    { id: 286, cat: "技術管理", zh: "ERP", ja: "ERP", yomi: "いーあーるぴー", eng: "ERP", desc_zh: "企業資源規劃，整合管理企業資源。", desc_ja: "経営資源を統合的に管理するシステム。" },
    { id: 287, cat: "技術管理", zh: "SCM", ja: "SCM", yomi: "えすしーえむ", eng: "SCM", desc_zh: "供應鏈管理，優化從生產到銷售的流程。", desc_ja: "供給連鎖管理。調達から販売まで最適化。" },
    { id: 288, cat: "技術管理", zh: "PLM", ja: "PLM", yomi: "ぴーえるえむ", eng: "PLM", desc_zh: "產品生命週期管理，從開發到報廢。", desc_ja: "製品の企画から廃棄までを一元管理。" },
    { id: 289, cat: "技術管理", zh: "群眾募資", ja: "クラウドファンディング", yomi: "くらうどふぁんでぃんぐ", eng: "Crowdfunding", desc_zh: "透過網路向大眾募集資金。", desc_ja: "ネットで不特定多数から資金を集める。" },
    { id: 290, cat: "技術管理", zh: "共享經濟", ja: "シェアリングエコノミー", yomi: "しぇありんぐえこのみー", eng: "Sharing Economy", desc_zh: "個人之間共享資產或服務。", desc_ja: "個人間で資産やサービスを共有する。" },
    { id: 291, cat: "技術管理", zh: "遠距工作", ja: "テレワーク", yomi: "てれわーく", eng: "Telework", desc_zh: "利用 ICT 技術在遠端工作。", desc_ja: "ICTを活用し、離れた場所で働く。" },
    { id: 292, cat: "技術管理", zh: "無障礙設計", ja: "アクセシビリティ", yomi: "あくせしびりてぃ", eng: "Accessibility", desc_zh: "讓所有人 (含身障者) 都能使用的程度。", desc_ja: "高齢者や障害者を含む誰でも使える度合い。" },
    { id: 293, cat: "技術管理", zh: "通用設計", ja: "ユニバーサルデザイン", yomi: "ゆにばーさるでざいん", eng: "Universal Design", desc_zh: "設計成所有人都能方便使用的產品。", desc_ja: "最初から誰でも使いやすく設計すること。" },
    { id: 294, cat: "技術管理", zh: "NDA", ja: "NDA", yomi: "えぬでぃーえー", eng: "NDA", desc_zh: "保密協定。", desc_ja: "秘密保持契約。" },
    { id: 295, cat: "技術管理", zh: "RFP", ja: "RFP", yomi: "あーるえふぴー", eng: "RFP", desc_zh: "建議書徵求文件，要求供應商提供提案。", desc_ja: "提案依頼書。ベンダに提案を求める文書。" },
    { id: 296, cat: "技術管理", zh: "RFI", ja: "RFI", yomi: "あーるえふあい", eng: "RFI", desc_zh: "資訊徵求文件，收集供應商的技術資訊。", desc_ja: "情報提供依頼書。技術情報を収集する。" },
    { id: 297, cat: "技術管理", zh: "PoC", ja: "PoC", yomi: "ぽっく", eng: "PoC", desc_zh: "概念驗證，測試新想法是否可行。", desc_ja: "概念実証。新しいアイデアの実現性を試す。" },
    { id: 298, cat: "技術管理", zh: "遊戲化", ja: "ゲーミフィケーション", yomi: "げーみふぃけーしょん", eng: "Gamification", desc_zh: "將遊戲元素應用於非遊戲領域。", desc_ja: "ゲームの要素を他分野に応用する。" },
    { id: 299, cat: "技術管理", zh: "SEO", ja: "SEO", yomi: "えすいーおー", eng: "SEO", desc_zh: "搜尋引擎最佳化，提升網站在搜尋結果的排名。", desc_ja: "検索エンジン最適化。" },
    { id: 300, cat: "技術管理", zh: "LBO", ja: "LBO", yomi: "えるびーおー", eng: "LBO", desc_zh: "槓桿收購，借錢來收購公司。", desc_ja: "買収先の資産を担保に資金を借りて買収。" },
    { id: 331, cat: "技術管理", zh: "M&A", ja: "M&A", yomi: "えむあんどえー", eng: "M&A", desc_zh: "企業合併與收購。", desc_ja: "企業の合併と買収。" },
    { id: 332, cat: "技術管理", zh: "IPO", ja: "IPO", yomi: "あいぴーおー", eng: "IPO", desc_zh: "首次公開發行股票 (上市)。", desc_ja: "新規株式公開。株を一般に売り出す。" },
    { id: 333, cat: "技術管理", zh: "TOB", ja: "TOB", yomi: "てぃーおーびー", eng: "TOB", desc_zh: "公開收購股票。", desc_ja: "株式公開買付け。" },
    { id: 334, cat: "技術管理", zh: "MBO", ja: "MBO", yomi: "えむびーおー", eng: "MBO", desc_zh: "管理層收購，經營陣容收購自家公司。", desc_ja: "経営陣による自社買収。" },
    { id: 335, cat: "技術管理", zh: "CEO", ja: "CEO", yomi: "しーいーおー", eng: "CEO", desc_zh: "執行長，最高經營負責人。", desc_ja: "最高経営責任者。" },
    { id: 336, cat: "技術管理", zh: "CIO", ja: "CIO", yomi: "しーあいおー", eng: "CIO", desc_zh: "資訊長，負責資訊系統策略。", desc_ja: "最高情報責任者。" },
    { id: 337, cat: "技術管理", zh: "CISO", ja: "CISO", yomi: "しーあいえすおー", eng: "CISO", desc_zh: "資安長，負責資訊安全。", desc_ja: "最高情報セキュリティ責任者。" },
    { id: 338, cat: "技術管理", zh: "COO", ja: "COO", yomi: "しーおーおー", eng: "COO", desc_zh: "營運長，負責公司日常營運。", desc_ja: "最高執行責任者。" },
    { id: 339, cat: "技術管理", zh: "CFO", ja: "CFO", yomi: "しーえふおー", eng: "CFO", desc_zh: "財務長，負責財務管理。", desc_ja: "最高財務責任者。" },
    { id: 340, cat: "技術管理", zh: "OJT", ja: "OJT", yomi: "おーじぇいてぃー", eng: "OJT", desc_zh: "在職訓練，透過實際工作進行培訓。", desc_ja: "職場内訓練。実務を通じた教育。" },
    { id: 341, cat: "技術管理", zh: "Off-JT", ja: "Off-JT", yomi: "おふじぇいてぃー", eng: "Off-JT", desc_zh: "職外訓練，暫離工作崗位進行研習。", desc_ja: "職場外訓練。仕事を離れて行う研修。" },
    { id: 342, cat: "技術管理", zh: "e-Learning", ja: "eラーニング", yomi: "いーらーにんぐ", eng: "e-Learning", desc_zh: "透過網路或電腦進行的學習。", desc_ja: "PCやネットを利用した学習。" },
    { id: 343, cat: "技術管理", zh: "HRTech", ja: "HRTech", yomi: "えいちあーるてっく", eng: "HRTech", desc_zh: "利用 IT 技術優化人資管理。", desc_ja: "ITを活用した人事管理。" },
    { id: 344, cat: "技術管理", zh: "FinTech", ja: "フィンテック", yomi: "ふぃんてっく", eng: "FinTech", desc_zh: "金融科技，利用 IT 創新金融服務。", desc_ja: "ITを活用した金融サービス。" },
    { id: 345, cat: "技術管理", zh: "EdTech", ja: "エドテック", yomi: "えどてっく", eng: "EdTech", desc_zh: "教育科技，利用 IT 創新教育。", desc_ja: "ITを活用した教育サービス。" },
    { id: 346, cat: "技術管理", zh: "BtoB", ja: "BtoB", yomi: "びーとぅーびー", eng: "BtoB", desc_zh: "企業對企業的交易。", desc_ja: "企業間取引。" },
    { id: 347, cat: "技術管理", zh: "BtoC", ja: "BtoC", yomi: "びーとぅーしー", eng: "BtoC", desc_zh: "企業對消費者的交易。", desc_ja: "企業と消費者間の取引。" },
    { id: 348, cat: "技術管理", zh: "CtoC", ja: "CtoC", yomi: "しーとぅーしー", eng: "CtoC", desc_zh: "消費者對消費者的交易 (如拍賣)。", desc_ja: "消費者間取引 (フリマ等)。" },
    { id: 349, cat: "技術管理", zh: "EC", ja: "EC", yomi: "いーしー", eng: "EC", desc_zh: "電子商務，網購。", desc_ja: "電子商取引。" },
    { id: 350, cat: "技術管理", zh: "SEO", ja: "SEO", yomi: "えすいーおー", eng: "SEO", desc_zh: "搜尋引擎最佳化。", desc_ja: "検索エンジン最適化。" },
    { id: 351, cat: "技術管理", zh: "SEM", ja: "SEM", yomi: "えすいーえむ", eng: "SEM", desc_zh: "搜尋引擎行銷 (包含 SEO 與關鍵字廣告)。", desc_ja: "検索エンジンマーケティング。" },
    { id: 352, cat: "技術管理", zh: "LTV", ja: "LTV", yomi: "えるてぃーぶい", eng: "LTV", desc_zh: "顧客終身價值。", desc_ja: "顧客生涯価値。" },
    { id: 353, cat: "技術管理", zh: "ROI", ja: "ROI", yomi: "あーるおーあい", eng: "ROI", desc_zh: "投資報酬率。", desc_ja: "投資対効果。" },
    { id: 354, cat: "技術管理", zh: "CPA", ja: "CPA", yomi: "しーぴーえー", eng: "CPA", desc_zh: "獲得一個新顧客的成本。", desc_ja: "顧客獲得単価。" },
    { id: 355, cat: "技術管理", zh: "KGI", ja: "KGI", yomi: "けーじーあい", eng: "KGI", desc_zh: "關鍵目標指標 (最終目標)。", desc_ja: "重要目標達成指標。" },
    { id: 356, cat: "技術管理", zh: "KPI", ja: "KPI", yomi: "けーぴーあい", eng: "KPI", desc_zh: "關鍵績效指標 (過程目標)。", desc_ja: "重要業績評価指標。" },
    { id: 357, cat: "技術管理", zh: "CSF", ja: "CSF", yomi: "しーえすえふ", eng: "CSF", desc_zh: "關鍵成功因素。", desc_ja: "重要成功要因。" },
    { id: 358, cat: "技術管理", zh: "PDCA", ja: "PDCA", yomi: "ぴーでぃーしーえー", eng: "PDCA", desc_zh: "品質管理的循環改善流程。", desc_ja: "計画・実行・評価・改善のサイクル。" },
    { id: 359, cat: "技術管理", zh: "OODA", ja: "OODA", yomi: "うーだ", eng: "OODA", desc_zh: "觀察-判斷-決策-行動的決策循環。", desc_ja: "観察・方向付・決定・行動のループ。" },
    { id: 360, cat: "技術管理", zh: "CRM", ja: "CRM", yomi: "しーあーるえむ", eng: "CRM", desc_zh: "客戶關係管理。", desc_ja: "顧客関係管理。" },
    { id: 361, cat: "技術管理", zh: "SFA", ja: "SFA", yomi: "えすえふえー", eng: "SFA", desc_zh: "業務支援系統，自動化銷售流程。", desc_ja: "営業支援システム。" },
    { id: 362, cat: "技術管理", zh: "ERP", ja: "ERP", yomi: "いーあーるぴー", eng: "ERP", desc_zh: "企業資源規劃。", desc_ja: "経営資源の統合管理。" },
    { id: 363, cat: "技術管理", zh: "SCM", ja: "SCM", yomi: "えすしーえむ", eng: "SCM", desc_zh: "供應鏈管理。", desc_ja: "供給連鎖管理。" },
    { id: 364, cat: "技術管理", zh: "PLM", ja: "PLM", yomi: "ぴーえるえむ", eng: "PLM", desc_zh: "產品生命週期管理。", desc_ja: "製品ライフサイクル管理。" },
    { id: 367, cat: "技術管理", zh: "JIT", ja: "JIT", yomi: "じゃすといんたいむ", eng: "JIT", desc_zh: "及時生產，零庫存管理。", desc_ja: "必要な物を必要な時に。在庫ゼロ。" },
    { id: 368, cat: "技術管理", zh: "FMS", ja: "FMS", yomi: "えふえむえす", eng: "FMS", desc_zh: "彈性製造系統，適應多品種少量生產。", desc_ja: "柔軟な生産システム。" },
    { id: 369, cat: "技術管理", zh: "MOT", ja: "MOT", yomi: "えむおーてぃー", eng: "MOT", desc_zh: "技術管理，將技術轉化為商業價值。", desc_ja: "技術経営。" },
    { id: 370, cat: "技術管理", zh: "TQC", ja: "TQC", yomi: "てぃーきゅーしー", eng: "TQC", desc_zh: "全公司品質管理。", desc_ja: "全社的品質管理。" },
    { id: 371, cat: "技術管理", zh: "ISO 9000", ja: "ISO 9000", yomi: "あいそきゅうせん", eng: "ISO 9000", desc_zh: "品質管理系統的國際標準。", desc_ja: "品質マネジメントシステム規格。" },
    { id: 372, cat: "技術管理", zh: "ISO 14000", ja: "ISO 14000", yomi: "あいそいちまんよんせん", eng: "ISO 14000", desc_zh: "環境管理系統的國際標準。", desc_ja: "環境マネジメントシステム規格。" },
    { id: 373, cat: "技術管理", zh: "ISO 27000", ja: "ISO 27000", yomi: "あいそにまんななせん", eng: "ISO 27000", desc_zh: "資訊安全管理系統 (ISMS) 的標準。", desc_ja: "情報セキュリティ管理規格。" },
    { id: 374, cat: "技術管理", zh: "JIS", ja: "JIS", yomi: "じす", eng: "JIS", desc_zh: "日本產業規格。", desc_ja: "日本産業規格。" },
    { id: 375, cat: "技術管理", zh: "JAN Code", ja: "JANコード", yomi: "じゃんこーど", eng: "JAN Code", desc_zh: "日本通用的商品條碼 (類似 EAN)。", desc_ja: "日本の共通商品コード (バーコード)。" },
    { id: 376, cat: "技術管理", zh: "QR Code", ja: "QRコード", yomi: "きゅーあーるこーど", eng: "QR Code", desc_zh: "二維條碼，可儲存更多資訊。", desc_ja: "二次元コード。大容量情報。" },
    { id: 377, cat: "技術管理", zh: "ISBN", ja: "ISBN", yomi: "あいえすびーえぬ", eng: "ISBN", desc_zh: "國際標準書號。", desc_ja: "国際標準図書番号。" },
    { id: 378, cat: "技術管理", zh: "Unicode", ja: "ユニコード", yomi: "ゆにこーど", eng: "Unicode", desc_zh: "萬國碼，包含世界各國文字的編碼。", desc_ja: "世界中の文字を扱う文字コード。" },
    { id: 379, cat: "技術管理", zh: "ASCII", ja: "アスキー", yomi: "あすきー", eng: "ASCII", desc_zh: "美國標準資訊交換碼 (英數符號)。", desc_ja: "英数字と記号の文字コード。" },
    { id: 380, cat: "技術管理", zh: "Shift-JIS", ja: "シフトJIS", yomi: "しふとじす", eng: "Shift-JIS", desc_zh: "日本常用的日文編碼格式。", desc_ja: "日本語の標準的な文字コード。" },
    { id: 381, cat: "技術管理", zh: "UTF-8", ja: "UTF-8", yomi: "ゆーてぃーえふはち", eng: "UTF-8", desc_zh: "Unicode 的一種編碼方式，網頁最常用。", desc_ja: "Webで最も使われる文字コード。" },
    { id: 382, cat: "技術管理", zh: "EUC-JP", ja: "EUC-JP", yomi: "いーゆーしーじぇいぴー", eng: "EUC-JP", desc_zh: "UNIX 系統常用的日文編碼。", desc_ja: "UNIX系で使われる日本語コード。" },
    { id: 383, cat: "技術管理", zh: "BCC", ja: "BCC", yomi: "びーしーしー", eng: "BCC", desc_zh: "密件副本，收件者看不到其他收件人。", desc_ja: "他の受信者に見えない宛先。" },
    { id: 384, cat: "技術管理", zh: "CC", ja: "CC", yomi: "しーしー", eng: "CC", desc_zh: "副本，知會其他收件人。", desc_ja: "複写。参考として送る宛先。" },
    { id: 385, cat: "技術管理", zh: "To", ja: "To", yomi: "とぅー", eng: "To", desc_zh: "主要收件人。", desc_ja: "主な宛先。" },
    { id: 386, cat: "技術管理", zh: "Subject", ja: "件名", yomi: "けんめい", eng: "Subject", desc_zh: "信件主旨。", desc_ja: "メールの題名。" },
    { id: 387, cat: "技術管理", zh: "Body", ja: "本文", yomi: "ほんぶん", eng: "Body", desc_zh: "信件內容。", desc_ja: "メールの内容。" },
    { id: 388, cat: "技術管理", zh: "Attachment", ja: "添付ファイル", yomi: "てんぷふぁいる", eng: "Attachment", desc_zh: "附件。", desc_ja: "一緒に送るファイル。" },
    { id: 389, cat: "技術管理", zh: "Sig", ja: "署名", yomi: "しょめい", eng: "Signature", desc_zh: "信末的簽名檔。", desc_ja: "メール末尾の署名。" },
    { id: 390, cat: "技術管理", zh: "Cookie", ja: "クッキー", yomi: "くっきー", eng: "Cookie", desc_zh: "瀏覽器儲存使用者資訊的小檔案。", desc_ja: "ブラウザに情報を保存する仕組み。" },
    { id: 391, cat: "技術管理", zh: "Cache", ja: "キャッシュ", yomi: "きゃっしゅ", eng: "Cache", desc_zh: "暫存檔，加速網頁載入。", desc_ja: "一時保存データ。読み込み高速化。" },
    { id: 392, cat: "技術管理", zh: "Session", ja: "セッション", yomi: "せっしょん", eng: "Session", desc_zh: "伺服器端紀錄使用者連線狀態的機制。", desc_ja: "一連の通信処理の状態管理。" },
    { id: 393, cat: "技術管理", zh: "Crawler", ja: "クローラ", yomi: "くろーら", eng: "Crawler", desc_zh: "搜尋引擎的爬蟲程式。", desc_ja: "検索エンジンの巡回プログラム。" },
    { id: 394, cat: "技術管理", zh: "Spider", ja: "スパイダー", yomi: "すぱいだー", eng: "Spider", desc_zh: "爬蟲程式的別稱。", desc_ja: "クローラの別名。" },
    { id: 395, cat: "技術管理", zh: "Algorithm", ja: "アルゴリズム", yomi: "あるごりずむ", eng: "Algorithm", desc_zh: "演算法，解決問題的步驟。", desc_ja: "問題を解決する手順。" },
    { id: 396, cat: "技術管理", zh: "Bug", ja: "バグ", yomi: "ばぐ", eng: "Bug", desc_zh: "程式錯誤。", desc_ja: "プログラムの不具合。" },
    { id: 397, cat: "技術管理", zh: "Debug", ja: "デバッグ", yomi: "でばっぐ", eng: "Debug", desc_zh: "除錯，修正程式錯誤。", desc_ja: "バグを修正する作業。" },
    { id: 398, cat: "技術管理", zh: "Patch", ja: "パッチ", yomi: "ぱっち", eng: "Patch", desc_zh: "修補程式。", desc_ja: "修正プログラム。" },
    { id: 399, cat: "技術管理", zh: "Version", ja: "バージョン", yomi: "ばーじょん", eng: "Version", desc_zh: "版本。", desc_ja: "版。" },
    { id: 400, cat: "技術管理", zh: "Release", ja: "リリース", yomi: "りりーす", eng: "Release", desc_zh: "發布軟體。", desc_ja: "ソフトを公開・発売すること。" },
// --- 新增：ID 401-500 (資安/網路/資料庫/財務) ---
    { id: 401, cat: "電腦系統", zh: "零時差攻擊", ja: "ゼロデイ攻撃", yomi: "ぜろでいこうげき", eng: "Zero-day Attack", desc_zh: "在軟體漏洞被發現但尚未修補前進行的攻擊。", desc_ja: "修正プログラムが公開される前の脆弱性を突く攻撃。" },
    { id: 402, cat: "電腦系統", zh: "緩衝區溢位", ja: "バッファオーバーフロー", yomi: "ばっふぁおーばーふろー", eng: "Buffer Overflow", desc_zh: "輸入超過記憶體預留空間的資料，導致系統崩潰或執行惡意碼。", desc_ja: "メモリ領域の上限を超えたデータを送りつける攻撃。" },
    { id: 403, cat: "電腦系統", zh: "中間人攻擊", ja: "中間者攻撃", yomi: "ちゅうかんしゃこうげき", eng: "Man-in-the-Middle Attack", desc_zh: "攻擊者介入通訊雙方之間，竊聽或竄改資料。", desc_ja: "通信する二者の間に割り込み、盗聴や改ざんを行う。" },
    { id: 404, cat: "電腦系統", zh: "重播攻擊", ja: "リプレイ攻撃", yomi: "りぷれいこうげき", eng: "Replay Attack", desc_zh: "攔截並重新發送有效的資料封包（如密碼）以欺騙系統。", desc_ja: "盗聴したデータを再送信し、正規の利用者になりすます。" },
    { id: 405, cat: "電腦系統", zh: "網頁掛馬", ja: "ドライブバイダウンロード", yomi: "どらいぶばいだうんろーど", eng: "Drive-by Download", desc_zh: "瀏覽惡意網頁時，自動在背景下載並執行病毒。", desc_ja: "Web閲覧だけでマルウェアを自動ダウンロードさせる攻撃。" },
    { id: 406, cat: "電腦系統", zh: "殭屍網路", ja: "ボットネット", yomi: "ぼっとねっと", eng: "Botnet", desc_zh: "被駭客控制的大量電腦群，常用於發動 DDoS。", desc_ja: "ウイルス感染し、遠隔操作される多数のPC群。" },
    { id: 407, cat: "電腦系統", zh: "間諜軟體", ja: "スパイウェア", yomi: "すぱいうぇあ", eng: "Spyware", desc_zh: "未經同意收集使用者資訊並傳送出去的軟體。", desc_ja: "ユーザーの情報を勝手に収集し送信するソフト。" },
    { id: 408, cat: "電腦系統", zh: "特洛伊木馬", ja: "トロイの木馬", yomi: "とろいのもくば", eng: "Trojan Horse", desc_zh: "偽裝成有用軟體，實際執行惡意行為，不具自我複製能力。", desc_ja: "無害を装って侵入し、悪意ある動作をする。自己増殖しない。" },
    { id: 409, cat: "電腦系統", zh: "蠕蟲", ja: "ワーム", yomi: "わーむ", eng: "Worm", desc_zh: "能自我複製並透過網路擴散的惡意程式。", desc_ja: "ネットワーク経由で自己増殖・感染拡大するプログラム。" },
    { id: 410, cat: "電腦系統", zh: "蜜罐", ja: "ハニーポット", yomi: "はにーぽっと", eng: "Honeypot", desc_zh: "故意設置漏洞誘捕駭客，以分析其攻擊手法。", desc_ja: "攻撃者を誘い込み、手法を分析するための囮システム。" },
    { id: 411, cat: "電腦系統", zh: "IDS", ja: "IDS", yomi: "あいでぃーえす", eng: "Intrusion Detection System", desc_zh: "入侵偵測系統，發現異常流量時發出警報。", desc_ja: "侵入検知システム。不正アクセスを検知し通知する。" },
    { id: 412, cat: "電腦系統", zh: "IPS", ja: "IPS", yomi: "あいぴーえす", eng: "Intrusion Prevention System", desc_zh: "入侵防禦系統，發現攻擊時會主動阻擋。", desc_ja: "侵入防止システム。攻撃を検知し遮断する。" },
    { id: 413, cat: "電腦系統", zh: "UTM", ja: "UTM", yomi: "ゆーてぃーえむ", eng: "Unified Threat Management", desc_zh: "整合式威脅管理，包含防火牆、防毒、VPN 等功能。", desc_ja: "統合脅威管理。FW、VPN、防毒などを一台に集約。" },
    { id: 414, cat: "電腦系統", zh: "SSO", ja: "シングルサインオン", yomi: "しんぐるさいんおん", eng: "Single Sign-On", desc_zh: "單一登入，只需登入一次即可存取多個系統。", desc_ja: "一度の認証で複数のシステムを利用できる仕組み。" },
    { id: 415, cat: "電腦系統", zh: "CAPTCHA", ja: "キャプチャ", yomi: "きゃぷちゃ", eng: "CAPTCHA", desc_zh: "區分人類與機器人的驗證機制（如圖形驗證碼）。", desc_ja: "人間かボットかを判別するテスト (文字認証など)。" },
    { id: 416, cat: "電腦系統", zh: "隱寫術", ja: "ステガノグラフィ", yomi: "すてがのぐらふぃ", eng: "Steganography", desc_zh: "將秘密資訊隱藏在圖片或音訊中。", desc_ja: "画像や音声データの中に秘密情報を隠す技術。" },
    { id: 417, cat: "電腦系統", zh: "肩窺", ja: "ショルダーハッキング", yomi: "しょるだーはっきんぐ", eng: "Shoulder Surfing", desc_zh: "偷看別人的螢幕或鍵盤輸入來竊取密碼。", desc_ja: "肩越しに画面やキー入力を盗み見る行為。" },
    { id: 418, cat: "電腦系統", zh: "負載平衡器", ja: "ロードバランサ", yomi: "ろーどばらんさ", eng: "Load Balancer", desc_zh: "將流量平均分配到多台伺服器，避免過載。", desc_ja: "負荷分散装置。アクセスを複数のサーバに振り分ける。" },
    { id: 419, cat: "電腦系統", zh: "鏡像站點", ja: "ミラーサイト", yomi: "みらーさいと", eng: "Mirror Site", desc_zh: "內容完全相同的複本網站，用於分流或備份。", desc_ja: "負荷分散のため、全く同じ内容で公開されたWebサイト。" },
    { id: 420, cat: "電腦系統", zh: "Web伺服器", ja: "Webサーバ", yomi: "うぇぶさーば", eng: "Web Server", desc_zh: "負責處理 HTTP 請求並回傳網頁的伺服器 (如 Apache, Nginx)。", desc_ja: "Webブラウザからの要求に応じページを表示するサーバ。" },
    { id: 421, cat: "電腦系統", zh: "應用程式伺服器", ja: "APサーバ", yomi: "えーぴーさーば", eng: "Application Server", desc_zh: "負責執行商業邏輯與程式運算的伺服器。", desc_ja: "業務ロジックの処理を行うサーバ (Java, PHP等)。" },
    { id: 422, cat: "電腦系統", zh: "三層式架構", ja: "3層クライアントサーバ", yomi: "さんそうくらいあんとさーば", eng: "3-Tier Architecture", desc_zh: "分為展示層、應用層、資料層的系統架構。", desc_ja: "プレゼンテーション、ファンクション、データベースの3層構造。" },
    { id: 423, cat: "電腦系統", zh: "詮釋資料", ja: "メタデータ", yomi: "めたでーた", eng: "Metadata", desc_zh: "描述資料的資料（如檔案的建立日期、作者）。", desc_ja: "データそのものを説明する属性情報。" },
    { id: 424, cat: "電腦系統", zh: "目錄服務", ja: "ディレクトリサービス", yomi: "でぃれくとりさーびす", eng: "Directory Service", desc_zh: "集中管理網路資源（使用者、電腦）的系統 (如 AD)。", desc_ja: "ネットワーク上の資源(ユーザ等)を一元管理する機能。" },
    { id: 425, cat: "電腦系統", zh: "網域", ja: "ドメイン", yomi: "どめいん", eng: "Domain", desc_zh: "網際網路上的地址名稱。", desc_ja: "インターネット上の住所にあたる名前。" },
    { id: 426, cat: "電腦系統", zh: "CMS", ja: "CMS", yomi: "しーえむえす", eng: "Content Management System", desc_zh: "內容管理系統，無需懂程式也能架設網站 (如 WordPress)。", desc_ja: "Webコンテンツを構成・管理するシステム。" },
    { id: 427, cat: "電腦系統", zh: "UX", ja: "UX", yomi: "ゆーえっくす", eng: "User Experience", desc_zh: "使用者體驗，用戶在使用產品過程中的感受。", desc_ja: "ユーザー体験。製品利用時の満足度や心地よさ。" },
    { id: 428, cat: "電腦系統", zh: "排他鎖", ja: "排他ロック", yomi: "はいたろっく", eng: "Exclusive Lock", desc_zh: "資料庫鎖定，完全禁止其他人讀取或寫入。", desc_ja: "他からの読み込みも書き込みも禁止するロック。" },
    { id: 429, cat: "電腦系統", zh: "共享鎖", ja: "共有ロック", yomi: "きょうゆうろっく", eng: "Shared Lock", desc_zh: "資料庫鎖定，允許他人讀取，但禁止寫入。", desc_ja: "他からの読み込みは許可し、書き込みは禁止する。" },
    { id: 430, cat: "電腦系統", zh: "兩階段鎖定", ja: "2相ロック", yomi: "にそうろっく", eng: "Two-Phase Locking (2PL)", desc_zh: "保證交易序列化的鎖定協定，分為增長與縮減階段。", desc_ja: "ロックの獲得と解放を2段階に分けて行う方式。" },
    { id: 431, cat: "電腦系統", zh: "檢查點", ja: "チェックポイント", yomi: "ちぇっくぽいんと", eng: "Checkpoint", desc_zh: "資料庫將記憶體資料寫入硬碟的同步點。", desc_ja: "メモリ上のデータをディスクに書き出す同期点。" },
    { id: 432, cat: "電腦系統", zh: "轉向前滾", ja: "ロールフォワード", yomi: "ろーるふぉわーど", eng: "Roll Forward", desc_zh: "利用備份與 Log 檔重做交易，恢復資料庫。", desc_ja: "バックアップ後のログを用いて処理を再現し復旧する。" },
    { id: 433, cat: "電腦系統", zh: "轉向後滾", ja: "ロールバック", yomi: "ろーるばっく", eng: "Rollback", desc_zh: "交易失敗時，取消變更回到原始狀態。", desc_ja: "処理失敗時、変更を取り消して元の状態に戻す。" },
    { id: 434, cat: "電腦系統", zh: "提交", ja: "コミット", yomi: "こみっと", eng: "Commit", desc_zh: "確認交易完成，將變更永久寫入資料庫。", desc_ja: "トランザクションの処理結果を確定させる。" },
    { id: 435, cat: "電腦系統", zh: "預存程序", ja: "ストアドプロシージャ", yomi: "すとあどぷろしーじゃ", eng: "Stored Procedure", desc_zh: "預先編譯並儲存在資料庫中的 SQL 程式。", desc_ja: "DB側に保存・実行される一連のSQLプログラム。" },
    { id: 436, cat: "電腦系統", zh: "觸發器", ja: "トリガー", yomi: "とりがー", eng: "Trigger", desc_zh: "當資料表發生變動時，自動執行的程式。", desc_ja: "データ変更時に自動的に実行される処理。" },
    { id: 437, cat: "電腦系統", zh: "視圖", ja: "ビュー", yomi: "びゅー", eng: "View", desc_zh: "虛擬表格，儲存的是查詢定義而非資料。", desc_ja: "特定の条件で抽出した仮想的な表。" },
    { id: 438, cat: "技術管理", zh: "GPL", ja: "GPL", yomi: "じーぴーえる", eng: "General Public License", desc_zh: "著名的開源授權，要求衍生作品也必須開源 (Copyleft)。", desc_ja: "コピーレフト性を持つ代表的なOSSライセンス。" },
    { id: 439, cat: "技術管理", zh: "BSD授權", ja: "BSDライセンス", yomi: "びーえすでぃー", eng: "BSD License", desc_zh: "寬鬆的開源授權，允許閉源商業使用。", desc_ja: "改変後の再頒布制限が緩いOSSライセンス。" },
    { id: 440, cat: "技術管理", zh: "共享軟體", ja: "シェアウェア", yomi: "しぇあうぇあ", eng: "Shareware", desc_zh: "可免費試用，但長期使用需付費的軟體。", desc_ja: "試用期間は無料だが、継続利用には料金が必要。" },
    { id: 441, cat: "技術管理", zh: "免費軟體", ja: "フリーウェア", yomi: "ふりーうぇあ", eng: "Freeware", desc_zh: "完全免費使用的軟體 (但不一定開源)。", desc_ja: "無償で利用できるソフトウェア。" },
    { id: 442, cat: "技術管理", zh: "流動資產", ja: "流動資産", yomi: "りゅうどうしさん", eng: "Current Assets", desc_zh: "一年內可變現的資產 (如現金、存貨)。", desc_ja: "1年以内に現金化できる資産 (現金、在庫等)。" },
    { id: 443, cat: "技術管理", zh: "固定資產", ja: "固定資産", yomi: "こていしさん", eng: "Fixed Assets", desc_zh: "長期持有供營運使用的資產 (如土地、設備)。", desc_ja: "長期にわたり保有・使用する資産 (土地、建物)。" },
    { id: 444, cat: "技術管理", zh: "自有資本", ja: "自己資本", yomi: "じこしほん", eng: "Equity / Net Assets", desc_zh: "股東出資與累積盈餘，不需償還。", desc_ja: "株主からの出資など、返済不要な資金。" },
    { id: 445, cat: "技術管理", zh: "折舊", ja: "減価償却", yomi: "げんかしょうきゃく", eng: "Depreciation", desc_zh: "將固定資產成本分攤到使用年限的會計處理。", desc_ja: "固定資産の購入費を耐用年数で分割計上すること。" },
    { id: 446, cat: "技術管理", zh: "現金流量表", ja: "キャッシュフロー計算書", yomi: "きゃっしゅふろー", eng: "Cash Flow Statement", desc_zh: "紀錄企業現金流入與流出的報表。", desc_ja: "現金の流れ（流入・流出）を表す財務諸表。" },
    { id: 447, cat: "技術管理", zh: "ROE", ja: "ROE", yomi: "あーるおーいー", eng: "Return on Equity", desc_zh: "股東權益報酬率，衡量利用自有資金獲利的能力。", desc_ja: "自己資本利益率。自己資本に対する利益の割合。" },
    { id: 448, cat: "技術管理", zh: "ROA", ja: "ROA", yomi: "あーるおーえー", eng: "Return on Assets", desc_zh: "總資產報酬率，衡量利用所有資產獲利的能力。", desc_ja: "総資産利益率。総資産に対する利益の割合。" },
    { id: 449, cat: "技術管理", zh: "變動成本", ja: "変動費", yomi: "へんどうひ", eng: "Variable Cost", desc_zh: "隨產量變動的成本 (如原料費)。", desc_ja: "売上や生産量に応じて増減する費用。" },
    { id: 450, cat: "技術管理", zh: "固定成本", ja: "固定費", yomi: "こていひ", eng: "Fixed Cost", desc_zh: "不隨產量變動的成本 (如房租、薪資)。", desc_ja: "売上に関わらず一定にかかる費用。" },
    { id: 451, cat: "技術管理", zh: "機會成本", ja: "機会費用", yomi: "きかいひよう", eng: "Opportunity Cost", desc_zh: "選擇某一方案而放棄其他方案所損失的潛在利益。", desc_ja: "ある選択をしたために放棄した利益。" },
    { id: 452, cat: "技術管理", zh: "沉沒成本", ja: "サンクコスト", yomi: "さんくこすと", eng: "Sunk Cost", desc_zh: "已經付出且無法回收的成本。", desc_ja: "既に支出され、回収不可能な費用。" },
    { id: 453, cat: "技術管理", zh: "規模經濟", ja: "規模の経済", yomi: "きぼのけいざい", eng: "Economies of Scale", desc_zh: "產量增加導致單位成本下降的現象。", desc_ja: "生産量が増えるほど単位コストが下がる効果。" },
    { id: 454, cat: "技術管理", zh: "範疇經濟", ja: "範囲の経済", yomi: "はんいのけいざい", eng: "Economies of Scope", desc_zh: "多樣化生產導致總成本下降的現象。", desc_ja: "多角化により、別々に事業を行うよりコストが下がる効果。" },
    { id: 455, cat: "基礎理論", zh: "流程圖", ja: "流れ図", yomi: "ながれず", eng: "Flowchart", desc_zh: "用圖形表示演算法或流程的圖表。", desc_ja: "処理の流れを図記号で表したもの。" },
    { id: 456, cat: "基礎理論", zh: "虛擬碼", ja: "擬似コード", yomi: "ぎじこーど", eng: "Pseudocode", desc_zh: "介於自然語言與程式碼之間的描述方式。", desc_ja: "自然言語に近い形式で書かれたコード。" },
    { id: 457, cat: "基礎理論", zh: "迴圈", ja: "ループ", yomi: "るーぷ", eng: "Loop", desc_zh: "重複執行某段程式碼的結構 (for, while)。", desc_ja: "繰り返し処理。" },
    { id: 458, cat: "基礎理論", zh: "變數", ja: "変数", yomi: "へんすう", eng: "Variable", desc_zh: "用於儲存資料的容器，數值可變。", desc_ja: "データを格納する箱。値は変更可能。" },
    { id: 459, cat: "基礎理論", zh: "常數", ja: "定数", yomi: "ていすう", eng: "Constant", desc_zh: "數值固定不可變更的變數。", desc_ja: "値が変更できない変数。" },
    { id: 460, cat: "基礎理論", zh: "引數", ja: "引数", yomi: "ひきすう", eng: "Argument", desc_zh: "傳遞給函數的參數。", desc_ja: "関数に渡す値。" },
    { id: 461, cat: "基礎理論", zh: "指標", ja: "ポインタ", yomi: "ぽいんた", eng: "Pointer", desc_zh: "儲存記憶體位址的變數。", desc_ja: "メモリ上のアドレスを格納する変数。" },
    { id: 462, cat: "基礎理論", zh: "例外處理", ja: "例外処理", yomi: "れいがいしょり", eng: "Exception Handling", desc_zh: "程式執行錯誤時的應對機制 (try-catch)。", desc_ja: "エラー発生時の対処を記述する仕組み。" },
    { id: 463, cat: "基礎理論", zh: "深度優先搜尋", ja: "深さ優先探索", yomi: "ふかさゆうせんたんさく", eng: "DFS", desc_zh: "盡可能深地搜索樹的分支。", desc_ja: "可能な限り深く探索を進めるアルゴリズム。" },
    { id: 464, cat: "基礎理論", zh: "廣度優先搜尋", ja: "幅優先探索", yomi: "はばゆうせんたんさく", eng: "BFS", desc_zh: "先搜索離根節點最近的節點。", desc_ja: "近いノードから順に探索するアルゴリズム。" },
    { id: 465, cat: "電腦系統", zh: "像素", ja: "画素", yomi: "がそ", eng: "Pixel", desc_zh: "構成數位影像的最小單位。", desc_ja: "デジタル画像を構成する最小単位。" },
    { id: 466, cat: "電腦系統", zh: "解析度", ja: "解像度", yomi: "かいぞうど", eng: "Resolution", desc_zh: "影像的精細程度。", desc_ja: "画像のきめ細かさ。" },
    { id: 467, cat: "電腦系統", zh: "dpi", ja: "dpi", yomi: "でぃーぴーあい", eng: "Dots Per Inch", desc_zh: "每英寸的點數，衡量列印解析度。", desc_ja: "1インチあたりのドット数。" },
    { id: 468, cat: "電腦系統", zh: "RGB", ja: "RGB", yomi: "あーるじーびー", eng: "RGB", desc_zh: "光的三原色 (紅綠藍)，用於螢幕顯示。", desc_ja: "光の三原色。モニタ表示用。" },
    { id: 469, cat: "電腦系統", zh: "CMYK", ja: "CMYK", yomi: "しーえむわいけー", eng: "CMYK", desc_zh: "印刷四分色模式 (青/洋紅/黃/黑)。", desc_ja: "印刷用の4色 (シアン/マゼンタ/イエロー/黒)。" },
    { id: 470, cat: "電腦系統", zh: "大數據 3V", ja: "ビッグデータ 3V", yomi: "さんぶい", eng: "3V of Big Data", desc_zh: "量(Volume)、速度(Velocity)、多樣性(Variety)。", desc_ja: "量、速度、多様性。" },
    { id: 471, cat: "電腦系統", zh: "網格運算", ja: "グリッドコンピューティング", yomi: "ぐりっどこんぴゅーてぃんぐ", eng: "Grid Computing", desc_zh: "結合多台電腦的計算能力來解決問題。", desc_ja: "複数コンピュータを連携させ計算能力を高める。" },
    { id: 472, cat: "電腦系統", zh: "P2P", ja: "P2P", yomi: "ぴーとぅーぴー", eng: "Peer-to-Peer", desc_zh: "電腦之間直接通訊，無中心伺服器。", desc_ja: "サーバを介さず端末同士で直接通信する。" },
    { id: 473, cat: "技術管理", zh: "勞動生產力", ja: "労働生産性", yomi: "ろうどうせいさんせい", eng: "Labor Productivity", desc_zh: "每位員工產出的附加價值。", desc_ja: "従業員一人当たりの付加価値額。" },
    { id: 474, cat: "技術管理", zh: "庫存週轉率", ja: "在庫回転率", yomi: "ざいこかいてんりつ", eng: "Inventory Turnover", desc_zh: "庫存在一定期間內銷售出去的次數。", desc_ja: "在庫がどれだけ効率よく売れたかの指標。" },
    { id: 475, cat: "技術管理", zh: "應收帳款", ja: "売掛金", yomi: "うりかけきん", eng: "Accounts Receivable", desc_zh: "賒銷商品後，尚未收回的款項。", desc_ja: "商品販売後、まだ回収していない代金。" },
    { id: 476, cat: "技術管理", zh: "應付帳款", ja: "買掛金", yomi: "かいかけきん", eng: "Accounts Payable", desc_zh: "賒購商品後，尚未支付的款項。", desc_ja: "商品購入後、まだ支払っていない代金。" },
    { id: 477, cat: "電腦系統", zh: "藍光", ja: "ブルーレイ", yomi: "ぶるーれい", eng: "Blu-ray Disc", desc_zh: "高容量光碟儲存格式。", desc_ja: "大容量光ディスク規格。" },
    { id: 478, cat: "基礎理論", zh: "批次檔", ja: "バッチファイル", yomi: "ばっちふぁいる", eng: "Batch File", desc_zh: "包含一系列指令的文字檔。", desc_ja: "一連のコマンドを記述したファイル。" },
    { id: 479, cat: "電腦系統", zh: "核心", ja: "カーネル", yomi: "かーねる", eng: "Kernel", desc_zh: "作業系統的核心部分，管理硬體。", desc_ja: "OSの中核部分。ハードウェアを管理。" },
    { id: 480, cat: "電腦系統", zh: "Shell", ja: "シェル", yomi: "しぇる", eng: "Shell", desc_zh: "接收使用者指令並傳給核心的介面。", desc_ja: "ユーザーの命令を解釈しカーネルに伝える。" },
    { id: 481, cat: "技術管理", zh: "供應鏈", ja: "サプライチェーン", yomi: "さぷらいちぇーん", eng: "Supply Chain", desc_zh: "從原物料到最終產品送達消費者的流程。", desc_ja: "原材料調達から消費者に届くまでの流れ。" },
    { id: 482, cat: "技術管理", zh: "利害關係人", ja: "ステークホルダー", yomi: "すてーくほるだー", eng: "Stakeholder", desc_zh: "與企業或專案有利益關係的個人或團體。", desc_ja: "企業活動に関わる利害関係者。" },
    { id: 483, cat: "技術管理", zh: "合規性", ja: "コンプライアンス", yomi: "こんぷらいあんす", eng: "Compliance", desc_zh: "遵守法律法規與企業倫理。", desc_ja: "法令遵守。" },
    { id: 484, cat: "技術管理", zh: "治理", ja: "ガバナンス", yomi: "がばなんす", eng: "Governance", desc_zh: "企業的統治與管理機制。", desc_ja: "企業統治。健全な経営のための管理体制。" },
    { id: 485, cat: "技術管理", zh: "基準測試", ja: "ベンチマーク", yomi: "べんちまーく", eng: "Benchmark", desc_zh: "測量軟硬體效能的標準測試。", desc_ja: "性能を測定・比較するための指標。" },
    { id: 486, cat: "技術管理", zh: "最佳實務", ja: "ベストプラクティス", yomi: "べすとぷらくてぃす", eng: "Best Practice", desc_zh: "業界公認最有效率、最成功的做法。", desc_ja: "最も効率的・効果的な実践方法。" },
    { id: 487, cat: "技術管理", zh: "腦力激盪", ja: "ブレインストーミング", yomi: "ぶれーんすとーみんぐ", eng: "Brainstorming", desc_zh: "集體自由發想創意的討論法。", desc_ja: "集団で自由にアイデアを出し合う会議手法。" },
    { id: 488, cat: "技術管理", zh: "決策樹", ja: "決定木", yomi: "けっていぎ", eng: "Decision Tree", desc_zh: "用樹狀圖分析決策與可能結果。", desc_ja: "意思決定の流れを樹形図で表したもの。" },
    { id: 489, cat: "技術管理", zh: "專案章程", ja: "プロジェクト憲章", yomi: "ぷろじぇくとけんしょう", eng: "Project Charter", desc_zh: "正式授權專案成立的文件。", desc_ja: "プロジェクトの立ち上げを正式に許可する文書。" },
    { id: 490, cat: "技術管理", zh: "利潤", ja: "利益", yomi: "りえき", eng: "Profit", desc_zh: "收入減去成本。", desc_ja: "売上から費用を引いたもの。" },
    { id: 491, cat: "技術管理", zh: "毛利", ja: "粗利", yomi: "あらり", eng: "Gross Profit", desc_zh: "銷貨收入減去銷貨成本。", desc_ja: "売上高から売上原価を引いた利益。" },
    { id: 492, cat: "技術管理", zh: "淨利", ja: "純利益", yomi: "じゅんりえき", eng: "Net Profit", desc_zh: "扣除所有稅金與費用後的最終利潤。", desc_ja: "全ての費用と税金を引いた最終的な利益。" },
    { id: 493, cat: "電腦系統", zh: "虛擬機器", ja: "仮想マシン", yomi: "かそうましん", eng: "Virtual Machine", desc_zh: "在電腦中模擬出的另一台電腦系統。", desc_ja: "コンピュータ内で仮想的に構築されたPC。" },
    { id: 494, cat: "電腦系統", zh: "容器", ja: "コンテナ", yomi: "こんてな", eng: "Container", desc_zh: "輕量級的虛擬化技術 (如 Docker)。", desc_ja: "OS上でアプリを隔離して実行する技術。" },
    { id: 495, cat: "電腦系統", zh: "伺服器", ja: "サーバ", yomi: "さーば", eng: "Server", desc_zh: "提供服務給其他電腦 (客戶端) 的電腦。", desc_ja: "サービスを提供する側のコンピュータ。" },
    { id: 496, cat: "電腦系統", zh: "客戶端", ja: "クライアント", yomi: "くらいあんと", eng: "Client", desc_zh: "請求服務的電腦或軟體。", desc_ja: "サービスを受ける側のコンピュータ。" },
    { id: 497, cat: "電腦系統", zh: "頻寬", ja: "帯域幅", yomi: "たいいきはば", eng: "Bandwidth", desc_zh: "網路傳輸資料的能力。", desc_ja: "通信回線のデータ転送能力。" },
    { id: 498, cat: "電腦系統", zh: "延遲", ja: "レイテンシ", yomi: "れいてんし", eng: "Latency", desc_zh: "資料傳輸的延遲時間。", desc_ja: "データ転送の遅延時間。" },
    { id: 499, cat: "電腦系統", zh: "回應", ja: "レスポンス", yomi: "れすぽんす", eng: "Response", desc_zh: "系統對請求的回覆。", desc_ja: "要求に対する応答。" },
    { id: 500, cat: "電腦系統", zh: "請求", ja: "リクエスト", yomi: "りくえすと", eng: "Request", desc_zh: "向系統發出的要求。", desc_ja: "システムへの要求。" }
];
