const questionData = [
    // --- (1-250 題保持不變，以下包含所有題目) ---
    { id: 1, cat: "基礎理論", zh: "位元", ja: "ビット", yomi: "びっと", eng: "Bit", desc_zh: "最小的資訊單位，只能表示 0 或 1。", desc_ja: "情報の最小単位。0 または 1 のいずれかを表します。" },
    { id: 2, cat: "基礎理論", zh: "位元組", ja: "バイト", yomi: "ばいと", eng: "Byte", desc_zh: "由 8 個位元組成，通常用來表示一個字元。", desc_ja: "8ビットから構成され、通常、1文字を表す単位です。" },
    { id: 3, cat: "基礎理論", zh: "二進位", ja: "2進数", yomi: "にしんすう", eng: "Binary Number", desc_zh: "僅使用 0 和 1 來表示數值的系統。", desc_ja: "0 と 1 のみを用いて数を表現する方法。" },
    { id: 4, cat: "基礎理論", zh: "二補數", ja: "2の補数", yomi: "にのほすう", eng: "Two's Complement", desc_zh: "在電腦中表示負數的方法。", desc_ja: "コンピュータで負の数を表現する方法。" },
    { id: 5, cat: "基礎理論", zh: "浮點數", ja: "浮動小数点", yomi: "ふどうしょうすうてん", eng: "Floating Point", desc_zh: "用於表示實數，由符號、指數、尾數組成。", desc_ja: "実数を表現する方式。符号、指数、仮数からなる。" },
    { id: 6, cat: "基礎理論", zh: "捨位誤差", ja: "丸め誤差", yomi: "まるめごさ", eng: "Rounding Error", desc_zh: "因位數有限，四雪五入或無條件捨去導致的計算誤差。", desc_ja: "桁数制限により、四捨五入や切り捨てで生じる計算誤差。" },
    { id: 7, cat: "基礎理論", zh: "AND 閘", ja: "AND ゲート", yomi: "あんどげーと", eng: "AND Gate", desc_zh: "邏輯乘。所有輸入為 1 時，輸出才為 1。", desc_ja: "論理積。全ての入力が 1 の時のみ、出力が 1 となる。" },
    { id: 8, cat: "基礎理論", zh: "OR 閘", ja: "OR ゲート", yomi: "おあげーと", eng: "OR Gate", desc_zh: "邏輯和。任一輸入為 1 時，輸出即為 1。", desc_ja: "論理和。いずれかの入力が 1 の時、出力が 1 となる。" },
    { id: 9, cat: "基礎理論", zh: "XOR 閘", ja: "排他的論理和", yomi: "はいたてきろんりわ", eng: "Exclusive OR (XOR)", desc_zh: "當兩個輸入不同時，輸出為 1。", desc_ja: "2つの入力が異なるときのみ、出力が 1 となる。" },
    { id: 10, cat: "基礎理論", zh: "資訊量", ja: "情報量", yomi: "じょうほうりょう", eng: "Information Amount", desc_zh: "事件發生機率越低，資訊量越大。", desc_ja: "事象の発生確率が低いほど、情報量は大きくなる。" },
    { id: 11, cat: "電腦系統", zh: "馮·諾伊曼架構", ja: "ノイマン型", yomi: "のいまんがた", eng: "Von Neumann", desc_zh: "程式內建方式，指令和資料都存在記憶體中。", desc_ja: "命令とデータがメモリに格納される方式。" },
    { id: 12, cat: "電腦系統", zh: "CPU", ja: "中央処理装置", yomi: "ちゅうおうしょりそうち", eng: "CPU", desc_zh: "負責執行指令與運算。", desc_ja: "命令の実行と演算を行う。" },
    { id: 13, cat: "電腦系統", zh: "快取記憶體", ja: "キャッシュメモリ", yomi: "きゃっしゅめもり", eng: "Cache", desc_zh: "位於 CPU 與 RAM 之間，加速資料存取。", desc_ja: "CPUとRAMの間にあり高速化する。" },
    { id: 14, cat: "電腦系統", zh: "RAM", ja: "RAM", yomi: "らむ", eng: "RAM", desc_zh: "揮發性記憶體，電源關閉後資料消失。", desc_ja: "電源を切るとデータが消える揮発性メモリ。" },
    { id: 15, cat: "電腦系統", zh: "ROM", ja: "ROM", yomi: "ろむ", eng: "ROM", desc_zh: "非揮發性記憶體，儲存 BIOS 等。", desc_ja: "不揮発性メモリ。BIOS等を保存。" },
    { id: 16, cat: "電腦系統", zh: "虛擬記憶體", ja: "仮想記憶", yomi: "かそうきおく", eng: "Virtual Memory", desc_zh: "將硬碟當作記憶體使用。", desc_ja: "HDDをメモリの一部として扱う技術。" },
    { id: 17, cat: "電腦系統", zh: "RAID 0", ja: "ストライピング", yomi: "すとらいぴんぐ", eng: "Striping", desc_zh: "資料分散寫入，速度快但無容錯。", desc_ja: "分散書き込み。高速だが耐障害性なし。" },
    { id: 18, cat: "電腦系統", zh: "RAID 1", ja: "ミラーリング", yomi: "みらーりんぐ", eng: "Mirroring", desc_zh: "資料完整複製到兩顆硬碟。", desc_ja: "複製書き込み。信頼性が高い。" },
    { id: 19, cat: "電腦系統", zh: "RAID 5", ja: "RAID 5", yomi: "れーどふぁいぶ", eng: "RAID 5", desc_zh: "分散寫入資料與同位檢查碼。", desc_ja: "データとパリティを分散書き込み。" },
    { id: 20, cat: "電腦系統", zh: "RDB", ja: "リレーショナルDB", yomi: "りれーしょなるでーたべーす", eng: "Relational Database", desc_zh: "關聯式資料庫，以表格形式管理資料。", desc_ja: "データを表形式で管理するデータベース。" },
    { id: 21, cat: "電腦系統", zh: "SQL", ja: "SQL", yomi: "えすきゅーえる", eng: "Structured Query Language", desc_zh: "操作資料庫的標準語言。", desc_ja: "データベースを操作する標準言語。" },
    { id: 22, cat: "電腦系統", zh: "正規化", ja: "正規化", yomi: "せいきか", eng: "Normalization", desc_zh: "消除資料重複與異常的過程。", desc_ja: "データの重複や矛盾を排除するプロセス。" },
    { id: 23, cat: "電腦系統", zh: "ACID特性", ja: "ACID特性", yomi: "あしっどとくせい", eng: "ACID Properties", desc_zh: "確保交易可靠性的四個特性(原子/一致/隔離/持久)。", desc_ja: "トランザクションの信頼性を保証する4つの性質。" },
    { id: 24, cat: "電腦系統", zh: "交易", ja: "トランザクション", yomi: "とらんざくしょん", eng: "Transaction", desc_zh: "一組不可分割的資料庫操作單元。", desc_ja: "分割できない一連のデータベース処理単位。" },
    { id: 25, cat: "電腦系統", zh: "OSI模型", ja: "OSI参照モデル", yomi: "おーえすあい", eng: "OSI Model", desc_zh: "通訊7層模型。", desc_ja: "通信の7階層モデル。" },
    { id: 26, cat: "電腦系統", zh: "TCP/IP", ja: "TCP/IP", yomi: "てぃーしーぴー", eng: "TCP/IP", desc_zh: "網際網路標準協定。", desc_ja: "ネットの標準プロトコル。" },
    { id: 27, cat: "電腦系統", zh: "IP地址", ja: "IPアドレス", yomi: "あいぴーあどれす", eng: "IP Address", desc_zh: "網路邏輯位址。", desc_ja: "ネット上の住所。" },
    { id: 28, cat: "電腦系統", zh: "MAC地址", ja: "MACアドレス", yomi: "まっくあどれす", eng: "MAC Address", desc_zh: "硬體實體位址。", desc_ja: "機器の物理アドレス。" },
    { id: 29, cat: "電腦系統", zh: "DHCP", ja: "DHCP", yomi: "でぃーえいちしーぴー", eng: "DHCP", desc_zh: "自動分配 IP。", desc_ja: "IP自動割り当て。" },
    { id: 30, cat: "電腦系統", zh: "NAT", ja: "NAT", yomi: "なっと", eng: "NAT", desc_zh: "轉換私有與公共 IP。", desc_ja: "IPアドレス変換。" },
    { id: 31, cat: "電腦系統", zh: "公開金鑰加密", ja: "公開鍵暗号", yomi: "こうかいかぎあんごう", eng: "Public Key", desc_zh: "雙鑰匙：公鑰加密，私鑰解密。", desc_ja: "2つの鍵。公開鍵で暗号化、秘密鍵で復号。" },
    { id: 32, cat: "電腦系統", zh: "共通金鑰加密", ja: "共通鍵暗号", yomi: "きょうつうかぎあんごう", eng: "Symmetric Key", desc_zh: "單鑰匙：加密解密用同一把。", desc_ja: "1つの鍵。暗号化と復号が同じ。" },
    { id: 33, cat: "電腦系統", zh: "數位簽章", ja: "デジタル署名", yomi: "でじたるしょめい", eng: "Digital Signature", desc_zh: "防竄改與確認身分。", desc_ja: "改ざん検知と本人確認。" },
    { id: 34, cat: "技術管理", zh: "瀑布模型", ja: "ウォーターフォール", yomi: "うぉーたーふぉーる", eng: "Waterfall", desc_zh: "按順序開發，不回頭。", desc_ja: "順序通り進める開発。" },
    { id: 35, cat: "技術管理", zh: "敏捷開發", ja: "アジャイル", yomi: "あじゃいる", eng: "Agile", desc_zh: "短週期反覆開發。", desc_ja: "短期間の反復開発。" },
    { id: 36, cat: "技術管理", zh: "WBS", ja: "WBS", yomi: "だぶりゅーびーえす", eng: "WBS", desc_zh: "工作分解結構。", desc_ja: "作業分解図。" },
    { id: 37, cat: "技術管理", zh: "關鍵路徑", ja: "クリティカルパス", yomi: "くりてぃかるぱす", eng: "Critical Path", desc_zh: "最長路徑，決定工期。", desc_ja: "最長経路。" },
    { id: 38, cat: "技術管理", zh: "EVM", ja: "EVM", yomi: "いーぶいえむ", eng: "EVM", desc_zh: "用金額管理進度。", desc_ja: "金額で進捗管理。" },
    { id: 39, cat: "技術管理", zh: "SLA", ja: "SLA", yomi: "えすえるえー", eng: "SLA", desc_zh: "服務層級協定，品質保證。", desc_ja: "サービス品質の保証。" },
    { id: 40, cat: "技術管理", zh: "MTBF", ja: "MTBF", yomi: "えむてぃーびーえふ", eng: "MTBF", desc_zh: "平均無故障時間 (可靠性)。", desc_ja: "平均故障間隔 (信頼性)。" },
    { id: 41, cat: "技術管理", zh: "MTTR", ja: "MTTR", yomi: "えむてぃーてぃーあーる", eng: "MTTR", desc_zh: "平均修復時間 (可維護性)。", desc_ja: "平均修復時間 (保守性)。" },
    { id: 42, cat: "技術管理", zh: "稼動率", ja: "稼働率", yomi: "かどうりつ", eng: "Availability Rate", desc_zh: "系統正常運作時間的比例。", desc_ja: "システムが動作している割合。" },
    { id: 43, cat: "技術管理", zh: "SWOT分析", ja: "SWOT分析", yomi: "すうぉっとぶんせき", eng: "SWOT Analysis", desc_zh: "分析優勢、劣勢、機會、威脅。", desc_ja: "強み、弱み、機会、脅威を分析。" },
    { id: 44, cat: "技術管理", zh: "BPR", ja: "BPR", yomi: "びーぴーあーる", eng: "BPR", desc_zh: "業務流程重組。", desc_ja: "業務プロセスの抜本的改革。" },
    { id: 45, cat: "技術管理", zh: "CRM", ja: "CRM", yomi: "しーあーるえむ", eng: "CRM", desc_zh: "客戶關係管理。", desc_ja: "顧客関係管理。" },
    { id: 46, cat: "技術管理", zh: "BCP", ja: "BCP", yomi: "びーしーぴー", eng: "BCP", desc_zh: "業務連續性計畫 (防災)。", desc_ja: "事業継続計画。" },
    { id: 47, cat: "技術管理", zh: "核心能力", ja: "コアコンピタンス", yomi: "こあこんぴたんす", eng: "Core Competence", desc_zh: "企業的核心競爭優勢。", desc_ja: "競合他社に真似できない強み。" },
    { id: 48, cat: "技術管理", zh: "KPI", ja: "KPI", yomi: "けーぴーあい", eng: "KPI", desc_zh: "關鍵績效指標。", desc_ja: "重要業績評価指標。" },
    { id: 49, cat: "技術管理", zh: "IoT", ja: "IoT", yomi: "あいおーてぃー", eng: "IoT", desc_zh: "物聯網。", desc_ja: "モノのインターネット。" },
    { id: 50, cat: "技術管理", zh: "DX", ja: "DX", yomi: "でぃーえっくす", eng: "DX", desc_zh: "數位轉型。", desc_ja: "デジタル変革。" },
    { id: 51, cat: "基礎理論", zh: "堆疊", ja: "スタック", yomi: "すたっく", eng: "Stack", desc_zh: "後進先出 (LIFO) 的資料結構。", desc_ja: "後入れ先出し (LIFO) のデータ構造。" },
    { id: 52, cat: "基礎理論", zh: "佇列", ja: "キュー", yomi: "きゅー", eng: "Queue", desc_zh: "先進先出 (FIFO) 的資料結構。", desc_ja: "先入れ先出し (FIFO) のデータ構造。" },
    { id: 53, cat: "基礎理論", zh: "陣列", ja: "配列", yomi: "はいれつ", eng: "Array", desc_zh: "相同類型的資料連續排列的結構。", desc_ja: "同じ型のデータを連続的に並べた構造。" },
    { id: 54, cat: "基礎理論", zh: "連結串列", ja: "連結リスト", yomi: "れんけつりすと", eng: "Linked List", desc_zh: "資料包含指向下一個資料位址的結構。", desc_ja: "データが次のデータの場所を指し示す構造。" },
    { id: 55, cat: "基礎理論", zh: "二元樹", ja: "二分木", yomi: "にぶんぎ", eng: "Binary Tree", desc_zh: "每個節點最多有兩個子節點的樹狀結構。", desc_ja: "各ノードが最大2つの子を持つ木構造。" },
    { id: 56, cat: "基礎理論", zh: "線性搜尋", ja: "線形探索", yomi: "せんけいたんさく", eng: "Linear Search", desc_zh: "從頭開始依序尋找資料的方法。", desc_ja: "先頭から順にデータを探す方法。" },
    { id: 57, cat: "基礎理論", zh: "二分搜尋", ja: "二分探索", yomi: "にぶんたんさく", eng: "Binary Search", desc_zh: "在已排序的資料中，反覆將範圍減半來搜尋。", desc_ja: "整列済みデータの中央を見て、範囲を半分に絞る探索法。" },
    { id: 58, cat: "基礎理論", zh: "雜湊法", ja: "ハッシュ法", yomi: "はっしゅほう", eng: "Hashing", desc_zh: "利用函數計算儲存位置，實現快速存取。", desc_ja: "関数で格納場所を計算し、高速アクセスを実現する。" },
    { id: 59, cat: "基礎理論", zh: "氣泡排序", ja: "バブルソート", yomi: "ばぶるそーと", eng: "Bubble Sort", desc_zh: "重複交換相鄰元素以進行排序。", desc_ja: "隣り合う要素を交換しながら整列する。" },
    { id: 60, cat: "基礎理論", zh: "快速排序", ja: "クイックソート", yomi: "くいっくそーと", eng: "Quick Sort", desc_zh: "選定基準值分割資料的高速排序法。", desc_ja: "基準値を決めてデータを分割する高速な整列法。" },
    { id: 61, cat: "電腦系統", zh: "GPU", ja: "GPU", yomi: "じーぴーゆー", eng: "GPU", desc_zh: "圖形處理器，擅長並行運算 (如 AI、圖像)。", desc_ja: "画像処理装置。並列処理（AI、画像）が得意。" },
    { id: 62, cat: "電腦系統", zh: "SSD", ja: "SSD", yomi: "えすえすでぃー", eng: "SSD", desc_zh: "使用快閃記憶體的儲存裝置，速度比 HDD 快。", desc_ja: "フラッシュメモリを使った記憶装置。HDDより高速。" },
    { id: 63, cat: "電腦系統", zh: "RFID", ja: "RFID", yomi: "あーるえふあいでぃー", eng: "RFID", desc_zh: "使用無線電波進行非接觸式資料讀寫的技術 (如 IC 卡)。", desc_ja: "電波を用いた非接触データ読み書き技術 (ICカード等)。" },
    { id: 64, cat: "電腦系統", zh: "NFC", ja: "NFC", yomi: "えぬえふしー", eng: "NFC", desc_zh: "近距離無線通訊技術 (如手機支付)。", desc_ja: "近距離無線通信技術 (スマホ決済など)。" },
    { id: 65, cat: "電腦系統", zh: "OCR", ja: "OCR", yomi: "おーしーあーる", eng: "OCR", desc_zh: "光學字元辨識，將圖片中的文字轉換為文字資料。", desc_ja: "画像内の文字をテキストデータに変換する技術。" },
    { id: 66, cat: "電腦系統", zh: "OSS", ja: "OSS", yomi: "おーえすえす", eng: "OSS", desc_zh: "開放原始碼軟體，原始碼公開且可自由修改。", desc_ja: "ソースコードが公開され、自由に修正可能なソフト。" },
    { id: 67, cat: "電腦系統", zh: "BIOS", ja: "BIOS", yomi: "ばいおす", eng: "BIOS", desc_zh: "電腦啟動時最先執行的程式，控制硬體。", desc_ja: "起動時に最初に実行され、ハードウェアを制御する。" },
    { id: 68, cat: "電腦系統", zh: "中介軟體", ja: "ミドルウェア", yomi: "みどるうぇあ", eng: "Middleware", desc_zh: "位於 OS 和應用程式之間，提供共通功能的軟體。", desc_ja: "OSとアプリの間にあり、共通機能を提供するソフト。" },
    { id: 69, cat: "電腦系統", zh: "API", ja: "API", yomi: "えーぴーあい", eng: "API", desc_zh: "讓軟體之間交換功能或資料的介面。", desc_ja: "ソフト同士が機能やデータをやり取りする窓口。" },
    { id: 70, cat: "電腦系統", zh: "批次處理", ja: "バッチ処理", yomi: "ばっちしょり", eng: "Batch Processing", desc_zh: "累積一定量的資料後，一次性進行處理。", desc_ja: "データを一定量ためてから一括で処理する方式。" },
    { id: 71, cat: "電腦系統", zh: "即時處理", ja: "リアルタイム処理", yomi: "りあるたいむしょり", eng: "Real-time", desc_zh: "資料產生時立即進行處理。", desc_ja: "データ発生時に即座に処理を行う方式。" },
    { id: 72, cat: "電腦系統", zh: "備份", ja: "バックアップ", yomi: "ばっくあっぷ", eng: "Backup", desc_zh: "複製資料以防遺失。", desc_ja: "データ消失に備えて複製をとること。" },
    { id: 73, cat: "電腦系統", zh: "完整備份", ja: "フルバックアップ", yomi: "ふるばっくあっぷ", eng: "Full Backup", desc_zh: "備份所有資料。", desc_ja: "全てのデータをバックアップする。" },
    { id: 74, cat: "電腦系統", zh: "差異備份", ja: "差分バックアップ", yomi: "さぶんばっくあっぷ", eng: "Differential", desc_zh: "備份自上次「完整備份」以來變更的資料。", desc_ja: "前回の「フルバックアップ」からの変更分を保存。" },
    { id: 75, cat: "電腦系統", zh: "增量備份", ja: "増分バックアップ", yomi: "ぞうぶんばっくあっぷ", eng: "Incremental", desc_zh: "備份自上次「任何備份」以來變更的資料。", desc_ja: "前回の「バックアップ」からの変更分のみ保存。" },
    { id: 76, cat: "電腦系統", zh: "主鍵", ja: "主キー", yomi: "しゅきー", eng: "Primary Key", desc_zh: "唯一識別表格中每一筆記錄的欄位。", desc_ja: "行を一意に識別するための列。" },
    { id: 77, cat: "電腦系統", zh: "外鍵", ja: "外部キー", yomi: "がいぶきー", eng: "Foreign Key", desc_zh: "用來關聯其他表格的欄位。", desc_ja: "他の表を参照するための列。" },
    { id: 78, cat: "電腦系統", zh: "SELECT", ja: "SELECT", yomi: "せれくと", eng: "SELECT", desc_zh: "SQL指令：查詢資料。", desc_ja: "SQL命令：データを検索する。" },
    { id: 79, cat: "電腦系統", zh: "INSERT", ja: "INSERT", yomi: "いんさーと", eng: "INSERT", desc_zh: "SQL指令：新增資料。", desc_ja: "SQL命令：データを追加する。" },
    { id: 80, cat: "電腦系統", zh: "UPDATE", ja: "UPDATE", yomi: "あっぷでーと", eng: "UPDATE", desc_zh: "SQL指令：更新資料。", desc_ja: "SQL命令：データを更新する。" },
    { id: 81, cat: "電腦系統", zh: "DNS", ja: "DNS", yomi: "でぃーえぬえす", eng: "DNS", desc_zh: "將網域名稱轉換為 IP 地址的系統。", desc_ja: "ドメイン名をIPアドレスに変換するシステム。" },
    { id: 82, cat: "電腦系統", zh: "HTTP", ja: "HTTP", yomi: "えいちてぃーてぃーぴー", eng: "HTTP", desc_zh: "網頁瀏覽器與伺服器之間的傳輸協定。", desc_ja: "Webブラウザとサーバ間の通信プロトコル。" },
    { id: 83, cat: "電腦系統", zh: "SMTP", ja: "SMTP", yomi: "えすえむてぃーぴー", eng: "SMTP", desc_zh: "發送電子郵件的協定。", desc_ja: "メールを送信するプロトコル。" },
    { id: 84, cat: "電腦系統", zh: "POP3", ja: "POP3", yomi: "ぽっぷすりー", eng: "POP3", desc_zh: "接收電子郵件的協定 (下載後從伺服器刪除)。", desc_ja: "メールを受信するプロトコル (DLしてサーバから削除)。" },
    { id: 85, cat: "電腦系統", zh: "IMAP", ja: "IMAP", yomi: "あいまっぷ", eng: "IMAP", desc_zh: "在伺服器上管理郵件的接收協定。", desc_ja: "サーバ上でメールを管理する受信プロトコル。" },
    { id: 86, cat: "電腦系統", zh: "FTP", ja: "FTP", yomi: "えふてぃーぴー", eng: "FTP", desc_zh: "檔案傳輸協定。", desc_ja: "ファイルを転送するプロトコル。" },
    { id: 87, cat: "電腦系統", zh: "NTP", ja: "NTP", yomi: "えぬてぃーぴー", eng: "NTP", desc_zh: "用於同步網路時間的協定。", desc_ja: "時刻を同期するプロトコル。" },
    { id: 88, cat: "電腦系統", zh: "ARP", ja: "ARP", yomi: "あーぷ", eng: "ARP", desc_zh: "從 IP 地址查詢 MAC 地址的協定。", desc_ja: "IPアドレスからMACアドレスを調べるプロトコル。" },
    { id: 89, cat: "電腦系統", zh: "路由器", ja: "ルータ", yomi: "るーた", eng: "Router", desc_zh: "連接不同網路並進行路徑選擇 (Routing) 的設備。", desc_ja: "異なるNWを接続し、経路選択を行う機器。" },
    { id: 90, cat: "電腦系統", zh: "交換器", ja: "スイッチ", yomi: "すいっち", eng: "Switch", desc_zh: "在同一網路內根據 MAC 地址轉發資料的設備。", desc_ja: "NW内でMACアドレスを見てデータを転送する機器。" },
    { id: 91, cat: "電腦系統", zh: "防火牆", ja: "ファイアウォール", yomi: "ふぁいあうぉーる", eng: "Firewall", desc_zh: "根據規則阻擋未經授權的網路存取。", desc_ja: "不正なアクセスを遮断する壁。" },
    { id: 92, cat: "電腦系統", zh: "WAF", ja: "WAF", yomi: "わふ", eng: "WAF", desc_zh: "專門保護 Web 應用程式的防火牆。", desc_ja: "Webアプリを保護するファイアウォール。" },
    { id: 93, cat: "電腦系統", zh: "DMZ", ja: "DMZ", yomi: "でぃーえむぜっと", eng: "DMZ", desc_zh: "非軍事區，放置公開伺服器以隔離內網。", desc_ja: "非武装地帯。外部公開サーバを置く緩衝地帯。" },
    { id: 94, cat: "電腦系統", zh: "VPN", ja: "VPN", yomi: "ぶいぴーえぬ", eng: "VPN", desc_zh: "在公網上建立加密通道的虛擬私有網路。", desc_ja: "公衆回線上に作る仮想的な専用線。" },
    { id: 95, cat: "電腦系統", zh: "惡意軟體", ja: "マルウェア", yomi: "まるうぇあ", eng: "Malware", desc_zh: "惡意程式的總稱 (病毒、蠕蟲等)。", desc_ja: "悪意のあるプログラムの総称。" },
    { id: 96, cat: "電腦系統", zh: "勒索軟體", ja: "ランサムウェア", yomi: "らんさむうぇあ", eng: "Ransomware", desc_zh: "加密檔案並勒索贖金的惡意軟體。", desc_ja: "ファイルを暗号化し、身代金を要求するソフト。" },
    { id: 97, cat: "電腦系統", zh: "網路釣魚", ja: "フィッシング", yomi: "ふぃっしんぐ", eng: "Phishing", desc_zh: "偽裝成合法網站騙取個資。", desc_ja: "偽サイトに誘導し、個人情報を盗む詐欺。" },
    { id: 98, cat: "電腦系統", zh: "社交工程", ja: "ソーシャルエンジニアリング", yomi: "そーしゃる", eng: "Social Engineering", desc_zh: "利用心理弱點 (如電話詐騙、偷看) 獲取資訊。", desc_ja: "人の心理的隙をついて情報を盗む手法。" },
    { id: 99, cat: "電腦系統", zh: "DoS攻擊", ja: "DoS攻撃", yomi: "どすこうげき", eng: "DoS Attack", desc_zh: "發送大量請求使伺服器癱瘓。", desc_ja: "大量の負荷をかけ、サービスを停止させる攻撃。" },
    { id: 100, cat: "電腦系統", zh: "SQL注入", ja: "SQLインジェクション", yomi: "えすきゅーえる", eng: "SQL Injection", desc_zh: "在輸入欄位注入惡意 SQL 指令以攻擊資料庫。", desc_ja: "入力欄に悪意あるSQLを注入しDBを操作する攻撃。" },
    { id: 101, cat: "電腦系統", zh: "XSS", ja: "XSS", yomi: "くろすさいと", eng: "XSS", desc_zh: "跨站腳本攻擊，在網頁植入惡意腳本。", desc_ja: "Webに悪意あるスクリプトを埋め込む攻撃。" },
    { id: 102, cat: "電腦系統", zh: "暴力破解", ja: "ブルートフォース", yomi: "ぶるーとふぉーす", eng: "Brute Force", desc_zh: "嘗試所有可能的密碼組合。", desc_ja: "全てのパスワードの組み合わせを試す攻撃。" },
    { id: 103, cat: "電腦系統", zh: "多因素認證", ja: "多要素認証", yomi: "たようそにんしょう", eng: "MFA", desc_zh: "結合密碼、生物特徵等兩種以上要素進行驗證。", desc_ja: "知識・所有・生体の2つ以上で認証する。" },
    { id: 104, cat: "電腦系統", zh: "生物辨識", ja: "バイオメトリクス", yomi: "ばいおめとりくす", eng: "Biometrics", desc_zh: "利用指紋、虹膜等身體特徵進行認證。", desc_ja: "指紋や静脈など、身体的特徴で行う認証。" },
    { id: 105, cat: "電腦系統", zh: "CA", ja: "認証局", yomi: "にんしょうきょく", eng: "CA", desc_zh: "發行數位憑證的公正第三方機構。", desc_ja: "デジタル証明書を発行する第三者機関。" },
    { id: 106, cat: "技術管理", zh: "物件導向", ja: "オブジェクト指向", yomi: "おぶじぇくとしこう", eng: "Object-Oriented", desc_zh: "將資料與處理程序視為「物件」來建構軟體。", desc_ja: "データと処理を「モノ」として扱う開発手法。" },
    { id: 107, cat: "技術管理", zh: "類別", ja: "クラス", yomi: "くらす", eng: "Class", desc_zh: "物件的設計圖或模板。", desc_ja: "オブジェクトの設計図。" },
    { id: 108, cat: "技術管理", zh: "實體", ja: "インスタンス", yomi: "いんすたんす", eng: "Instance", desc_zh: "根據類別產生的實際物件。", desc_ja: "クラスから生成された実体。" },
    { id: 109, cat: "技術管理", zh: "封裝", ja: "カプセル化", yomi: "かぷせるか", eng: "Encapsulation", desc_zh: "隱藏物件內部的資料與實作細節。", desc_ja: "データと手続きをまとめ、詳細を隠蔽すること。" },
    { id: 110, cat: "技術管理", zh: "繼承", ja: "継承", yomi: "けいしょう", eng: "Inheritance", desc_zh: "承接既有類別的屬性與方法。", desc_ja: "既存クラスの性質を受け継ぐこと。" },
    { id: 111, cat: "技術管理", zh: "多型", ja: "ポリモーフィズム", yomi: "ぽりもーふぃずむ", eng: "Polymorphism", desc_zh: "同一訊息對不同物件有不同反應。", desc_ja: "同じ命令でも対象によって振る舞いが変わる性質。" },
    { id: 112, cat: "技術管理", zh: "UML", ja: "UML", yomi: "ゆーえむえる", eng: "UML", desc_zh: "軟體設計的標準圖示語言。", desc_ja: "ソフトウェア設計のための統一モデリング言語。" },
    { id: 113, cat: "技術管理", zh: "類別圖", ja: "クラス図", yomi: "くらすず", eng: "Class Diagram", desc_zh: "描述類別之間的靜態關係。", desc_ja: "クラス間の静的な関係を表す図。" },
    { id: 114, cat: "技術管理", zh: "使用案例圖", ja: "ユースケース図", yomi: "ゆーすけーすず", eng: "Use Case Diagram", desc_zh: "從使用者角度描述系統功能的圖。", desc_ja: "利用者視点でシステム機能を表す図。" },
    { id: 115, cat: "技術管理", zh: "黑箱測試", ja: "ブラックボックステスト", yomi: "ぶらっくぼっくすてすと", eng: "Black-box Testing", desc_zh: "只關注輸入與輸出，不看內部構造的測試。", desc_ja: "内部構造を見ず、入力と出力だけを確認するテスト。" },
    { id: 116, cat: "技術管理", zh: "白箱測試", ja: "ホワイトボックステスト", yomi: "ほわいとぼっくすてすと", eng: "White-box Testing", desc_zh: "檢查程式內部邏輯與結構的測試。", desc_ja: "プログラムの内部構造や論理を確認するテスト。" },
    { id: 117, cat: "技術管理", zh: "單元測試", ja: "単体テスト", yomi: "たんたいてすと", eng: "Unit Testing", desc_zh: "針對個別模組進行的測試。", desc_ja: "個々のモジュール単位で行うテスト。" },
    { id: 118, cat: "技術管理", zh: "整合測試", ja: "結合テスト", yomi: "けつごうてすと", eng: "Integration Testing", desc_zh: "組合多個模組進行的測試。", desc_ja: "複数のモジュールを組み合わせて行うテスト。" },
    { id: 119, cat: "技術管理", zh: "系統測試", ja: "システムテスト", yomi: "しすてむてすと", eng: "System Testing", desc_zh: "針對整個系統是否符合需求進行測試。", desc_ja: "システム全体が要件を満たすか確認するテスト。" },
    { id: 120, cat: "技術管理", zh: "DevOps", ja: "DevOps", yomi: "でぼぷす", eng: "DevOps", desc_zh: "開發 (Dev) 與維運 (Ops) 合作以加速開發。", desc_ja: "開発と運用が連携し、迅速に開発する手法。" },
    { id: 121, cat: "技術管理", zh: "ITIL", ja: "ITIL", yomi: "あいてぃる", eng: "ITIL", desc_zh: "IT 服務管理的最佳實務彙編。", desc_ja: "ITサービス管理の成功事例集。" },
    { id: 122, cat: "技術管理", zh: "服務台", ja: "サービスデスク", yomi: "さーびすですく", eng: "Service Desk", desc_zh: "使用者的單一聯繫窗口。", desc_ja: "利用者からの問い合わせ窓口（単一接点）。" },
    { id: 123, cat: "技術管理", zh: "事件管理", ja: "インシデント管理", yomi: "いんしでんとかんり", eng: "Incident Mgmt", desc_zh: "目標是盡快恢復服務正常運作。", desc_ja: "サービスの迅速な復旧を目的とする管理。" },
    { id: 124, cat: "技術管理", zh: "問題管理", ja: "問題管理", yomi: "もんだいかんり", eng: "Problem Mgmt", desc_zh: "查明事件根本原因，防止再發。", desc_ja: "根本原因を究明し、再発防止を図る管理。" },
    { id: 125, cat: "技術管理", zh: "變更管理", ja: "変更管理", yomi: "へんこうかんり", eng: "Change Mgmt", desc_zh: "評估並批准對系統的變更。", desc_ja: "システムへの変更を評価・承認する管理。" },
    { id: 126, cat: "技術管理", zh: "PMBOK", ja: "PMBOK", yomi: "ぴんぼっく", eng: "PMBOK", desc_zh: "專案管理的知識體系指南。", desc_ja: "プロジェクト管理の知識体系ガイド。" },
    { id: 127, cat: "技術管理", zh: "範疇", ja: "スコープ", yomi: "すこーぷ", eng: "Scope", desc_zh: "專案的工作範圍。", desc_ja: "プロジェクトの作業範囲。" },
    { id: 128, cat: "技術管理", zh: "風險管理", ja: "リスク管理", yomi: "りすくかんり", eng: "Risk Mgmt", desc_zh: "識別並應對潛在風險的過程。", desc_ja: "リスクを特定し、対策を講じるプロセス。" },
    { id: 129, cat: "技術管理", zh: "AI", ja: "AI", yomi: "えーあい", eng: "AI", desc_zh: "人工智慧。", desc_ja: "人工知能。" },
    { id: 130, cat: "技術管理", zh: "機器學習", ja: "機械学習", yomi: "きかいがくしゅう", eng: "Machine Learning", desc_zh: "讓電腦從數據中學習規則的技術。", desc_ja: "データからコンピュータが学習する技術。" },
    { id: 131, cat: "技術管理", zh: "深度學習", ja: "ディープラーニング", yomi: "でぃーぷらーにんぐ", eng: "Deep Learning", desc_zh: "模仿人腦神經網路的機器學習技術。", desc_ja: "脳神経回路を模した機械学習技術。" },
    { id: 132, cat: "技術管理", zh: "大數據", ja: "ビッグデータ", yomi: "びっぐでーた", eng: "Big Data", desc_zh: "巨大且多樣化的資料集合。", desc_ja: "巨大で多種多様なデータ群。" },
    { id: 133, cat: "技術管理", zh: "區塊鏈", ja: "ブロックチェーン", yomi: "ぶろっくちぇーん", eng: "Blockchain", desc_zh: "分散式帳本技術，難以竄改。", desc_ja: "分散型台帳技術。改ざんが困難。" },
    { id: 134, cat: "技術管理", zh: "雲端運算", ja: "クラウドコンピューティング", yomi: "くらうどこんぴゅーてぃんぐ", eng: "Cloud Computing", desc_zh: "透過網路使用伺服器資源的服務。", desc_ja: "ネット経由でIT資源を利用する形態。" },
    { id: 135, cat: "技術管理", zh: "SaaS", ja: "SaaS", yomi: "さーす", eng: "SaaS", desc_zh: "透過網路提供軟體功能 (如 Gmail)。", desc_ja: "ソフトの機能をネット経由で提供する。" },
    { id: 136, cat: "技術管理", zh: "PaaS", ja: "PaaS", yomi: "ぱーす", eng: "PaaS", desc_zh: "提供應用程式開發平台。", desc_ja: "アプリ開発のプラットフォームを提供する。" },
    { id: 137, cat: "技術管理", zh: "IaaS", ja: "IaaS", yomi: "いあーす", eng: "IaaS", desc_zh: "提供虛擬機、網路等基礎設施。", desc_ja: "仮想機やNWなどインフラを提供する。" },
    { id: 138, cat: "技術管理", zh: "邊緣運算", ja: "エッジコンピューティング", yomi: "えっじこんぴゅーてぃんぐ", eng: "Edge Computing", desc_zh: "在靠近使用者的位置處理數據以降低延遲。", desc_ja: "端末の近くで処理し、遅延を減らす技術。" },
    { id: 139, cat: "技術管理", zh: "著作權", ja: "著作権", yomi: "ちょさくけん", eng: "Copyright", desc_zh: "保護創作物的權利 (包含程式碼)。", desc_ja: "創作物を保護する権利 (プログラム含む)。" },
    { id: 140, cat: "技術管理", zh: "專利權", ja: "特許権", yomi: "とっきょけん", eng: "Patent", desc_zh: "保護發明與技術構想的權利。", desc_ja: "発明や技術的アイデアを保護する権利。" },
    { id: 141, cat: "技術管理", zh: "商標權", ja: "商標権", yomi: "しょうひょうけん", eng: "Trademark", desc_zh: "保護品牌名稱與標誌的權利。", desc_ja: "ブランド名やロゴを保護する権利。" },
    { id: 142, cat: "技術管理", zh: "營業秘密", ja: "営業秘密", yomi: "えいぎょうひみつ", eng: "Trade Secret", desc_zh: "具有秘密性與價值的商業資訊。", desc_ja: "秘密として管理される有用な情報。" },
    { id: 143, cat: "技術管理", zh: "PL法", ja: "PL法", yomi: "ぴーえるほう", eng: "PL Law", desc_zh: "產品責任法，針對產品缺陷造成損害的賠償。", desc_ja: "製造物責任法。製品の欠陥による損害賠償。" },
    { id: 144, cat: "技術管理", zh: "勞動派遣", ja: "労働者派遣", yomi: "ろうどうしゃはけん", eng: "Dispatching", desc_zh: "勞工接受派遣公司指揮，到客戶端工作。", desc_ja: "派遣元と雇用契約し、派遣先の指揮で働く。" },
    { id: 145, cat: "技術管理", zh: "承包", ja: "請負", yomi: "うけおい", eng: "Contracting", desc_zh: "承諾完成工作以換取報酬，指揮權在承包商。", desc_ja: "成果物の完成を約束する。指揮権は請負側。" },
    { id: 146, cat: "技術管理", zh: "準委任", ja: "準委任", yomi: "じゅんいにん", eng: "Quasi-mandate", desc_zh: "受託處理業務，不保證完成成果 (如顧問)。", desc_ja: "業務処理を委託する。完成責任はない。" },
    { id: 147, cat: "技術管理", zh: "個資法", ja: "個人情報保護法", yomi: "こじんじょうほうほごほう", eng: "APPI", desc_zh: "保護個人隱私資訊的法律。", desc_ja: "個人のプライバシー情報を守る法律。" },
    { id: 148, cat: "技術管理", zh: "合規", ja: "コンプライアンス", yomi: "こんぷらいあんす", eng: "Compliance", desc_zh: "企業遵守法律與倫理規範。", desc_ja: "法令遵守。企業がルールを守ること。" },
    { id: 149, cat: "技術管理", zh: "CSR", ja: "CSR", yomi: "しーえすあーる", eng: "CSR", desc_zh: "企業社會責任。", desc_ja: "企業の社会的責任。" },
    { id: 150, cat: "技術管理", zh: "SDGs", ja: "SDGs", yomi: "えすでぃーじーず", eng: "SDGs", desc_zh: "永續發展目標。", desc_ja: "持続可能な開発目標。" },
    { id: 151, cat: "基礎理論", zh: "逆波蘭表示法", ja: "逆ポーランド記法", yomi: "ぎゃくぽーらんどきほう", eng: "RPN", desc_zh: "將運算子寫在運算元後面的表示法。", desc_ja: "演算子を被演算子の後ろに記述する方法。" },
    { id: 152, cat: "基礎理論", zh: "遞迴", ja: "再帰", yomi: "さいき", eng: "Recursive", desc_zh: "函數在執行過程中呼叫自身的技巧。", desc_ja: "関数が自分自身を呼び出すこと。" },
    { id: 153, cat: "基礎理論", zh: "演算法複雜度", ja: "計算量", yomi: "けいさんりょう", eng: "Computational Complexity", desc_zh: "衡量演算法執行時間或空間的指標 (O(n))。", desc_ja: "アルゴリズムの実行時間やメモリ使用量の尺度。" },
    { id: 154, cat: "基礎理論", zh: "有限狀態機", ja: "オートマトン", yomi: "おーとまとん", eng: "Automaton", desc_zh: "根據輸入在不同狀態間轉換的模型。", desc_ja: "入力に応じて状態が遷移するモデル。" },
    { id: 155, cat: "基礎理論", zh: "真值表", ja: "真理値表", yomi: "しんりちひょう", eng: "Truth Table", desc_zh: "列出邏輯電路所有可能輸入與輸出的表格。", desc_ja: "論理回路の全入力と出力の組み合わせを表にしたもの。" },
    { id: 156, cat: "基礎理論", zh: "NAND 閘", ja: "NAND ゲート", yomi: "なんどげーと", eng: "NAND Gate", desc_zh: "只有當所有輸入為 1 時，輸出才為 0。", desc_ja: "入力が全て1の時だけ0を出力する。" },
    { id: 157, cat: "基礎理論", zh: "堆積", ja: "ヒープ", yomi: "ひーぷ", eng: "Heap", desc_zh: "一種特殊的樹狀結構，用於優先權佇列。", desc_ja: "優先度付きキューなどに使われる木構造。" },
    { id: 158, cat: "基礎理論", zh: "雜湊碰撞", ja: "シノニム", yomi: "しのにむ", eng: "Synonym", desc_zh: "雜湊法中，不同資料計算出相同雜湊值的現象。", desc_ja: "異なるデータから同じハッシュ値が出ること。" },
    { id: 159, cat: "基礎理論", zh: "根目錄", ja: "ルートディレクトリ", yomi: "るーとでぃれくとり", eng: "Root Directory", desc_zh: "檔案系統階層結構的最頂層。", desc_ja: "ファイル階層構造の最上位。" },
    { id: 160, cat: "基礎理論", zh: "絕對路徑", ja: "絶対パス", yomi: "ぜったいぱす", eng: "Absolute Path", desc_zh: "從根目錄開始完整描述檔案位置的路徑。", desc_ja: "ルートからファイル位置を完全に記述するパス。" },
    { id: 161, cat: "電腦系統", zh: "暫存器", ja: "レジスタ", yomi: "れじすた", eng: "Register", desc_zh: "CPU 內部速度最快的超小型記憶體。", desc_ja: "CPU内部にある超高速な記憶領域。" },
    { id: 162, cat: "電腦系統", zh: "時脈頻率", ja: "クロック周波数", yomi: "くろっくしゅうはすう", eng: "Clock Frequency", desc_zh: "CPU 每秒執行的週期數 (Hz)。", desc_ja: "CPUの処理速度の指標。Hzで表す。" },
    { id: 163, cat: "電腦系統", zh: "匯流排", ja: "バス", yomi: "ばす", eng: "Bus", desc_zh: "電腦內部傳輸資料的通道。", desc_ja: "コンピュータ内部のデータ伝送路。" },
    { id: 164, cat: "電腦系統", zh: "A/D轉換器", ja: "A/D変換器", yomi: "えーでぃーへんかんき", eng: "A/D Converter", desc_zh: "將類比訊號 (如聲音) 轉為數位訊號。", desc_ja: "アナログ信号をデジタル信号に変換する。" },
    { id: 165, cat: "電腦系統", zh: "致動器", ja: "アクチュエータ", yomi: "あくちゅえーた", eng: "Actuator", desc_zh: "將電訊號轉換為物理動作的裝置 (如馬達)。", desc_ja: "電気信号を物理的な動きに変える装置。" },
    { id: 166, cat: "電腦系統", zh: "感測器", ja: "センサ", yomi: "せんさ", eng: "Sensor", desc_zh: "檢測物理量 (光、溫度) 並轉為電子訊號。", desc_ja: "物理量(光・温度)を検知し信号にする。" },
    { id: 167, cat: "電腦系統", zh: "嵌入式系統", ja: "組込みシステム", yomi: "くみこみしすてむ", eng: "Embedded System", desc_zh: "內建於機器中，執行特定功能的電腦。", desc_ja: "機器に内蔵され特定機能を実現するPC。" },
    { id: 168, cat: "電腦系統", zh: "隨插即用", ja: "プラグアンドプレイ", yomi: "ぷらぐあんどぷれい", eng: "Plug and Play", desc_zh: "連接裝置後自動設定即可使用。", desc_ja: "機器接続時に自動設定ですぐ使える機能。" },
    { id: 169, cat: "電腦系統", zh: "HDMI", ja: "HDMI", yomi: "えいちでぃーえむあい", eng: "HDMI", desc_zh: "傳輸高品質影像與聲音的數位介面。", desc_ja: "映像と音声を伝送するデジタル端子。" },
    { id: 170, cat: "電腦系統", zh: "USB", ja: "USB", yomi: "ゆーえすびー", eng: "USB", desc_zh: "通用的序列匯流排介面，支援熱插拔。", desc_ja: "汎用的なシリアルバス規格。" },
    { id: 171, cat: "電腦系統", zh: "藍牙", ja: "Bluetooth", yomi: "ぶるーとぅーす", eng: "Bluetooth", desc_zh: "短距離低功耗的無線通訊技術。", desc_ja: "近距離・低消費電力の無線通信技術。" },
    { id: 172, cat: "電腦系統", zh: "SRAM", ja: "SRAM", yomi: "えすらむ", eng: "SRAM", desc_zh: "速度快不需要更新動作，常用於快取。", desc_ja: "高速でリフレッシュ不要。キャッシュに利用。" },
    { id: 173, cat: "電腦系統", zh: "DRAM", ja: "DRAM", yomi: "でぃーらむ", eng: "DRAM", desc_zh: "需定期更新動作，容量大，用於主記憶體。", desc_ja: "リフレッシュ必要。主記憶に利用。" },
    { id: 174, cat: "電腦系統", zh: "快閃記憶體", ja: "フラッシュメモリ", yomi: "ふらっしゅめもり", eng: "Flash Memory", desc_zh: "可電子抹除的非揮發性記憶體 (如 USB)。", desc_ja: "電気的に消去可能な不揮発性メモリ。" },
    { id: 175, cat: "電腦系統", zh: "多核心", ja: "マルチコア", yomi: "まるちこあ", eng: "Multi-core", desc_zh: "一個 CPU 封裝中包含多個處理核心。", desc_ja: "1つのCPUに複数の処理コアを持つこと。" },
    { id: 176, cat: "電腦系統", zh: "周轉時間", ja: "ターンアラウンドタイム", yomi: "たーんあらうんどたいむ", eng: "Turnaround Time", desc_zh: "從提交工作到輸出結果的總時間。", desc_ja: "処理依頼から結果出力までの全時間。" },
    { id: 177, cat: "電腦系統", zh: "回應時間", ja: "レスポンスタイム", yomi: "れすぽんすたいむ", eng: "Response Time", desc_zh: "從發出指令到系統開始反應的時間。", desc_ja: "指示から反応が始まるまでの時間。" },
    { id: 178, cat: "電腦系統", zh: "吞吐量", ja: "スループット", yomi: "するーぷっと", eng: "Throughput", desc_zh: "單位時間內處理的工作量。", desc_ja: "単位時間あたりの処理能力。" },
    { id: 179, cat: "電腦系統", zh: "多工處理", ja: "マルチタスク", yomi: "まるちたすく", eng: "Multitasking", desc_zh: "同時執行多個程式的技術。", desc_ja: "複数の処理を並行して行う技術。" },
    { id: 180, cat: "電腦系統", zh: "假脫機", ja: "スプーリング", yomi: "すぷーりんぐ", eng: "Spooling", desc_zh: "將資料暫存以緩解慢速裝置的等待。", desc_ja: "データを一時保存し、待ちを減らす。" },
    { id: 181, cat: "電腦系統", zh: "死結", ja: "デッドロック", yomi: "でっどろっく", eng: "Deadlock", desc_zh: "兩個程序互等對方釋放資源，導致停擺。", desc_ja: "処理が互いの資源空きを待ち、停止する状態。" },
    { id: 182, cat: "電腦系統", zh: "記憶體洩漏", ja: "メモリリーク", yomi: "めもりりーく", eng: "Memory Leak", desc_zh: "程式未釋放不再使用的記憶體。", desc_ja: "メモリが解放されず、使用可能領域が減る。" },
    { id: 183, cat: "電腦系統", zh: "碎片化", ja: "フラグメンテーション", yomi: "ふらぐめんてーしょん", eng: "Fragmentation", desc_zh: "記憶體或硬碟空間變得零散，降低效率。", desc_ja: "記憶領域が断片化し、効率が落ちる現象。" },
    { id: 184, cat: "電腦系統", zh: "排程", ja: "スケジューリング", yomi: "すけじゅーりんぐ", eng: "Scheduling", desc_zh: "決定 CPU 分配給哪個程序的機制。", desc_ja: "CPUをどの処理に割り当てるか決めること。" },
    { id: 185, cat: "電腦系統", zh: "輪詢", ja: "ラウンドロビン", yomi: "らうんどろびん", eng: "Round Robin", desc_zh: "依序分配固定時間給每個程序。", desc_ja: "各処理に一定時間を順に割り当てる方式。" },
    { id: 186, cat: "電腦系統", zh: "目錄", ja: "ディレクトリ", yomi: "でぃれくとり", eng: "Directory", desc_zh: "用於分類和管理檔案的資料夾。", desc_ja: "ファイルを整理・管理するフォルダ。" },
    { id: 187, cat: "電腦系統", zh: "壓縮", ja: "圧縮", yomi: "あっしゅく", eng: "Compression", desc_zh: "縮小檔案容量的技術。", desc_ja: "データのサイズを小さくする技術。" },
    { id: 188, cat: "電腦系統", zh: "封存", ja: "アーカイブ", yomi: "あーかいぶ", eng: "Archive", desc_zh: "將多個檔案整合成一個檔案。", desc_ja: "複数ファイルを一つにまとめること。" },
    { id: 189, cat: "電腦系統", zh: "GUI", ja: "GUI", yomi: "じーゆーあい", eng: "GUI", desc_zh: "透過圖形和滑鼠操作的介面。", desc_ja: "画像やマウスで操作する画面。" },
    { id: 190, cat: "電腦系統", zh: "CUI", ja: "CUI", yomi: "しーゆーあい", eng: "CUI", desc_zh: "透過鍵盤輸入文字指令操作的介面。", desc_ja: "文字入力で操作する画面。" },
    { id: 191, cat: "電腦系統", zh: "子網路遮罩", ja: "サブネットマスク", yomi: "さぶねっとますく", eng: "Subnet Mask", desc_zh: "用來區分 IP 位址中網路位址與主機位址。", desc_ja: "IPアドレスのNW部とホスト部を分ける。" },
    { id: 192, cat: "電腦系統", zh: "預設閘道", ja: "デフォルトゲートウェイ", yomi: "でふぉるとげーとうぇい", eng: "Default Gateway", desc_zh: "通往外部網路的出口 (路由器)。", desc_ja: "外部NWへの出入り口 (ルータ等)。" },
    { id: 193, cat: "電腦系統", zh: "IPv6", ja: "IPv6", yomi: "あいぴーぶいろく", eng: "IPv6", desc_zh: "128位元的 IP 地址，解決 IPv4 枯竭問題。", desc_ja: "128ビットのIPアドレス。IPv4枯渇対策。" },
    { id: 194, cat: "電腦系統", zh: "連接埠號", ja: "ポート番号", yomi: "ぽーとばんごう", eng: "Port Number", desc_zh: "識別通訊應用程式的編號 (80=Web)。", desc_ja: "アプリを識別する番号 (80=Web等)。" },
    { id: 195, cat: "電腦系統", zh: "HTTPS", ja: "HTTPS", yomi: "えいちてぃーてぃーぴーえす", eng: "HTTPS", desc_zh: "加密的 HTTP 通訊。", desc_ja: "暗号化されたWeb通信。" },
    { id: 196, cat: "電腦系統", zh: "SSH", ja: "SSH", yomi: "えすえすえいち", eng: "SSH", desc_zh: "遠端安全登入並操作電腦的協定。", desc_ja: "遠隔地から安全に操作するプロトコル。" },
    { id: 197, cat: "電腦系統", zh: "代理伺服器", ja: "プロキシ", yomi: "ぷろきし", eng: "Proxy", desc_zh: "代替內部電腦存取網際網路的伺服器。", desc_ja: "代理でネット接続するサーバ。" },
    { id: 198, cat: "電腦系統", zh: "LAN", ja: "LAN", yomi: "らん", eng: "LAN", desc_zh: "區域網路 (如辦公室或家庭內)。", desc_ja: "構内ネットワーク。" },
    { id: 199, cat: "電腦系統", zh: "WAN", ja: "WAN", yomi: "わん", eng: "WAN", desc_zh: "廣域網路 (連接不同地點的網路)。", desc_ja: "広域ネットワーク。" },
    { id: 200, cat: "電腦系統", zh: "Ping", ja: "Ping", yomi: "ぴん", eng: "Ping", desc_zh: "確認網路連線是否通暢的指令。", desc_ja: "接続確認を行うコマンド。" },
    { id: 201, cat: "電腦系統", zh: "封包", ja: "パケット", yomi: "ぱけっと", eng: "Packet", desc_zh: "網路傳輸的資料小塊。", desc_ja: "通信データの小包。" },
    { id: 202, cat: "電腦系統", zh: "VLAN", ja: "VLAN", yomi: "ぶいらん", eng: "VLAN", desc_zh: "在物理網路上邏輯分割出的虛擬網路。", desc_ja: "仮想的に分割されたLAN。" },
    { id: 203, cat: "電腦系統", zh: "ESSID", ja: "ESSID", yomi: "いーえすえすあいでぃー", eng: "ESSID", desc_zh: "無線網路基地台的識別名稱。", desc_ja: "無線LANアクセスポイントの識別名。" },
    { id: 204, cat: "電腦系統", zh: "MIME", ja: "MIME", yomi: "まいむ", eng: "MIME", desc_zh: "讓電子郵件支援文字以外格式的標準。", desc_ja: "メールで画像等を扱うための規格。" },
    { id: 205, cat: "電腦系統", zh: "VoIP", ja: "VoIP", yomi: "ぼいっぷ", eng: "VoIP", desc_zh: "在網路上傳輸語音的技術 (網路電話)。", desc_ja: "ネットで音声を送る技術 (IP電話)。" },
    { id: 206, cat: "電腦系統", zh: "SDN", ja: "SDN", yomi: "えすでぃーえぬ", eng: "SDN", desc_zh: "透過軟體集中控制網路架構。", desc_ja: "ソフトでNW構成を制御する技術。" },
    { id: 207, cat: "電腦系統", zh: "迴路位址", ja: "ループバックアドレス", yomi: "るーぷばっくあどれす", eng: "Loopback", desc_zh: "指向本機自己的 IP (127.0.0.1)。", desc_ja: "自分自身を指すIP (127.0.0.1)。" },
    { id: 208, cat: "電腦系統", zh: "廣播", ja: "ブロードキャスト", yomi: "ぶろーどきゃすと", eng: "Broadcast", desc_zh: "向網路上所有裝置發送資料。", desc_ja: "NW内の全機器にデータを送る。" },
    { id: 209, cat: "電腦系統", zh: "串流", ja: "ストリーミング", yomi: "すとりーみんぐ", eng: "Streaming", desc_zh: "邊下載邊播放影音的技術。", desc_ja: "DLしながら再生する技術。" },
    { id: 210, cat: "電腦系統", zh: "IoT閘道器", ja: "IoTゲートウェイ", yomi: "あいおーてぃーげーとうぇい", eng: "IoT Gateway", desc_zh: "連接感測器與雲端的橋樑設備。", desc_ja: "センサとクラウドを繋ぐ中継機。" },
    { id: 211, cat: "電腦系統", zh: "零信任", ja: "ゼロトラスト", yomi: "ぜろとらすと", eng: "Zero Trust", desc_zh: "不信任任何內外網，每次存取都驗證。", desc_ja: "全てを信頼せず毎回検証する概念。" },
    { id: 212, cat: "電腦系統", zh: "APT攻擊", ja: "APT攻撃", yomi: "えーぴーてぃーこうげき", eng: "APT Attack", desc_zh: "針對特定目標長期潛伏的持續性攻擊。", desc_ja: "特定の標的を執拗に攻撃する手法。" },
    { id: 213, cat: "電腦系統", zh: "字典攻擊", ja: "辞書攻撃", yomi: "じしょこうげき", eng: "Dictionary Attack", desc_zh: "使用常用單字列表嘗試破解密碼。", desc_ja: "単語リストを使ってパスワードを破る。" },
    { id: 214, cat: "電腦系統", zh: "彩虹表", ja: "レインボーテーブル", yomi: "れいんぼーてーぶる", eng: "Rainbow Table", desc_zh: "預先計算雜湊值以快速破解密碼的對照表。", desc_ja: "ハッシュ値を事前計算したクラック用表。" },
    { id: 215, cat: "電腦系統", zh: "加鹽", ja: "ソルト", yomi: "そると", eng: "Salting", desc_zh: "在密碼中加入隨機字串再雜湊，防止彩虹表。", desc_ja: "乱数を付加してハッシュ化し解読を防ぐ。" },
    { id: 216, cat: "電腦系統", zh: "鍵盤側錄", ja: "キーロガー", yomi: "きーろがー", eng: "Keylogger", desc_zh: "記錄使用者按鍵輸入的惡意軟體。", desc_ja: "キー入力操作を記録するスパイウェア。" },
    { id: 217, cat: "電腦系統", zh: "Rootkit", ja: "ルートキット", yomi: "るーときっと", eng: "Rootkit", desc_zh: "隱藏攻擊痕跡並維持入侵權限的工具包。", desc_ja: "侵入の痕跡を隠し権限を維持するツール。" },
    { id: 218, cat: "電腦系統", zh: "DDos攻擊", ja: "DDoS攻撃", yomi: "でぃーどすこうげき", eng: "DDoS", desc_zh: "利用多台電腦分散同時發動 DoS 攻擊。", desc_ja: "多数の機器から一斉に攻撃を仕掛ける。" },
    { id: 219, cat: "電腦系統", zh: "加密雜湊函數", ja: "ハッシュ関数", yomi: "はっしゅかんすう", eng: "Hash Function", desc_zh: "將資料轉換為固定長度亂碼，不可逆。", desc_ja: "データを固定長の要約値に変換する関数。" },
    { id: 220, cat: "電腦系統", zh: "PKI", ja: "PKI", yomi: "ぴーけーあい", eng: "PKI", desc_zh: "公開金鑰基礎建設，管理憑證的體系。", desc_ja: "公開鍵暗号基盤。証明書を管理する仕組み。" },
    { id: 221, cat: "電腦系統", zh: "CRL", ja: "CRL", yomi: "しーあーるえる", eng: "CRL", desc_zh: "憑證撤銷清單，列出已失效的數位憑證。", desc_ja: "有効期限前に無効になった証明書リスト。" },
    { id: 222, cat: "電腦系統", zh: "ISMS", ja: "ISMS", yomi: "あいえすえむえす", eng: "ISMS", desc_zh: "資訊安全管理系統。", desc_ja: "情報セキュリティマネジメントシステム。" },
    { id: 223, cat: "電腦系統", zh: "機密性", ja: "機密性", yomi: "きみつせい", eng: "Confidentiality", desc_zh: "資安三要素之一，確保只有授權者能存取。", desc_ja: "許可された人だけがアクセスできること。" },
    { id: 224, cat: "電腦系統", zh: "完整性", ja: "完全性", yomi: "かんぜんせい", eng: "Integrity", desc_zh: "資安三要素之一，確保資料準確未被竄改。", desc_ja: "データが正確で改ざんされていないこと。" },
    { id: 225, cat: "電腦系統", zh: "可用性", ja: "可用性", yomi: "かようせい", eng: "Availability", desc_zh: "資安三要素之一，確保需要時能使用系統。", desc_ja: "必要な時にいつでも使えること。" },
    { id: 226, cat: "電腦系統", zh: "風險評估", ja: "リスクアセスメント", yomi: "りすくあせすめんと", eng: "Risk Assessment", desc_zh: "分析威脅與脆弱性，評估潛在損失。", desc_ja: "脅威や脆弱性を分析し損失を予測する。" },
    { id: 227, cat: "電腦系統", zh: "BYOD", ja: "BYOD", yomi: "びーわいおーでぃー", eng: "BYOD", desc_zh: "員工攜帶私人設備處理公務。", desc_ja: "私物端末を業務に利用すること。" },
    { id: 228, cat: "電腦系統", zh: "MDM", ja: "MDM", yomi: "えむでぃーえむ", eng: "MDM", desc_zh: "行動裝置管理，統一控管員工手機平板。", desc_ja: "モバイル端末を統合管理するシステム。" },
    { id: 229, cat: "電腦系統", zh: "VPN通道", ja: "トンネリング", yomi: "とんねりんぐ", eng: "Tunneling", desc_zh: "在網路上建立虛擬傳輸通道的技術。", desc_ja: "仮想的な通信路を作る技術。" },
    { id: 230, cat: "電腦系統", zh: "混合雲", ja: "ハイブリッドクラウド", yomi: "はいぶりっどくらうど", eng: "Hybrid Cloud", desc_zh: "結合私有雲與公有雲的架構。", desc_ja: "私有雲と公有雲を組み合わせた形態。" },
    { id: 231, cat: "電腦系統", zh: "ER圖", ja: "E-R図", yomi: "いーあーるず", eng: "ER Diagram", desc_zh: "描述實體與關係的圖。", desc_ja: "実体と関係を表す図。" },
    { id: 232, cat: "電腦系統", zh: "NoSQL", ja: "NoSQL", yomi: "のーえすきゅーえる", eng: "NoSQL", desc_zh: "非關聯式資料庫的總稱，適合大數據。", desc_ja: "RDB以外のDB総称。ビッグデータ向き。" },
    { id: 233, cat: "電腦系統", zh: "資料倉儲", ja: "データウェアハウス", yomi: "でーたうぇあはうす", eng: "Data Warehouse", desc_zh: "整合多個來源的歷史資料，用於分析。", desc_ja: "分析用に時系列データを統合したもの。" },
    { id: 234, cat: "電腦系統", zh: "資料探勘", ja: "データマイニング", yomi: "でーたみにんぐ", eng: "Data Mining", desc_zh: "從大量資料中挖掘未知規則的技術。", desc_ja: "大量データから規則性を発掘する技術。" },
    { id: 235, cat: "技術管理", zh: "ABC分析", ja: "ABC分析", yomi: "えーびーしーぶんせき", eng: "ABC Analysis", desc_zh: "根據重要性將項目分為 A、B、C 三類。", desc_ja: "重要度で3ランクに分ける分析手法。" },
    { id: 236, cat: "技術管理", zh: "帕累托圖", ja: "パレート図", yomi: "ぱれーとず", eng: "Pareto Chart", desc_zh: "結合長條圖與累積曲線，找出主要問題。", desc_ja: "棒グラフと折れ線で重要項目を特定する。" },
    { id: 237, cat: "技術管理", zh: "散布圖", ja: "散布図", yomi: "さんぷず", eng: "Scatter Plot", desc_zh: "用點表示兩個變數間的關係 (相關性)。", desc_ja: "2変数の相関関係を見るグラフ。" },
    { id: 238, cat: "技術管理", zh: "損益表", ja: "損益計算書", yomi: "そんえきけいさんしょ", eng: "P/L", desc_zh: "顯示企業一段時間內的盈利狀況。", desc_ja: "企業の経営成績(利益)を表す表。" },
    { id: 239, cat: "技術管理", zh: "資產負債表", ja: "貸借対照表", yomi: "たいしゃくたいしょうひょう", eng: "B/S", desc_zh: "顯示企業在特定時間點的財務狀況。", desc_ja: "企業の財政状態(資産・負債)を表す表。" },
    { id: 240, cat: "技術管理", zh: "ROI", ja: "ROI", yomi: "あーるおーあい", eng: "ROI", desc_zh: "投資報酬率，衡量投資獲利的指標。", desc_ja: "投資対効果。投資に対する利益率。" },
    { id: 241, cat: "技術管理", zh: "TCO", ja: "TCO", yomi: "てぃーしーおー", eng: "TCO", desc_zh: "總體擁有成本，包含採購、維護等。", desc_ja: "導入から廃棄までの総コスト。" },
    { id: 242, cat: "技術管理", zh: "損益平衡點", ja: "損益分岐点", yomi: "そんえきぶんきてん", eng: "Break-even Point", desc_zh: "收入與成本相等，不賺不賠的銷售額。", desc_ja: "利益がゼロになる売上高。" },
    { id: 243, cat: "技術管理", zh: "核心競爭力", ja: "コアコンピタンス", yomi: "こあこんぴたんす", eng: "Core Competence", desc_zh: "企業獨有的、他社難以模仿的強項。", desc_ja: "他社が真似できない核となる強み。" },
    { id: 244, cat: "技術管理", zh: "藍海策略", ja: "ブルーオーシャン", yomi: "ぶるーおーしゃん", eng: "Blue Ocean", desc_zh: "開創無競爭的新市場空間。", desc_ja: "競争のない未開拓市場を創る戦略。" },
    { id: 245, cat: "技術管理", zh: "長尾效應", ja: "ロングテール", yomi: "ろんぐてーる", eng: "Long Tail", desc_zh: "冷門商品總銷售額超過熱門商品的現象。", desc_ja: "死に筋商品の合計が売上の多くを占める。" },
    { id: 246, cat: "技術管理", zh: "腦力激盪", ja: "ブレーンストーミング", yomi: "ぶれーんすとーみんぐ", eng: "Brainstorming", desc_zh: "多人自由提出想法，禁止批評。", desc_ja: "批判禁止で自由にアイデアを出し合う。" },
    { id: 247, cat: "技術管理", zh: "KJ法", ja: "KJ法", yomi: "けーじぇいほう", eng: "KJ Method", desc_zh: "將點子寫在卡片上並分類整理的發想法。", desc_ja: "カードを使ってアイデアを整理する手法。" },
    { id: 248, cat: "技術管理", zh: "甘特圖", ja: "ガントチャート", yomi: "がんとちゃーと", eng: "Gantt Chart", desc_zh: "用條狀圖顯示專案進度的圖表。", desc_ja: "日程と進捗を横棒で表した図。" },
    { id: 249, cat: "技術管理", zh: "魚骨圖", ja: "特性要因図", yomi: "とくせいよういんず", eng: "Fishbone Diagram", desc_zh: "分析問題原因與結果關係的圖 (石川圖)。", desc_ja: "原因と結果の関係を整理する図。" },
    { id: 250, cat: "技術管理", zh: "雷達圖", ja: "レーダーチャート", yomi: "れーだーちゃーと", eng: "Radar Chart", desc_zh: "顯示多個項目平衡狀態的放射狀圖表。", desc_ja: "複数項目のバランスを見る放射状の図。" },

    // --- 新增：ID 251-300 ---
    { id: 251, cat: "電腦系統", zh: "高可用性", ja: "ハイアベイラビリティ", yomi: "はいあべいらびりてぃ", eng: "HA", desc_zh: "系統長時間持續運作不中斷的能力。", desc_ja: "システムが停止せず稼働し続ける能力。" },
    { id: 252, cat: "電腦系統", zh: "容錯", ja: "フォールトトレランス", yomi: "ふぉーるととれらんす", eng: "Fault Tolerance", desc_zh: "即使部分故障，系統仍能繼續運作的特性。", desc_ja: "一部が故障しても稼働を続ける性質。" },
    { id: 253, cat: "電腦系統", zh: "失效安全", ja: "フェールセーフ", yomi: "ふぇーるせーふ", eng: "Fail Safe", desc_zh: "故障時以安全為優先，停止系統運作。", desc_ja: "故障時に安全を優先しシステムを止める。" },
    { id: 254, cat: "電腦系統", zh: "失效軟運作", ja: "フェールソフト", yomi: "ふぇーるそふと", eng: "Fail Soft", desc_zh: "故障時降低效能，但維持基本運作。", desc_ja: "故障時に機能を落として継続する。" },
    { id: 255, cat: "電腦系統", zh: "雙工系統", ja: "デュプレックスシステム", yomi: "でゅぷれっくす", eng: "Duplex System", desc_zh: "主系統運作，副系統待機，故障時切換。", desc_ja: "主系で処理し待機系へ切り替える方式。" },
    { id: 256, cat: "電腦系統", zh: "雙重系統", ja: "デュアルシステム", yomi: "でゅあるしすてむ", eng: "Dual System", desc_zh: "兩套系統同時進行相同處理並比對結果。", desc_ja: "2系統で同じ処理を行い結果を照合する。" },
    { id: 257, cat: "電腦系統", zh: "叢集", ja: "クラスタ", yomi: "くらすた", eng: "Cluster", desc_zh: "多台電腦連接並像一台機器般運作。", desc_ja: "複数台を接続し1台のように見せる技術。" },
    { id: 258, cat: "電腦系統", zh: "NAS", ja: "NAS", yomi: "なす", eng: "Network Attached Storage", desc_zh: "連接網路直接使用的檔案儲存裝置。", desc_ja: "ネットに接続して使うファイルサーバ。" },
    { id: 259, cat: "電腦系統", zh: "SAN", ja: "SAN", yomi: "さん", eng: "Storage Area Network", desc_zh: "伺服器與儲存裝置之間的高速專用網路。", desc_ja: "サーバとストレージを結ぶ高速専用網。" },
    { id: 260, cat: "電腦系統", zh: "精簡型電腦", ja: "シンクライアント", yomi: "しんくらいあんと", eng: "Thin Client", desc_zh: "客戶端只負責顯示，處理在伺服器端進行。", desc_ja: "処理をサーバ側で行う最小限機能の端末。" },
    { id: 261, cat: "電腦系統", zh: "編譯器", ja: "コンパイラ", yomi: "こんぱいら", eng: "Compiler", desc_zh: "將原始碼一次性轉換為機器語言的程式。", desc_ja: "ソースを一括で機械語に変換するソフト。" },
    { id: 262, cat: "電腦系統", zh: "直譯器", ja: "インタプリタ", yomi: "いんたぷりた", eng: "Interpreter", desc_zh: "逐行翻譯並執行原始碼的程式。", desc_ja: "ソースを逐次翻訳しながら実行するソフト。" },
    { id: 263, cat: "電腦系統", zh: "連結器", ja: "リンカ", yomi: "りんか", eng: "Linker", desc_zh: "將編譯後的多個目的檔結合成執行檔。", desc_ja: "複数ファイルを結合し実行形式にする。" },
    { id: 264, cat: "電腦系統", zh: "載入器", ja: "ローダ", yomi: "ろーだ", eng: "Loader", desc_zh: "將執行檔載入記憶體並執行的程式。", desc_ja: "実行ファイルをメモリに読み込むソフト。" },
    { id: 265, cat: "電腦系統", zh: "垃圾回收", ja: "ガベージコレクション", yomi: "がべーじこれくしょん", eng: "Garbage Collection", desc_zh: "自動釋放不再使用的記憶體空間。", desc_ja: "不要なメモリ領域を自動的に解放する。" },
    { id: 266, cat: "電腦系統", zh: "遞迴呼叫", ja: "リエントラント", yomi: "りえんとらんと", eng: "Reentrant", desc_zh: "可重入，多個程式同時呼叫也不會出錯。", desc_ja: "複数のタスクから同時呼び出し可能な性質。" },
    { id: 267, cat: "電腦系統", zh: "動態連結函式庫", ja: "DLL", yomi: "でぃーえるえる", eng: "Dynamic Link Library", desc_zh: "程式執行時才載入的函式庫。", desc_ja: "実行時に結合されるライブラリ。" },
    { id: 268, cat: "電腦系統", zh: "UPS", ja: "UPS", yomi: "ゆーぴーえす", eng: "Uninterruptible Power Supply", desc_zh: "不斷電系統，停電時提供臨時電力。", desc_ja: "停電時に電力を供給する無停電電源装置。" },
    { id: 269, cat: "電腦系統", zh: "PWM", ja: "PWM", yomi: "ぴーだぶりゅーえむ", eng: "Pulse Width Modulation", desc_zh: "脈衝寬度調變，用於控制馬達轉速或LED亮度。", desc_ja: "パルス幅で電圧等を制御する方式。" },
    { id: 270, cat: "電腦系統", zh: "驅動程式", ja: "デバイスドライバ", yomi: "でばいすどらいば", eng: "Device Driver", desc_zh: "控制硬體裝置的軟體。", desc_ja: "周辺機器を制御するためのソフト。" },
    { id: 271, cat: "電腦系統", zh: "SNMP", ja: "SNMP", yomi: "えすえぬえむぴー", eng: "Simple Network Management", desc_zh: "監控網路設備狀態的協定。", desc_ja: "ネットワーク機器を監視するプロトコル。" },
    { id: 272, cat: "電腦系統", zh: "Telnet", ja: "Telnet", yomi: "てるねっと", eng: "Telnet", desc_zh: "早期的遠端登入協定 (未加密，不安全)。", desc_ja: "遠隔操作プロトコル (暗号化なし)。" },
    { id: 273, cat: "電腦系統", zh: "LPWA", ja: "LPWA", yomi: "えるぴーだぶりゅえー", eng: "Low Power Wide Area", desc_zh: "低功耗廣域網路，適合 IoT。", desc_ja: "省電力で広範囲をカバーする無線技術。" },
    { id: 274, cat: "電腦系統", zh: "5G", ja: "5G", yomi: "ふぁいぶじー", eng: "5th Generation", desc_zh: "第五代行動通訊 (高速、低延遲、多連結)。", desc_ja: "高速・低遅延・多数接続の移動通信。" },
    { id: 275, cat: "電腦系統", zh: "MAC位址過濾", ja: "MACアドレスフィルタリング", yomi: "まっくあどれすふぃるたりんぐ", eng: "MAC Filtering", desc_zh: "只允許特定 MAC 位址的裝置連線。", desc_ja: "特定のMACアドレスのみ接続を許可する。" },
    { id: 276, cat: "電腦系統", zh: "WPA3", ja: "WPA3", yomi: "だぶりゅーぴーえーすりー", eng: "WPA3", desc_zh: "最新的無線網路加密標準，比 WPA2 更安全。", desc_ja: "最新の無線LANセキュリティ規格。" },
    { id: 277, cat: "電腦系統", zh: "TPM", ja: "TPM", yomi: "てぃーぴーえむ", eng: "Trusted Platform Module", desc_zh: "內建於電腦主機板的安全晶片。", desc_ja: "PCにあるセキュリティチップ。" },
    { id: 278, cat: "電腦系統", zh: "沙箱", ja: "サンドボックス", yomi: "さんどぼっくす", eng: "Sandbox", desc_zh: "隔離的執行環境，用於測試不明程式。", desc_ja: "隔離された仮想環境。ウイルス解析に利用。" },
    { id: 279, cat: "電腦系統", zh: "滲透測試", ja: "ペネトレーションテスト", yomi: "ぺねとれーしょんてすと", eng: "Penetration Test", desc_zh: "模擬駭客攻擊以找出系統漏洞。", desc_ja: "侵入を試みて脆弱性を探すテスト。" },
    { id: 280, cat: "電腦系統", zh: "數位鑑識", ja: "デジタルフォレンジック", yomi: "でじたるふぉれんじっく", eng: "Digital Forensics", desc_zh: "收集與分析數位證據以調查犯罪。", desc_ja: "犯罪捜査のための電子的証拠解析。" },
    { id: 281, cat: "技術管理", zh: "PPM", ja: "PPM", yomi: "ぴーぴーえむ", eng: "Product Portfolio Management", desc_zh: "將產品分為問題兒、明星、金牛、敗犬。", desc_ja: "事業を4象限(花形・金のなる木等)で分析。" },
    { id: 282, cat: "技術管理", zh: "行銷4P", ja: "マーケティングミックス", yomi: "まーけてぃんぐみっくす", eng: "4P (Marketing Mix)", desc_zh: "產品、價格、通路、推廣。", desc_ja: "製品・価格・流通・販促の4要素。" },
    { id: 283, cat: "技術管理", zh: "4C", ja: "4C", yomi: "よんしー", eng: "4C", desc_zh: "從顧客觀點出發的行銷要素 (成本、便利性等)。", desc_ja: "顧客視点の4要素 (コスト・利便性等)。" },
    { id: 284, cat: "技術管理", zh: "RFM分析", ja: "RFM分析", yomi: "あーるえふえむぶんせき", eng: "RFM Analysis", desc_zh: "根據最近購買日、頻率、金額分析顧客。", desc_ja: "最新購買日・頻度・金額で顧客を分析。" },
    { id: 285, cat: "技術管理", zh: "BSC", ja: "バランススコアカード", yomi: "ばらんすすこあかーど", eng: "Balanced Scorecard", desc_zh: "從財務、顧客、流程、學習四個視角評估績效。", desc_ja: "財務・顧客・業務・学習の4視点で評価。" },
    { id: 286, cat: "技術管理", zh: "ERP", ja: "ERP", yomi: "いーあーるぴー", eng: "Enterprise Resource Planning", desc_zh: "企業資源規劃，整合管理企業資源。", desc_ja: "経営資源を統合的に管理するシステム。" },
    { id: 287, cat: "技術管理", zh: "SCM", ja: "SCM", yomi: "えすしーえむ", eng: "Supply Chain Management", desc_zh: "供應鏈管理，優化從生產到銷售的流程。", desc_ja: "供給連鎖管理。調達から販売まで最適化。" },
    { id: 288, cat: "技術管理", zh: "PLM", ja: "PLM", yomi: "ぴーえるえむ", eng: "Product Lifecycle Management", desc_zh: "產品生命週期管理，從開發到報廢。", desc_ja: "製品の企画から廃棄までを一元管理。" },
    { id: 289, cat: "技術管理", zh: "群眾募資", ja: "クラウドファンディング", yomi: "くらうどふぁんでぃんぐ", eng: "Crowdfunding", desc_zh: "透過網路向大眾募集資金。", desc_ja: "ネットで不特定多数から資金を集める。" },
    { id: 290, cat: "技術管理", zh: "共享經濟", ja: "シェアリングエコノミー", yomi: "しぇありんぐえこのみー", eng: "Sharing Economy", desc_zh: "個人之間共享資產或服務。", desc_ja: "個人間で資産やサービスを共有する。" },
    { id: 291, cat: "技術管理", zh: "遠距工作", ja: "テレワーク", yomi: "てれわーく", eng: "Telework", desc_zh: "利用 ICT 技術在遠端工作。", desc_ja: "ICTを活用し、離れた場所で働く。" },
    { id: 292, cat: "技術管理", zh: "無障礙設計", ja: "アクセシビリティ", yomi: "あくせしびりてぃ", eng: "Accessibility", desc_zh: "讓所有人 (含身障者) 都能使用的程度。", desc_ja: "高齢者や障害者を含む誰でも使える度合い。" },
    { id: 293, cat: "技術管理", zh: "通用設計", ja: "ユニバーサルデザイン", yomi: "ゆにばーさるでざいん", eng: "Universal Design", desc_zh: "設計成所有人都能方便使用的產品。", desc_ja: "最初から誰でも使いやすく設計すること。" },
    { id: 294, cat: "技術管理", zh: "NDA", ja: "NDA", yomi: "えぬでぃーえー", eng: "Non-Disclosure Agreement", desc_zh: "保密協定。", desc_ja: "秘密保持契約。" },
    { id: 295, cat: "技術管理", zh: "RFP", ja: "RFP", yomi: "あーるえふぴー", eng: "Request For Proposal", desc_zh: "建議書徵求文件，要求供應商提供提案。", desc_ja: "提案依頼書。ベンダに提案を求める文書。" },
    { id: 296, cat: "技術管理", zh: "RFI", ja: "RFI", yomi: "あーるえふあい", eng: "Request For Information", desc_zh: "資訊徵求文件，收集供應商的技術資訊。", desc_ja: "情報提供依頼書。技術情報を収集する。" },
    { id: 297, cat: "技術管理", zh: "PoC", ja: "PoC", yomi: "ぽっく", eng: "Proof of Concept", desc_zh: "概念驗證，測試新想法是否可行。", desc_ja: "概念実証。新しいアイデアの実現性を試す。" },
    { id: 298, cat: "技術管理", zh: "遊戲化", ja: "ゲーミフィケーション", yomi: "げーみふぃけーしょん", eng: "Gamification", desc_zh: "將遊戲元素應用於非遊戲領域。", desc_ja: "ゲームの要素を他分野に応用する。" },
    { id: 299, cat: "技術管理", zh: "SEO", ja: "SEO", yomi: "えすいーおー", eng: "Search Engine Optimization", desc_zh: "搜尋引擎最佳化，提升網站在搜尋結果的排名。", desc_ja: "検索エンジン最適化。" },
    { id: 300, cat: "技術管理", zh: "LBO", ja: "LBO", yomi: "えるびーおー", eng: "Leveraged Buyout", desc_zh: "槓桿收購，借錢來收購公司。", desc_ja: "買収先の資産を担保に資金を借りて買収。" }
];